// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	relayer "github.com/chainsafe/canton-middleware/pkg/relayer"
	mock "github.com/stretchr/testify/mock"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

type Service_Expecter struct {
	mock *mock.Mock
}

func (_m *Service) EXPECT() *Service_Expecter {
	return &Service_Expecter{mock: &_m.Mock}
}

// GetTransfer provides a mock function with given fields: ctx, id
func (_m *Service) GetTransfer(ctx context.Context, id string) (*relayer.Transfer, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetTransfer")
	}

	var r0 *relayer.Transfer
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*relayer.Transfer, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *relayer.Transfer); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*relayer.Transfer)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Service_GetTransfer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTransfer'
type Service_GetTransfer_Call struct {
	*mock.Call
}

// GetTransfer is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *Service_Expecter) GetTransfer(ctx interface{}, id interface{}) *Service_GetTransfer_Call {
	return &Service_GetTransfer_Call{Call: _e.mock.On("GetTransfer", ctx, id)}
}

func (_c *Service_GetTransfer_Call) Run(run func(ctx context.Context, id string)) *Service_GetTransfer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Service_GetTransfer_Call) Return(_a0 *relayer.Transfer, _a1 error) *Service_GetTransfer_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Service_GetTransfer_Call) RunAndReturn(run func(context.Context, string) (*relayer.Transfer, error)) *Service_GetTransfer_Call {
	_c.Call.Return(run)
	return _c
}

// ListTransfers provides a mock function with given fields: ctx, limit
func (_m *Service) ListTransfers(ctx context.Context, limit int) ([]*relayer.Transfer, error) {
	ret := _m.Called(ctx, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListTransfers")
	}

	var r0 []*relayer.Transfer
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) ([]*relayer.Transfer, error)); ok {
		return rf(ctx, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) []*relayer.Transfer); ok {
		r0 = rf(ctx, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*relayer.Transfer)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Service_ListTransfers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTransfers'
type Service_ListTransfers_Call struct {
	*mock.Call
}

// ListTransfers is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
func (_e *Service_Expecter) ListTransfers(ctx interface{}, limit interface{}) *Service_ListTransfers_Call {
	return &Service_ListTransfers_Call{Call: _e.mock.On("ListTransfers", ctx, limit)}
}

func (_c *Service_ListTransfers_Call) Run(run func(ctx context.Context, limit int)) *Service_ListTransfers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *Service_ListTransfers_Call) Return(_a0 []*relayer.Transfer, _a1 error) *Service_ListTransfers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Service_ListTransfers_Call) RunAndReturn(run func(context.Context, int) ([]*relayer.Transfer, error)) *Service_ListTransfers_Call {
	_c.Call.Return(run)
	return _c
}

// RegisterTransfer provides a mock function with given fields: ctx, req
func (_m *Service) RegisterTransfer(ctx context.Context, req *relayer.RegisterTransferRequest) (*relayer.RegisterTransferResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for RegisterTransfer")
	}

	var r0 *relayer.RegisterTransferResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *relayer.RegisterTransferRequest) (*relayer.RegisterTransferResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *relayer.RegisterTransferRequest) *relayer.RegisterTransferResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*relayer.RegisterTransferResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *relayer.RegisterTransferRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Service_RegisterTransfer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterTransfer'
type Service_RegisterTransfer_Call struct {
	*mock.Call
}

// RegisterTransfer is a helper method to define mock.On call
//   - ctx context.Context
//   - req *relayer.RegisterTransferRequest
func (_e *Service_Expecter) RegisterTransfer(ctx interface{}, req interface{}) *Service_RegisterTransfer_Call {
	return &Service_RegisterTransfer_Call{Call: _e.mock.On("RegisterTransfer", ctx, req)}
}

func (_c *Service_RegisterTransfer_Call) Run(run func(ctx context.Context, req *relayer.RegisterTransferRequest)) *Service_RegisterTransfer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*relayer.RegisterTransferRequest))
	})
	return _c
}

func (_c *Service_RegisterTransfer_Call) Return(_a0 *relayer.RegisterTransferResponse, _a1 error) *Service_RegisterTransfer_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Service_RegisterTransfer_Call) RunAndReturn(run func(context.Context, *relayer.RegisterTransferRequest) (*relayer.RegisterTransferResponse, error)) *Service_RegisterTransfer_Call {
	_c.Call.Return(run)
	return _c
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
