// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	common "github.com/ethereum/go-ethereum/common"
	mock "github.com/stretchr/testify/mock"
)

// Verifier is an autogenerated mock type for the Verifier type
type Verifier struct {
	mock.Mock
}

type Verifier_Expecter struct {
	mock *mock.Mock
}

func (_m *Verifier) EXPECT() *Verifier_Expecter {
	return &Verifier_Expecter{mock: &_m.Mock}
}

// Verify provides a mock function with given fields: message, signature
func (_m *Verifier) Verify(message string, signature string) (common.Address, string, error) {
	ret := _m.Called(message, signature)

	if len(ret) == 0 {
		panic("no return value specified for Verify")
	}

	var r0 common.Address
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(string, string) (common.Address, string, error)); ok {
		return rf(message, signature)
	}
	if rf, ok := ret.Get(0).(func(string, string) common.Address); ok {
		r0 = rf(message, signature)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(common.Address)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string) string); ok {
		r1 = rf(message, signature)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(string, string) error); ok {
		r2 = rf(message, signature)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Verifier_Verify_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Verify'
type Verifier_Verify_Call struct {
	*mock.Call
}

// Verify is a helper method to define mock.On call
//   - message string
//   - signature string
func (_e *Verifier_Expecter) Verify(message interface{}, signature interface{}) *Verifier_Verify_Call {
	return &Verifier_Verify_Call{Call: _e.mock.On("Verify", message, signature)}
}

func (_c *Verifier_Verify_Call) Run(run func(message string, signature string)) *Verifier_Verify_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *Verifier_Verify_Call) Return(_a0 common.Address, _a1 string, _a2 error) *Verifier_Verify_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *Verifier_Verify_Call) RunAndReturn(run func(string, string) (common.Address, string, error)) *Verifier_Verify_Call {
	_c.Call.Return(run)
	return _c
}

// NewVerifier creates a new instance of Verifier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewVerifier(t interface {
	mock.TestingT
	Cleanup(func())
}) *Verifier {
	mock := &Verifier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
