// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// NonceStore is an autogenerated mock type for the NonceStore type
type NonceStore struct {
	mock.Mock
}

type NonceStore_Expecter struct {
	mock *mock.Mock
}

func (_m *NonceStore) EXPECT() *NonceStore_Expecter {
	return &NonceStore_Expecter{mock: &_m.Mock}
}

// Consume provides a mock function with given fields: nonce
func (_m *NonceStore) Consume(nonce string) bool {
	ret := _m.Called(nonce)

	if len(ret) == 0 {
		panic("no return value specified for Consume")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(nonce)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// NonceStore_Consume_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Consume'
type NonceStore_Consume_Call struct {
	*mock.Call
}

// Consume is a helper method to define mock.On call
//   - nonce string
func (_e *NonceStore_Expecter) Consume(nonce interface{}) *NonceStore_Consume_Call {
	return &NonceStore_Consume_Call{Call: _e.mock.On("Consume", nonce)}
}

func (_c *NonceStore_Consume_Call) Run(run func(nonce string)) *NonceStore_Consume_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *NonceStore_Consume_Call) Return(_a0 bool) *NonceStore_Consume_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *NonceStore_Consume_Call) RunAndReturn(run func(string) bool) *NonceStore_Consume_Call {
	_c.Call.Return(run)
	return _c
}

// Issue provides a mock function with given fields: address
func (_m *NonceStore) Issue(address string) (string, error) {
	ret := _m.Called(address)

	if len(ret) == 0 {
		panic("no return value specified for Issue")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(address)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(address)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(address)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NonceStore_Issue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Issue'
type NonceStore_Issue_Call struct {
	*mock.Call
}

// Issue is a helper method to define mock.On call
//   - address string
func (_e *NonceStore_Expecter) Issue(address interface{}) *NonceStore_Issue_Call {
	return &NonceStore_Issue_Call{Call: _e.mock.On("Issue", address)}
}

func (_c *NonceStore_Issue_Call) Run(run func(address string)) *NonceStore_Issue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *NonceStore_Issue_Call) Return(_a0 string, _a1 error) *NonceStore_Issue_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *NonceStore_Issue_Call) RunAndReturn(run func(string) (string, error)) *NonceStore_Issue_Call {
	_c.Call.Return(run)
	return _c
}

// NewNonceStore creates a new instance of NonceStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNonceStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *NonceStore {
	mock := &NonceStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
