// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	jwt "github.com/chainsafe/canton-middleware/pkg/auth/jwt"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// Issuer is an autogenerated mock type for the Issuer type
type Issuer struct {
	mock.Mock
}

type Issuer_Expecter struct {
	mock *mock.Mock
}

func (_m *Issuer) EXPECT() *Issuer_Expecter {
	return &Issuer_Expecter{mock: &_m.Mock}
}

// Issue provides a mock function with given fields: evmAddress, cantonPartyID
func (_m *Issuer) Issue(evmAddress string, cantonPartyID string) (string, time.Time, error) {
	ret := _m.Called(evmAddress, cantonPartyID)

	if len(ret) == 0 {
		panic("no return value specified for Issue")
	}

	var r0 string
	var r1 time.Time
	var r2 error
	if rf, ok := ret.Get(0).(func(string, string) (string, time.Time, error)); ok {
		return rf(evmAddress, cantonPartyID)
	}
	if rf, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = rf(evmAddress, cantonPartyID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string, string) time.Time); ok {
		r1 = rf(evmAddress, cantonPartyID)
	} else {
		r1 = ret.Get(1).(time.Time)
	}

	if rf, ok := ret.Get(2).(func(string, string) error); ok {
		r2 = rf(evmAddress, cantonPartyID)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Issuer_Issue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Issue'
type Issuer_Issue_Call struct {
	*mock.Call
}

// Issue is a helper method to define mock.On call
//   - evmAddress string
//   - cantonPartyID string
func (_e *Issuer_Expecter) Issue(evmAddress interface{}, cantonPartyID interface{}) *Issuer_Issue_Call {
	return &Issuer_Issue_Call{Call: _e.mock.On("Issue", evmAddress, cantonPartyID)}
}

func (_c *Issuer_Issue_Call) Run(run func(evmAddress string, cantonPartyID string)) *Issuer_Issue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *Issuer_Issue_Call) Return(_a0 string, _a1 time.Time, _a2 error) *Issuer_Issue_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *Issuer_Issue_Call) RunAndReturn(run func(string, string) (string, time.Time, error)) *Issuer_Issue_Call {
	_c.Call.Return(run)
	return _c
}

// JWKS provides a mock function with no fields
func (_m *Issuer) JWKS() jwt.JWKS {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for JWKS")
	}

	var r0 jwt.JWKS
	if rf, ok := ret.Get(0).(func() jwt.JWKS); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(jwt.JWKS)
	}

	return r0
}

// Issuer_JWKS_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'JWKS'
type Issuer_JWKS_Call struct {
	*mock.Call
}

// JWKS is a helper method to define mock.On call
func (_e *Issuer_Expecter) JWKS() *Issuer_JWKS_Call {
	return &Issuer_JWKS_Call{Call: _e.mock.On("JWKS")}
}

func (_c *Issuer_JWKS_Call) Run(run func()) *Issuer_JWKS_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Issuer_JWKS_Call) Return(_a0 jwt.JWKS) *Issuer_JWKS_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Issuer_JWKS_Call) RunAndReturn(run func() jwt.JWKS) *Issuer_JWKS_Call {
	_c.Call.Return(run)
	return _c
}

// NewIssuer creates a new instance of Issuer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIssuer(t interface {
	mock.TestingT
	Cleanup(func())
}) *Issuer {
	mock := &Issuer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
