// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	auth "github.com/chainsafe/canton-middleware/pkg/auth"

	jwt "github.com/chainsafe/canton-middleware/pkg/auth/jwt"

	mock "github.com/stretchr/testify/mock"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

type Service_Expecter struct {
	mock *mock.Mock
}

func (_m *Service) EXPECT() *Service_Expecter {
	return &Service_Expecter{mock: &_m.Mock}
}

// JWKS provides a mock function with no fields
func (_m *Service) JWKS() jwt.JWKS {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for JWKS")
	}

	var r0 jwt.JWKS
	if rf, ok := ret.Get(0).(func() jwt.JWKS); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(jwt.JWKS)
	}

	return r0
}

// Service_JWKS_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'JWKS'
type Service_JWKS_Call struct {
	*mock.Call
}

// JWKS is a helper method to define mock.On call
func (_e *Service_Expecter) JWKS() *Service_JWKS_Call {
	return &Service_JWKS_Call{Call: _e.mock.On("JWKS")}
}

func (_c *Service_JWKS_Call) Run(run func()) *Service_JWKS_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Service_JWKS_Call) Return(_a0 jwt.JWKS) *Service_JWKS_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Service_JWKS_Call) RunAndReturn(run func() jwt.JWKS) *Service_JWKS_Call {
	_c.Call.Return(run)
	return _c
}

// Login provides a mock function with given fields: ctx, message, signature
func (_m *Service) Login(ctx context.Context, message string, signature string) (*auth.LoginResponse, error) {
	ret := _m.Called(ctx, message, signature)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 *auth.LoginResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*auth.LoginResponse, error)); ok {
		return rf(ctx, message, signature)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *auth.LoginResponse); ok {
		r0 = rf(ctx, message, signature)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.LoginResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, message, signature)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Service_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type Service_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - ctx context.Context
//   - message string
//   - signature string
func (_e *Service_Expecter) Login(ctx interface{}, message interface{}, signature interface{}) *Service_Login_Call {
	return &Service_Login_Call{Call: _e.mock.On("Login", ctx, message, signature)}
}

func (_c *Service_Login_Call) Run(run func(ctx context.Context, message string, signature string)) *Service_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *Service_Login_Call) Return(_a0 *auth.LoginResponse, _a1 error) *Service_Login_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Service_Login_Call) RunAndReturn(run func(context.Context, string, string) (*auth.LoginResponse, error)) *Service_Login_Call {
	_c.Call.Return(run)
	return _c
}

// Nonce provides a mock function with given fields: address
func (_m *Service) Nonce(address string) (string, error) {
	ret := _m.Called(address)

	if len(ret) == 0 {
		panic("no return value specified for Nonce")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(address)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(address)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(address)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Service_Nonce_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Nonce'
type Service_Nonce_Call struct {
	*mock.Call
}

// Nonce is a helper method to define mock.On call
//   - address string
func (_e *Service_Expecter) Nonce(address interface{}) *Service_Nonce_Call {
	return &Service_Nonce_Call{Call: _e.mock.On("Nonce", address)}
}

func (_c *Service_Nonce_Call) Run(run func(address string)) *Service_Nonce_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *Service_Nonce_Call) Return(_a0 string, _a1 error) *Service_Nonce_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Service_Nonce_Call) RunAndReturn(run func(string) (string, error)) *Service_Nonce_Call {
	_c.Call.Return(run)
	return _c
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
