// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	common "github.com/ethereum/go-ethereum/common"
	mock "github.com/stretchr/testify/mock"

	token "github.com/chainsafe/canton-middleware/pkg/token"
)

// TokenService is an autogenerated mock type for the TokenService type
type TokenService struct {
	mock.Mock
}

type TokenService_Expecter struct {
	mock *mock.Mock
}

func (_m *TokenService) EXPECT() *TokenService_Expecter {
	return &TokenService_Expecter{mock: &_m.Mock}
}

// ERC20 provides a mock function with given fields: address
func (_m *TokenService) ERC20(address common.Address) (token.ERC20, error) {
	ret := _m.Called(address)

	if len(ret) == 0 {
		panic("no return value specified for ERC20")
	}

	var r0 token.ERC20
	var r1 error
	if rf, ok := ret.Get(0).(func(common.Address) (token.ERC20, error)); ok {
		return rf(address)
	}
	if rf, ok := ret.Get(0).(func(common.Address) token.ERC20); ok {
		r0 = rf(address)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(token.ERC20)
		}
	}

	if rf, ok := ret.Get(1).(func(common.Address) error); ok {
		r1 = rf(address)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TokenService_ERC20_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ERC20'
type TokenService_ERC20_Call struct {
	*mock.Call
}

// ERC20 is a helper method to define mock.On call
//   - address common.Address
func (_e *TokenService_Expecter) ERC20(address interface{}) *TokenService_ERC20_Call {
	return &TokenService_ERC20_Call{Call: _e.mock.On("ERC20", address)}
}

func (_c *TokenService_ERC20_Call) Run(run func(address common.Address)) *TokenService_ERC20_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(common.Address))
	})
	return _c
}

func (_c *TokenService_ERC20_Call) Return(_a0 token.ERC20, _a1 error) *TokenService_ERC20_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TokenService_ERC20_Call) RunAndReturn(run func(common.Address) (token.ERC20, error)) *TokenService_ERC20_Call {
	_c.Call.Return(run)
	return _c
}

// Native provides a mock function with no fields
func (_m *TokenService) Native() token.Native {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Native")
	}

	var r0 token.Native
	if rf, ok := ret.Get(0).(func() token.Native); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(token.Native)
		}
	}

	return r0
}

// TokenService_Native_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Native'
type TokenService_Native_Call struct {
	*mock.Call
}

// Native is a helper method to define mock.On call
func (_e *TokenService_Expecter) Native() *TokenService_Native_Call {
	return &TokenService_Native_Call{Call: _e.mock.On("Native")}
}

func (_c *TokenService_Native_Call) Run(run func()) *TokenService_Native_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *TokenService_Native_Call) Return(_a0 token.Native) *TokenService_Native_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TokenService_Native_Call) RunAndReturn(run func() token.Native) *TokenService_Native_Call {
	_c.Call.Return(run)
	return _c
}

// NewTokenService creates a new instance of TokenService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTokenService(t interface {
	mock.TestingT
	Cleanup(func())
}) *TokenService {
	mock := &TokenService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
