// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	big "math/big"

	common "github.com/ethereum/go-ethereum/common"

	mock "github.com/stretchr/testify/mock"
)

// Native is an autogenerated mock type for the Native type
type Native struct {
	mock.Mock
}

type Native_Expecter struct {
	mock *mock.Mock
}

func (_m *Native) EXPECT() *Native_Expecter {
	return &Native_Expecter{mock: &_m.Mock}
}

// GetBalance provides a mock function with given fields: ctx, address
func (_m *Native) GetBalance(ctx context.Context, address common.Address) (big.Int, error) {
	ret := _m.Called(ctx, address)

	if len(ret) == 0 {
		panic("no return value specified for GetBalance")
	}

	var r0 big.Int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, common.Address) (big.Int, error)); ok {
		return rf(ctx, address)
	}
	if rf, ok := ret.Get(0).(func(context.Context, common.Address) big.Int); ok {
		r0 = rf(ctx, address)
	} else {
		r0 = ret.Get(0).(big.Int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, common.Address) error); ok {
		r1 = rf(ctx, address)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Native_GetBalance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBalance'
type Native_GetBalance_Call struct {
	*mock.Call
}

// GetBalance is a helper method to define mock.On call
//   - ctx context.Context
//   - address common.Address
func (_e *Native_Expecter) GetBalance(ctx interface{}, address interface{}) *Native_GetBalance_Call {
	return &Native_GetBalance_Call{Call: _e.mock.On("GetBalance", ctx, address)}
}

func (_c *Native_GetBalance_Call) Run(run func(ctx context.Context, address common.Address)) *Native_GetBalance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(common.Address))
	})
	return _c
}

func (_c *Native_GetBalance_Call) Return(_a0 big.Int, _a1 error) *Native_GetBalance_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Native_GetBalance_Call) RunAndReturn(run func(context.Context, common.Address) (big.Int, error)) *Native_GetBalance_Call {
	_c.Call.Return(run)
	return _c
}

// Transfer provides a mock function with given fields: ctx, from, to, amount
func (_m *Native) Transfer(ctx context.Context, from common.Address, to common.Address, amount big.Int) error {
	ret := _m.Called(ctx, from, to, amount)

	if len(ret) == 0 {
		panic("no return value specified for Transfer")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, common.Address, common.Address, big.Int) error); ok {
		r0 = rf(ctx, from, to, amount)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Native_Transfer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Transfer'
type Native_Transfer_Call struct {
	*mock.Call
}

// Transfer is a helper method to define mock.On call
//   - ctx context.Context
//   - from common.Address
//   - to common.Address
//   - amount big.Int
func (_e *Native_Expecter) Transfer(ctx interface{}, from interface{}, to interface{}, amount interface{}) *Native_Transfer_Call {
	return &Native_Transfer_Call{Call: _e.mock.On("Transfer", ctx, from, to, amount)}
}

func (_c *Native_Transfer_Call) Run(run func(ctx context.Context, from common.Address, to common.Address, amount big.Int)) *Native_Transfer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(common.Address), args[2].(common.Address), args[3].(big.Int))
	})
	return _c
}

func (_c *Native_Transfer_Call) Return(_a0 error) *Native_Transfer_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Native_Transfer_Call) RunAndReturn(run func(context.Context, common.Address, common.Address, big.Int) error) *Native_Transfer_Call {
	_c.Call.Return(run)
	return _c
}

// NewNative creates a new instance of Native. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNative(t interface {
	mock.TestingT
	Cleanup(func())
}) *Native {
	mock := &Native{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
