// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	ethrpc "github.com/chainsafe/canton-middleware/pkg/ethrpc"
	mock "github.com/stretchr/testify/mock"
)

// Store is an autogenerated mock type for the Store type
type Store struct {
	mock.Mock
}

type Store_Expecter struct {
	mock *mock.Mock
}

func (_m *Store) EXPECT() *Store_Expecter {
	return &Store_Expecter{mock: &_m.Mock}
}

// GetBlockNumberByHash provides a mock function with given fields: ctx, blockHash
func (_m *Store) GetBlockNumberByHash(ctx context.Context, blockHash []byte) (uint64, error) {
	ret := _m.Called(ctx, blockHash)

	if len(ret) == 0 {
		panic("no return value specified for GetBlockNumberByHash")
	}

	var r0 uint64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []byte) (uint64, error)); ok {
		return rf(ctx, blockHash)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []byte) uint64); ok {
		r0 = rf(ctx, blockHash)
	} else {
		r0 = ret.Get(0).(uint64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, []byte) error); ok {
		r1 = rf(ctx, blockHash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store_GetBlockNumberByHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBlockNumberByHash'
type Store_GetBlockNumberByHash_Call struct {
	*mock.Call
}

// GetBlockNumberByHash is a helper method to define mock.On call
//   - ctx context.Context
//   - blockHash []byte
func (_e *Store_Expecter) GetBlockNumberByHash(ctx interface{}, blockHash interface{}) *Store_GetBlockNumberByHash_Call {
	return &Store_GetBlockNumberByHash_Call{Call: _e.mock.On("GetBlockNumberByHash", ctx, blockHash)}
}

func (_c *Store_GetBlockNumberByHash_Call) Run(run func(ctx context.Context, blockHash []byte)) *Store_GetBlockNumberByHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]byte))
	})
	return _c
}

func (_c *Store_GetBlockNumberByHash_Call) Return(_a0 uint64, _a1 error) *Store_GetBlockNumberByHash_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Store_GetBlockNumberByHash_Call) RunAndReturn(run func(context.Context, []byte) (uint64, error)) *Store_GetBlockNumberByHash_Call {
	_c.Call.Return(run)
	return _c
}

// GetEvmLogs provides a mock function with given fields: ctx, address, topic0, fromBlock, toBlock
func (_m *Store) GetEvmLogs(ctx context.Context, address []byte, topic0 []byte, fromBlock uint64, toBlock uint64) ([]*ethrpc.EvmLog, error) {
	ret := _m.Called(ctx, address, topic0, fromBlock, toBlock)

	if len(ret) == 0 {
		panic("no return value specified for GetEvmLogs")
	}

	var r0 []*ethrpc.EvmLog
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []byte, []byte, uint64, uint64) ([]*ethrpc.EvmLog, error)); ok {
		return rf(ctx, address, topic0, fromBlock, toBlock)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []byte, []byte, uint64, uint64) []*ethrpc.EvmLog); ok {
		r0 = rf(ctx, address, topic0, fromBlock, toBlock)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*ethrpc.EvmLog)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []byte, []byte, uint64, uint64) error); ok {
		r1 = rf(ctx, address, topic0, fromBlock, toBlock)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store_GetEvmLogs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEvmLogs'
type Store_GetEvmLogs_Call struct {
	*mock.Call
}

// GetEvmLogs is a helper method to define mock.On call
//   - ctx context.Context
//   - address []byte
//   - topic0 []byte
//   - fromBlock uint64
//   - toBlock uint64
func (_e *Store_Expecter) GetEvmLogs(ctx interface{}, address interface{}, topic0 interface{}, fromBlock interface{}, toBlock interface{}) *Store_GetEvmLogs_Call {
	return &Store_GetEvmLogs_Call{Call: _e.mock.On("GetEvmLogs", ctx, address, topic0, fromBlock, toBlock)}
}

func (_c *Store_GetEvmLogs_Call) Run(run func(ctx context.Context, address []byte, topic0 []byte, fromBlock uint64, toBlock uint64)) *Store_GetEvmLogs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]byte), args[2].([]byte), args[3].(uint64), args[4].(uint64))
	})
	return _c
}

func (_c *Store_GetEvmLogs_Call) Return(_a0 []*ethrpc.EvmLog, _a1 error) *Store_GetEvmLogs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Store_GetEvmLogs_Call) RunAndReturn(run func(context.Context, []byte, []byte, uint64, uint64) ([]*ethrpc.EvmLog, error)) *Store_GetEvmLogs_Call {
	_c.Call.Return(run)
	return _c
}

// GetEvmLogsByTxHash provides a mock function with given fields: ctx, txHash
func (_m *Store) GetEvmLogsByTxHash(ctx context.Context, txHash []byte) ([]*ethrpc.EvmLog, error) {
	ret := _m.Called(ctx, txHash)

	if len(ret) == 0 {
		panic("no return value specified for GetEvmLogsByTxHash")
	}

	var r0 []*ethrpc.EvmLog
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []byte) ([]*ethrpc.EvmLog, error)); ok {
		return rf(ctx, txHash)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []byte) []*ethrpc.EvmLog); ok {
		r0 = rf(ctx, txHash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*ethrpc.EvmLog)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []byte) error); ok {
		r1 = rf(ctx, txHash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store_GetEvmLogsByTxHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEvmLogsByTxHash'
type Store_GetEvmLogsByTxHash_Call struct {
	*mock.Call
}

// GetEvmLogsByTxHash is a helper method to define mock.On call
//   - ctx context.Context
//   - txHash []byte
func (_e *Store_Expecter) GetEvmLogsByTxHash(ctx interface{}, txHash interface{}) *Store_GetEvmLogsByTxHash_Call {
	return &Store_GetEvmLogsByTxHash_Call{Call: _e.mock.On("GetEvmLogsByTxHash", ctx, txHash)}
}

func (_c *Store_GetEvmLogsByTxHash_Call) Run(run func(ctx context.Context, txHash []byte)) *Store_GetEvmLogsByTxHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]byte))
	})
	return _c
}

func (_c *Store_GetEvmLogsByTxHash_Call) Return(_a0 []*ethrpc.EvmLog, _a1 error) *Store_GetEvmLogsByTxHash_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Store_GetEvmLogsByTxHash_Call) RunAndReturn(run func(context.Context, []byte) ([]*ethrpc.EvmLog, error)) *Store_GetEvmLogsByTxHash_Call {
	_c.Call.Return(run)
	return _c
}

// GetEvmTransaction provides a mock function with given fields: ctx, txHash
func (_m *Store) GetEvmTransaction(ctx context.Context, txHash []byte) (*ethrpc.EvmTransaction, error) {
	ret := _m.Called(ctx, txHash)

	if len(ret) == 0 {
		panic("no return value specified for GetEvmTransaction")
	}

	var r0 *ethrpc.EvmTransaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []byte) (*ethrpc.EvmTransaction, error)); ok {
		return rf(ctx, txHash)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []byte) *ethrpc.EvmTransaction); ok {
		r0 = rf(ctx, txHash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ethrpc.EvmTransaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []byte) error); ok {
		r1 = rf(ctx, txHash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store_GetEvmTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEvmTransaction'
type Store_GetEvmTransaction_Call struct {
	*mock.Call
}

// GetEvmTransaction is a helper method to define mock.On call
//   - ctx context.Context
//   - txHash []byte
func (_e *Store_Expecter) GetEvmTransaction(ctx interface{}, txHash interface{}) *Store_GetEvmTransaction_Call {
	return &Store_GetEvmTransaction_Call{Call: _e.mock.On("GetEvmTransaction", ctx, txHash)}
}

func (_c *Store_GetEvmTransaction_Call) Run(run func(ctx context.Context, txHash []byte)) *Store_GetEvmTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]byte))
	})
	return _c
}

func (_c *Store_GetEvmTransaction_Call) Return(_a0 *ethrpc.EvmTransaction, _a1 error) *Store_GetEvmTransaction_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Store_GetEvmTransaction_Call) RunAndReturn(run func(context.Context, []byte) (*ethrpc.EvmTransaction, error)) *Store_GetEvmTransaction_Call {
	_c.Call.Return(run)
	return _c
}

// GetEvmTransactionCount provides a mock function with given fields: ctx, fromAddress
func (_m *Store) GetEvmTransactionCount(ctx context.Context, fromAddress string) (uint64, error) {
	ret := _m.Called(ctx, fromAddress)

	if len(ret) == 0 {
		panic("no return value specified for GetEvmTransactionCount")
	}

	var r0 uint64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (uint64, error)); ok {
		return rf(ctx, fromAddress)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) uint64); ok {
		r0 = rf(ctx, fromAddress)
	} else {
		r0 = ret.Get(0).(uint64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, fromAddress)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store_GetEvmTransactionCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEvmTransactionCount'
type Store_GetEvmTransactionCount_Call struct {
	*mock.Call
}

// GetEvmTransactionCount is a helper method to define mock.On call
//   - ctx context.Context
//   - fromAddress string
func (_e *Store_Expecter) GetEvmTransactionCount(ctx interface{}, fromAddress interface{}) *Store_GetEvmTransactionCount_Call {
	return &Store_GetEvmTransactionCount_Call{Call: _e.mock.On("GetEvmTransactionCount", ctx, fromAddress)}
}

func (_c *Store_GetEvmTransactionCount_Call) Run(run func(ctx context.Context, fromAddress string)) *Store_GetEvmTransactionCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Store_GetEvmTransactionCount_Call) Return(_a0 uint64, _a1 error) *Store_GetEvmTransactionCount_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Store_GetEvmTransactionCount_Call) RunAndReturn(run func(context.Context, string) (uint64, error)) *Store_GetEvmTransactionCount_Call {
	_c.Call.Return(run)
	return _c
}

// GetLatestEvmBlockNumber provides a mock function with given fields: ctx
func (_m *Store) GetLatestEvmBlockNumber(ctx context.Context) (uint64, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetLatestEvmBlockNumber")
	}

	var r0 uint64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (uint64, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) uint64); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(uint64)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store_GetLatestEvmBlockNumber_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLatestEvmBlockNumber'
type Store_GetLatestEvmBlockNumber_Call struct {
	*mock.Call
}

// GetLatestEvmBlockNumber is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Store_Expecter) GetLatestEvmBlockNumber(ctx interface{}) *Store_GetLatestEvmBlockNumber_Call {
	return &Store_GetLatestEvmBlockNumber_Call{Call: _e.mock.On("GetLatestEvmBlockNumber", ctx)}
}

func (_c *Store_GetLatestEvmBlockNumber_Call) Run(run func(ctx context.Context)) *Store_GetLatestEvmBlockNumber_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *Store_GetLatestEvmBlockNumber_Call) Return(_a0 uint64, _a1 error) *Store_GetLatestEvmBlockNumber_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Store_GetLatestEvmBlockNumber_Call) RunAndReturn(run func(context.Context) (uint64, error)) *Store_GetLatestEvmBlockNumber_Call {
	_c.Call.Return(run)
	return _c
}

// NextEvmBlock provides a mock function with given fields: ctx, chainID
func (_m *Store) NextEvmBlock(ctx context.Context, chainID uint64) (uint64, []byte, uint, error) {
	ret := _m.Called(ctx, chainID)

	if len(ret) == 0 {
		panic("no return value specified for NextEvmBlock")
	}

	var r0 uint64
	var r1 []byte
	var r2 uint
	var r3 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64) (uint64, []byte, uint, error)); ok {
		return rf(ctx, chainID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64) uint64); ok {
		r0 = rf(ctx, chainID)
	} else {
		r0 = ret.Get(0).(uint64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64) []byte); ok {
		r1 = rf(ctx, chainID)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]byte)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, uint64) uint); ok {
		r2 = rf(ctx, chainID)
	} else {
		r2 = ret.Get(2).(uint)
	}

	if rf, ok := ret.Get(3).(func(context.Context, uint64) error); ok {
		r3 = rf(ctx, chainID)
	} else {
		r3 = ret.Error(3)
	}

	return r0, r1, r2, r3
}

// Store_NextEvmBlock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NextEvmBlock'
type Store_NextEvmBlock_Call struct {
	*mock.Call
}

// NextEvmBlock is a helper method to define mock.On call
//   - ctx context.Context
//   - chainID uint64
func (_e *Store_Expecter) NextEvmBlock(ctx interface{}, chainID interface{}) *Store_NextEvmBlock_Call {
	return &Store_NextEvmBlock_Call{Call: _e.mock.On("NextEvmBlock", ctx, chainID)}
}

func (_c *Store_NextEvmBlock_Call) Run(run func(ctx context.Context, chainID uint64)) *Store_NextEvmBlock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64))
	})
	return _c
}

func (_c *Store_NextEvmBlock_Call) Return(_a0 uint64, _a1 []byte, _a2 uint, _a3 error) *Store_NextEvmBlock_Call {
	_c.Call.Return(_a0, _a1, _a2, _a3)
	return _c
}

func (_c *Store_NextEvmBlock_Call) RunAndReturn(run func(context.Context, uint64) (uint64, []byte, uint, error)) *Store_NextEvmBlock_Call {
	_c.Call.Return(run)
	return _c
}

// SaveEvmLog provides a mock function with given fields: ctx, log
func (_m *Store) SaveEvmLog(ctx context.Context, log *ethrpc.EvmLog) error {
	ret := _m.Called(ctx, log)

	if len(ret) == 0 {
		panic("no return value specified for SaveEvmLog")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *ethrpc.EvmLog) error); ok {
		r0 = rf(ctx, log)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Store_SaveEvmLog_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveEvmLog'
type Store_SaveEvmLog_Call struct {
	*mock.Call
}

// SaveEvmLog is a helper method to define mock.On call
//   - ctx context.Context
//   - log *ethrpc.EvmLog
func (_e *Store_Expecter) SaveEvmLog(ctx interface{}, log interface{}) *Store_SaveEvmLog_Call {
	return &Store_SaveEvmLog_Call{Call: _e.mock.On("SaveEvmLog", ctx, log)}
}

func (_c *Store_SaveEvmLog_Call) Run(run func(ctx context.Context, log *ethrpc.EvmLog)) *Store_SaveEvmLog_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*ethrpc.EvmLog))
	})
	return _c
}

func (_c *Store_SaveEvmLog_Call) Return(_a0 error) *Store_SaveEvmLog_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Store_SaveEvmLog_Call) RunAndReturn(run func(context.Context, *ethrpc.EvmLog) error) *Store_SaveEvmLog_Call {
	_c.Call.Return(run)
	return _c
}

// SaveEvmTransaction provides a mock function with given fields: ctx, tx
func (_m *Store) SaveEvmTransaction(ctx context.Context, tx *ethrpc.EvmTransaction) error {
	ret := _m.Called(ctx, tx)

	if len(ret) == 0 {
		panic("no return value specified for SaveEvmTransaction")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *ethrpc.EvmTransaction) error); ok {
		r0 = rf(ctx, tx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Store_SaveEvmTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveEvmTransaction'
type Store_SaveEvmTransaction_Call struct {
	*mock.Call
}

// SaveEvmTransaction is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *ethrpc.EvmTransaction
func (_e *Store_Expecter) SaveEvmTransaction(ctx interface{}, tx interface{}) *Store_SaveEvmTransaction_Call {
	return &Store_SaveEvmTransaction_Call{Call: _e.mock.On("SaveEvmTransaction", ctx, tx)}
}

func (_c *Store_SaveEvmTransaction_Call) Run(run func(ctx context.Context, tx *ethrpc.EvmTransaction)) *Store_SaveEvmTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*ethrpc.EvmTransaction))
	})
	return _c
}

func (_c *Store_SaveEvmTransaction_Call) Return(_a0 error) *Store_SaveEvmTransaction_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Store_SaveEvmTransaction_Call) RunAndReturn(run func(context.Context, *ethrpc.EvmTransaction) error) *Store_SaveEvmTransaction_Call {
	_c.Call.Return(run)
	return _c
}

// NewStore creates a new instance of Store. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *Store {
	mock := &Store{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
