// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	apidb "github.com/chainsafe/canton-middleware/pkg/apidb"
	mock "github.com/stretchr/testify/mock"
)

// Store is an autogenerated mock type for the Store type
type Store struct {
	mock.Mock
}

type Store_Expecter struct {
	mock *mock.Mock
}

func (_m *Store) EXPECT() *Store_Expecter {
	return &Store_Expecter{mock: &_m.Mock}
}

// GetBlockNumberByHash provides a mock function with given fields: blockHash
func (_m *Store) GetBlockNumberByHash(blockHash []byte) (uint64, error) {
	ret := _m.Called(blockHash)

	if len(ret) == 0 {
		panic("no return value specified for GetBlockNumberByHash")
	}

	var r0 uint64
	var r1 error
	if rf, ok := ret.Get(0).(func([]byte) (uint64, error)); ok {
		return rf(blockHash)
	}
	if rf, ok := ret.Get(0).(func([]byte) uint64); ok {
		r0 = rf(blockHash)
	} else {
		r0 = ret.Get(0).(uint64)
	}

	if rf, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = rf(blockHash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store_GetBlockNumberByHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBlockNumberByHash'
type Store_GetBlockNumberByHash_Call struct {
	*mock.Call
}

// GetBlockNumberByHash is a helper method to define mock.On call
//   - blockHash []byte
func (_e *Store_Expecter) GetBlockNumberByHash(blockHash interface{}) *Store_GetBlockNumberByHash_Call {
	return &Store_GetBlockNumberByHash_Call{Call: _e.mock.On("GetBlockNumberByHash", blockHash)}
}

func (_c *Store_GetBlockNumberByHash_Call) Run(run func(blockHash []byte)) *Store_GetBlockNumberByHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]byte))
	})
	return _c
}

func (_c *Store_GetBlockNumberByHash_Call) Return(_a0 uint64, _a1 error) *Store_GetBlockNumberByHash_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Store_GetBlockNumberByHash_Call) RunAndReturn(run func([]byte) (uint64, error)) *Store_GetBlockNumberByHash_Call {
	_c.Call.Return(run)
	return _c
}

// GetEvmLogs provides a mock function with given fields: address, topic0, fromBlock, toBlock
func (_m *Store) GetEvmLogs(address []byte, topic0 []byte, fromBlock int64, toBlock int64) ([]*apidb.EvmLog, error) {
	ret := _m.Called(address, topic0, fromBlock, toBlock)

	if len(ret) == 0 {
		panic("no return value specified for GetEvmLogs")
	}

	var r0 []*apidb.EvmLog
	var r1 error
	if rf, ok := ret.Get(0).(func([]byte, []byte, int64, int64) ([]*apidb.EvmLog, error)); ok {
		return rf(address, topic0, fromBlock, toBlock)
	}
	if rf, ok := ret.Get(0).(func([]byte, []byte, int64, int64) []*apidb.EvmLog); ok {
		r0 = rf(address, topic0, fromBlock, toBlock)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*apidb.EvmLog)
		}
	}

	if rf, ok := ret.Get(1).(func([]byte, []byte, int64, int64) error); ok {
		r1 = rf(address, topic0, fromBlock, toBlock)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store_GetEvmLogs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEvmLogs'
type Store_GetEvmLogs_Call struct {
	*mock.Call
}

// GetEvmLogs is a helper method to define mock.On call
//   - address []byte
//   - topic0 []byte
//   - fromBlock int64
//   - toBlock int64
func (_e *Store_Expecter) GetEvmLogs(address interface{}, topic0 interface{}, fromBlock interface{}, toBlock interface{}) *Store_GetEvmLogs_Call {
	return &Store_GetEvmLogs_Call{Call: _e.mock.On("GetEvmLogs", address, topic0, fromBlock, toBlock)}
}

func (_c *Store_GetEvmLogs_Call) Run(run func(address []byte, topic0 []byte, fromBlock int64, toBlock int64)) *Store_GetEvmLogs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]byte), args[1].([]byte), args[2].(int64), args[3].(int64))
	})
	return _c
}

func (_c *Store_GetEvmLogs_Call) Return(_a0 []*apidb.EvmLog, _a1 error) *Store_GetEvmLogs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Store_GetEvmLogs_Call) RunAndReturn(run func([]byte, []byte, int64, int64) ([]*apidb.EvmLog, error)) *Store_GetEvmLogs_Call {
	_c.Call.Return(run)
	return _c
}

// GetEvmLogsByTxHash provides a mock function with given fields: txHash
func (_m *Store) GetEvmLogsByTxHash(txHash []byte) ([]*apidb.EvmLog, error) {
	ret := _m.Called(txHash)

	if len(ret) == 0 {
		panic("no return value specified for GetEvmLogsByTxHash")
	}

	var r0 []*apidb.EvmLog
	var r1 error
	if rf, ok := ret.Get(0).(func([]byte) ([]*apidb.EvmLog, error)); ok {
		return rf(txHash)
	}
	if rf, ok := ret.Get(0).(func([]byte) []*apidb.EvmLog); ok {
		r0 = rf(txHash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*apidb.EvmLog)
		}
	}

	if rf, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = rf(txHash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store_GetEvmLogsByTxHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEvmLogsByTxHash'
type Store_GetEvmLogsByTxHash_Call struct {
	*mock.Call
}

// GetEvmLogsByTxHash is a helper method to define mock.On call
//   - txHash []byte
func (_e *Store_Expecter) GetEvmLogsByTxHash(txHash interface{}) *Store_GetEvmLogsByTxHash_Call {
	return &Store_GetEvmLogsByTxHash_Call{Call: _e.mock.On("GetEvmLogsByTxHash", txHash)}
}

func (_c *Store_GetEvmLogsByTxHash_Call) Run(run func(txHash []byte)) *Store_GetEvmLogsByTxHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]byte))
	})
	return _c
}

func (_c *Store_GetEvmLogsByTxHash_Call) Return(_a0 []*apidb.EvmLog, _a1 error) *Store_GetEvmLogsByTxHash_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Store_GetEvmLogsByTxHash_Call) RunAndReturn(run func([]byte) ([]*apidb.EvmLog, error)) *Store_GetEvmLogsByTxHash_Call {
	_c.Call.Return(run)
	return _c
}

// GetEvmTransaction provides a mock function with given fields: txHash
func (_m *Store) GetEvmTransaction(txHash []byte) (*apidb.EvmTransaction, error) {
	ret := _m.Called(txHash)

	if len(ret) == 0 {
		panic("no return value specified for GetEvmTransaction")
	}

	var r0 *apidb.EvmTransaction
	var r1 error
	if rf, ok := ret.Get(0).(func([]byte) (*apidb.EvmTransaction, error)); ok {
		return rf(txHash)
	}
	if rf, ok := ret.Get(0).(func([]byte) *apidb.EvmTransaction); ok {
		r0 = rf(txHash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apidb.EvmTransaction)
		}
	}

	if rf, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = rf(txHash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store_GetEvmTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEvmTransaction'
type Store_GetEvmTransaction_Call struct {
	*mock.Call
}

// GetEvmTransaction is a helper method to define mock.On call
//   - txHash []byte
func (_e *Store_Expecter) GetEvmTransaction(txHash interface{}) *Store_GetEvmTransaction_Call {
	return &Store_GetEvmTransaction_Call{Call: _e.mock.On("GetEvmTransaction", txHash)}
}

func (_c *Store_GetEvmTransaction_Call) Run(run func(txHash []byte)) *Store_GetEvmTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]byte))
	})
	return _c
}

func (_c *Store_GetEvmTransaction_Call) Return(_a0 *apidb.EvmTransaction, _a1 error) *Store_GetEvmTransaction_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Store_GetEvmTransaction_Call) RunAndReturn(run func([]byte) (*apidb.EvmTransaction, error)) *Store_GetEvmTransaction_Call {
	_c.Call.Return(run)
	return _c
}

// GetEvmTransactionCount provides a mock function with given fields: fromAddress
func (_m *Store) GetEvmTransactionCount(fromAddress string) (uint64, error) {
	ret := _m.Called(fromAddress)

	if len(ret) == 0 {
		panic("no return value specified for GetEvmTransactionCount")
	}

	var r0 uint64
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (uint64, error)); ok {
		return rf(fromAddress)
	}
	if rf, ok := ret.Get(0).(func(string) uint64); ok {
		r0 = rf(fromAddress)
	} else {
		r0 = ret.Get(0).(uint64)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(fromAddress)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store_GetEvmTransactionCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEvmTransactionCount'
type Store_GetEvmTransactionCount_Call struct {
	*mock.Call
}

// GetEvmTransactionCount is a helper method to define mock.On call
//   - fromAddress string
func (_e *Store_Expecter) GetEvmTransactionCount(fromAddress interface{}) *Store_GetEvmTransactionCount_Call {
	return &Store_GetEvmTransactionCount_Call{Call: _e.mock.On("GetEvmTransactionCount", fromAddress)}
}

func (_c *Store_GetEvmTransactionCount_Call) Run(run func(fromAddress string)) *Store_GetEvmTransactionCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *Store_GetEvmTransactionCount_Call) Return(_a0 uint64, _a1 error) *Store_GetEvmTransactionCount_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Store_GetEvmTransactionCount_Call) RunAndReturn(run func(string) (uint64, error)) *Store_GetEvmTransactionCount_Call {
	_c.Call.Return(run)
	return _c
}

// GetLatestEvmBlockNumber provides a mock function with no fields
func (_m *Store) GetLatestEvmBlockNumber() (uint64, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetLatestEvmBlockNumber")
	}

	var r0 uint64
	var r1 error
	if rf, ok := ret.Get(0).(func() (uint64, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() uint64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(uint64)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store_GetLatestEvmBlockNumber_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLatestEvmBlockNumber'
type Store_GetLatestEvmBlockNumber_Call struct {
	*mock.Call
}

// GetLatestEvmBlockNumber is a helper method to define mock.On call
func (_e *Store_Expecter) GetLatestEvmBlockNumber() *Store_GetLatestEvmBlockNumber_Call {
	return &Store_GetLatestEvmBlockNumber_Call{Call: _e.mock.On("GetLatestEvmBlockNumber")}
}

func (_c *Store_GetLatestEvmBlockNumber_Call) Run(run func()) *Store_GetLatestEvmBlockNumber_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Store_GetLatestEvmBlockNumber_Call) Return(_a0 uint64, _a1 error) *Store_GetLatestEvmBlockNumber_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Store_GetLatestEvmBlockNumber_Call) RunAndReturn(run func() (uint64, error)) *Store_GetLatestEvmBlockNumber_Call {
	_c.Call.Return(run)
	return _c
}

// NextEvmBlock provides a mock function with given fields: chainID
func (_m *Store) NextEvmBlock(chainID uint64) (uint64, []byte, int, error) {
	ret := _m.Called(chainID)

	if len(ret) == 0 {
		panic("no return value specified for NextEvmBlock")
	}

	var r0 uint64
	var r1 []byte
	var r2 int
	var r3 error
	if rf, ok := ret.Get(0).(func(uint64) (uint64, []byte, int, error)); ok {
		return rf(chainID)
	}
	if rf, ok := ret.Get(0).(func(uint64) uint64); ok {
		r0 = rf(chainID)
	} else {
		r0 = ret.Get(0).(uint64)
	}

	if rf, ok := ret.Get(1).(func(uint64) []byte); ok {
		r1 = rf(chainID)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]byte)
		}
	}

	if rf, ok := ret.Get(2).(func(uint64) int); ok {
		r2 = rf(chainID)
	} else {
		r2 = ret.Get(2).(int)
	}

	if rf, ok := ret.Get(3).(func(uint64) error); ok {
		r3 = rf(chainID)
	} else {
		r3 = ret.Error(3)
	}

	return r0, r1, r2, r3
}

// Store_NextEvmBlock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NextEvmBlock'
type Store_NextEvmBlock_Call struct {
	*mock.Call
}

// NextEvmBlock is a helper method to define mock.On call
//   - chainID uint64
func (_e *Store_Expecter) NextEvmBlock(chainID interface{}) *Store_NextEvmBlock_Call {
	return &Store_NextEvmBlock_Call{Call: _e.mock.On("NextEvmBlock", chainID)}
}

func (_c *Store_NextEvmBlock_Call) Run(run func(chainID uint64)) *Store_NextEvmBlock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint64))
	})
	return _c
}

func (_c *Store_NextEvmBlock_Call) Return(_a0 uint64, _a1 []byte, _a2 int, _a3 error) *Store_NextEvmBlock_Call {
	_c.Call.Return(_a0, _a1, _a2, _a3)
	return _c
}

func (_c *Store_NextEvmBlock_Call) RunAndReturn(run func(uint64) (uint64, []byte, int, error)) *Store_NextEvmBlock_Call {
	_c.Call.Return(run)
	return _c
}

// SaveEvmLog provides a mock function with given fields: log
func (_m *Store) SaveEvmLog(log *apidb.EvmLog) error {
	ret := _m.Called(log)

	if len(ret) == 0 {
		panic("no return value specified for SaveEvmLog")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*apidb.EvmLog) error); ok {
		r0 = rf(log)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Store_SaveEvmLog_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveEvmLog'
type Store_SaveEvmLog_Call struct {
	*mock.Call
}

// SaveEvmLog is a helper method to define mock.On call
//   - log *apidb.EvmLog
func (_e *Store_Expecter) SaveEvmLog(log interface{}) *Store_SaveEvmLog_Call {
	return &Store_SaveEvmLog_Call{Call: _e.mock.On("SaveEvmLog", log)}
}

func (_c *Store_SaveEvmLog_Call) Run(run func(log *apidb.EvmLog)) *Store_SaveEvmLog_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*apidb.EvmLog))
	})
	return _c
}

func (_c *Store_SaveEvmLog_Call) Return(_a0 error) *Store_SaveEvmLog_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Store_SaveEvmLog_Call) RunAndReturn(run func(*apidb.EvmLog) error) *Store_SaveEvmLog_Call {
	_c.Call.Return(run)
	return _c
}

// SaveEvmTransaction provides a mock function with given fields: tx
func (_m *Store) SaveEvmTransaction(tx *apidb.EvmTransaction) error {
	ret := _m.Called(tx)

	if len(ret) == 0 {
		panic("no return value specified for SaveEvmTransaction")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*apidb.EvmTransaction) error); ok {
		r0 = rf(tx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Store_SaveEvmTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveEvmTransaction'
type Store_SaveEvmTransaction_Call struct {
	*mock.Call
}

// SaveEvmTransaction is a helper method to define mock.On call
//   - tx *apidb.EvmTransaction
func (_e *Store_Expecter) SaveEvmTransaction(tx interface{}) *Store_SaveEvmTransaction_Call {
	return &Store_SaveEvmTransaction_Call{Call: _e.mock.On("SaveEvmTransaction", tx)}
}

func (_c *Store_SaveEvmTransaction_Call) Run(run func(tx *apidb.EvmTransaction)) *Store_SaveEvmTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*apidb.EvmTransaction))
	})
	return _c
}

func (_c *Store_SaveEvmTransaction_Call) Return(_a0 error) *Store_SaveEvmTransaction_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Store_SaveEvmTransaction_Call) RunAndReturn(run func(*apidb.EvmTransaction) error) *Store_SaveEvmTransaction_Call {
	_c.Call.Return(run)
	return _c
}

// NewStore creates a new instance of Store. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *Store {
	mock := &Store{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
