// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	ethrpc "github.com/chainsafe/canton-middleware/pkg/ethrpc"
	mock "github.com/stretchr/testify/mock"
)

// PendingBlock is an autogenerated mock type for the PendingBlock type
type PendingBlock struct {
	mock.Mock
}

type PendingBlock_Expecter struct {
	mock *mock.Mock
}

func (_m *PendingBlock) EXPECT() *PendingBlock_Expecter {
	return &PendingBlock_Expecter{mock: &_m.Mock}
}

// Abort provides a mock function with given fields: ctx
func (_m *PendingBlock) Abort(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Abort")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PendingBlock_Abort_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Abort'
type PendingBlock_Abort_Call struct {
	*mock.Call
}

// Abort is a helper method to define mock.On call
//   - ctx context.Context
func (_e *PendingBlock_Expecter) Abort(ctx interface{}) *PendingBlock_Abort_Call {
	return &PendingBlock_Abort_Call{Call: _e.mock.On("Abort", ctx)}
}

func (_c *PendingBlock_Abort_Call) Run(run func(ctx context.Context)) *PendingBlock_Abort_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *PendingBlock_Abort_Call) Return(_a0 error) *PendingBlock_Abort_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PendingBlock_Abort_Call) RunAndReturn(run func(context.Context) error) *PendingBlock_Abort_Call {
	_c.Call.Return(run)
	return _c
}

// BlockHash provides a mock function with no fields
func (_m *PendingBlock) BlockHash() []byte {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for BlockHash")
	}

	var r0 []byte
	if rf, ok := ret.Get(0).(func() []byte); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	return r0
}

// PendingBlock_BlockHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BlockHash'
type PendingBlock_BlockHash_Call struct {
	*mock.Call
}

// BlockHash is a helper method to define mock.On call
func (_e *PendingBlock_Expecter) BlockHash() *PendingBlock_BlockHash_Call {
	return &PendingBlock_BlockHash_Call{Call: _e.mock.On("BlockHash")}
}

func (_c *PendingBlock_BlockHash_Call) Run(run func()) *PendingBlock_BlockHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *PendingBlock_BlockHash_Call) Return(_a0 []byte) *PendingBlock_BlockHash_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PendingBlock_BlockHash_Call) RunAndReturn(run func() []byte) *PendingBlock_BlockHash_Call {
	_c.Call.Return(run)
	return _c
}

// BlockNumber provides a mock function with no fields
func (_m *PendingBlock) BlockNumber() uint64 {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for BlockNumber")
	}

	var r0 uint64
	if rf, ok := ret.Get(0).(func() uint64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(uint64)
	}

	return r0
}

// PendingBlock_BlockNumber_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BlockNumber'
type PendingBlock_BlockNumber_Call struct {
	*mock.Call
}

// BlockNumber is a helper method to define mock.On call
func (_e *PendingBlock_Expecter) BlockNumber() *PendingBlock_BlockNumber_Call {
	return &PendingBlock_BlockNumber_Call{Call: _e.mock.On("BlockNumber")}
}

func (_c *PendingBlock_BlockNumber_Call) Run(run func()) *PendingBlock_BlockNumber_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *PendingBlock_BlockNumber_Call) Return(_a0 uint64) *PendingBlock_BlockNumber_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PendingBlock_BlockNumber_Call) RunAndReturn(run func() uint64) *PendingBlock_BlockNumber_Call {
	_c.Call.Return(run)
	return _c
}

// Finalize provides a mock function with given fields: ctx
func (_m *PendingBlock) Finalize(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Finalize")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PendingBlock_Finalize_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Finalize'
type PendingBlock_Finalize_Call struct {
	*mock.Call
}

// Finalize is a helper method to define mock.On call
//   - ctx context.Context
func (_e *PendingBlock_Expecter) Finalize(ctx interface{}) *PendingBlock_Finalize_Call {
	return &PendingBlock_Finalize_Call{Call: _e.mock.On("Finalize", ctx)}
}

func (_c *PendingBlock_Finalize_Call) Run(run func(ctx context.Context)) *PendingBlock_Finalize_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *PendingBlock_Finalize_Call) Return(_a0 error) *PendingBlock_Finalize_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PendingBlock_Finalize_Call) RunAndReturn(run func(context.Context) error) *PendingBlock_Finalize_Call {
	_c.Call.Return(run)
	return _c
}

// SaveEvmLog provides a mock function with given fields: ctx, log
func (_m *PendingBlock) SaveEvmLog(ctx context.Context, log *ethrpc.EvmLog) error {
	ret := _m.Called(ctx, log)

	if len(ret) == 0 {
		panic("no return value specified for SaveEvmLog")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *ethrpc.EvmLog) error); ok {
		r0 = rf(ctx, log)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PendingBlock_SaveEvmLog_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveEvmLog'
type PendingBlock_SaveEvmLog_Call struct {
	*mock.Call
}

// SaveEvmLog is a helper method to define mock.On call
//   - ctx context.Context
//   - log *ethrpc.EvmLog
func (_e *PendingBlock_Expecter) SaveEvmLog(ctx interface{}, log interface{}) *PendingBlock_SaveEvmLog_Call {
	return &PendingBlock_SaveEvmLog_Call{Call: _e.mock.On("SaveEvmLog", ctx, log)}
}

func (_c *PendingBlock_SaveEvmLog_Call) Run(run func(ctx context.Context, log *ethrpc.EvmLog)) *PendingBlock_SaveEvmLog_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*ethrpc.EvmLog))
	})
	return _c
}

func (_c *PendingBlock_SaveEvmLog_Call) Return(_a0 error) *PendingBlock_SaveEvmLog_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PendingBlock_SaveEvmLog_Call) RunAndReturn(run func(context.Context, *ethrpc.EvmLog) error) *PendingBlock_SaveEvmLog_Call {
	_c.Call.Return(run)
	return _c
}

// SaveEvmTransaction provides a mock function with given fields: ctx, tx
func (_m *PendingBlock) SaveEvmTransaction(ctx context.Context, tx *ethrpc.EvmTransaction) error {
	ret := _m.Called(ctx, tx)

	if len(ret) == 0 {
		panic("no return value specified for SaveEvmTransaction")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *ethrpc.EvmTransaction) error); ok {
		r0 = rf(ctx, tx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PendingBlock_SaveEvmTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveEvmTransaction'
type PendingBlock_SaveEvmTransaction_Call struct {
	*mock.Call
}

// SaveEvmTransaction is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *ethrpc.EvmTransaction
func (_e *PendingBlock_Expecter) SaveEvmTransaction(ctx interface{}, tx interface{}) *PendingBlock_SaveEvmTransaction_Call {
	return &PendingBlock_SaveEvmTransaction_Call{Call: _e.mock.On("SaveEvmTransaction", ctx, tx)}
}

func (_c *PendingBlock_SaveEvmTransaction_Call) Run(run func(ctx context.Context, tx *ethrpc.EvmTransaction)) *PendingBlock_SaveEvmTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*ethrpc.EvmTransaction))
	})
	return _c
}

func (_c *PendingBlock_SaveEvmTransaction_Call) Return(_a0 error) *PendingBlock_SaveEvmTransaction_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PendingBlock_SaveEvmTransaction_Call) RunAndReturn(run func(context.Context, *ethrpc.EvmTransaction) error) *PendingBlock_SaveEvmTransaction_Call {
	_c.Call.Return(run)
	return _c
}

// NewPendingBlock creates a new instance of PendingBlock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPendingBlock(t interface {
	mock.TestingT
	Cleanup(func())
}) *PendingBlock {
	mock := &PendingBlock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
