// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	indexer "github.com/chainsafe/canton-middleware/pkg/indexer"
	mock "github.com/stretchr/testify/mock"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

type Service_Expecter struct {
	mock *mock.Mock
}

func (_m *Service) EXPECT() *Service_Expecter {
	return &Service_Expecter{mock: &_m.Mock}
}

// GetBalance provides a mock function with given fields: ctx, partyID, admin, id
func (_m *Service) GetBalance(ctx context.Context, partyID string, admin string, id string) (*indexer.Balance, error) {
	ret := _m.Called(ctx, partyID, admin, id)

	if len(ret) == 0 {
		panic("no return value specified for GetBalance")
	}

	var r0 *indexer.Balance
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (*indexer.Balance, error)); ok {
		return rf(ctx, partyID, admin, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) *indexer.Balance); ok {
		r0 = rf(ctx, partyID, admin, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*indexer.Balance)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, partyID, admin, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Service_GetBalance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBalance'
type Service_GetBalance_Call struct {
	*mock.Call
}

// GetBalance is a helper method to define mock.On call
//   - ctx context.Context
//   - partyID string
//   - admin string
//   - id string
func (_e *Service_Expecter) GetBalance(ctx interface{}, partyID interface{}, admin interface{}, id interface{}) *Service_GetBalance_Call {
	return &Service_GetBalance_Call{Call: _e.mock.On("GetBalance", ctx, partyID, admin, id)}
}

func (_c *Service_GetBalance_Call) Run(run func(ctx context.Context, partyID string, admin string, id string)) *Service_GetBalance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *Service_GetBalance_Call) Return(_a0 *indexer.Balance, _a1 error) *Service_GetBalance_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Service_GetBalance_Call) RunAndReturn(run func(context.Context, string, string, string) (*indexer.Balance, error)) *Service_GetBalance_Call {
	_c.Call.Return(run)
	return _c
}

// GetEvent provides a mock function with given fields: ctx, contractID
func (_m *Service) GetEvent(ctx context.Context, contractID string) (*indexer.ParsedEvent, error) {
	ret := _m.Called(ctx, contractID)

	if len(ret) == 0 {
		panic("no return value specified for GetEvent")
	}

	var r0 *indexer.ParsedEvent
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*indexer.ParsedEvent, error)); ok {
		return rf(ctx, contractID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *indexer.ParsedEvent); ok {
		r0 = rf(ctx, contractID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*indexer.ParsedEvent)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, contractID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Service_GetEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEvent'
type Service_GetEvent_Call struct {
	*mock.Call
}

// GetEvent is a helper method to define mock.On call
//   - ctx context.Context
//   - contractID string
func (_e *Service_Expecter) GetEvent(ctx interface{}, contractID interface{}) *Service_GetEvent_Call {
	return &Service_GetEvent_Call{Call: _e.mock.On("GetEvent", ctx, contractID)}
}

func (_c *Service_GetEvent_Call) Run(run func(ctx context.Context, contractID string)) *Service_GetEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Service_GetEvent_Call) Return(_a0 *indexer.ParsedEvent, _a1 error) *Service_GetEvent_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Service_GetEvent_Call) RunAndReturn(run func(context.Context, string) (*indexer.ParsedEvent, error)) *Service_GetEvent_Call {
	_c.Call.Return(run)
	return _c
}

// GetToken provides a mock function with given fields: ctx, admin, id
func (_m *Service) GetToken(ctx context.Context, admin string, id string) (*indexer.Token, error) {
	ret := _m.Called(ctx, admin, id)

	if len(ret) == 0 {
		panic("no return value specified for GetToken")
	}

	var r0 *indexer.Token
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*indexer.Token, error)); ok {
		return rf(ctx, admin, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *indexer.Token); ok {
		r0 = rf(ctx, admin, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*indexer.Token)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, admin, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Service_GetToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetToken'
type Service_GetToken_Call struct {
	*mock.Call
}

// GetToken is a helper method to define mock.On call
//   - ctx context.Context
//   - admin string
//   - id string
func (_e *Service_Expecter) GetToken(ctx interface{}, admin interface{}, id interface{}) *Service_GetToken_Call {
	return &Service_GetToken_Call{Call: _e.mock.On("GetToken", ctx, admin, id)}
}

func (_c *Service_GetToken_Call) Run(run func(ctx context.Context, admin string, id string)) *Service_GetToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *Service_GetToken_Call) Return(_a0 *indexer.Token, _a1 error) *Service_GetToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Service_GetToken_Call) RunAndReturn(run func(context.Context, string, string) (*indexer.Token, error)) *Service_GetToken_Call {
	_c.Call.Return(run)
	return _c
}

// ListBalancesForParty provides a mock function with given fields: ctx, partyID, p
func (_m *Service) ListBalancesForParty(ctx context.Context, partyID string, p indexer.Pagination) (*indexer.Page[*indexer.Balance], error) {
	ret := _m.Called(ctx, partyID, p)

	if len(ret) == 0 {
		panic("no return value specified for ListBalancesForParty")
	}

	var r0 *indexer.Page[*indexer.Balance]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, indexer.Pagination) (*indexer.Page[*indexer.Balance], error)); ok {
		return rf(ctx, partyID, p)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, indexer.Pagination) *indexer.Page[*indexer.Balance]); ok {
		r0 = rf(ctx, partyID, p)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*indexer.Page[*indexer.Balance])
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, indexer.Pagination) error); ok {
		r1 = rf(ctx, partyID, p)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Service_ListBalancesForParty_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListBalancesForParty'
type Service_ListBalancesForParty_Call struct {
	*mock.Call
}

// ListBalancesForParty is a helper method to define mock.On call
//   - ctx context.Context
//   - partyID string
//   - p indexer.Pagination
func (_e *Service_Expecter) ListBalancesForParty(ctx interface{}, partyID interface{}, p interface{}) *Service_ListBalancesForParty_Call {
	return &Service_ListBalancesForParty_Call{Call: _e.mock.On("ListBalancesForParty", ctx, partyID, p)}
}

func (_c *Service_ListBalancesForParty_Call) Run(run func(ctx context.Context, partyID string, p indexer.Pagination)) *Service_ListBalancesForParty_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(indexer.Pagination))
	})
	return _c
}

func (_c *Service_ListBalancesForParty_Call) Return(_a0 *indexer.Page[*indexer.Balance], _a1 error) *Service_ListBalancesForParty_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Service_ListBalancesForParty_Call) RunAndReturn(run func(context.Context, string, indexer.Pagination) (*indexer.Page[*indexer.Balance], error)) *Service_ListBalancesForParty_Call {
	_c.Call.Return(run)
	return _c
}

// ListBalancesForToken provides a mock function with given fields: ctx, admin, id, p
func (_m *Service) ListBalancesForToken(ctx context.Context, admin string, id string, p indexer.Pagination) (*indexer.Page[*indexer.Balance], error) {
	ret := _m.Called(ctx, admin, id, p)

	if len(ret) == 0 {
		panic("no return value specified for ListBalancesForToken")
	}

	var r0 *indexer.Page[*indexer.Balance]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, indexer.Pagination) (*indexer.Page[*indexer.Balance], error)); ok {
		return rf(ctx, admin, id, p)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, indexer.Pagination) *indexer.Page[*indexer.Balance]); ok {
		r0 = rf(ctx, admin, id, p)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*indexer.Page[*indexer.Balance])
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, indexer.Pagination) error); ok {
		r1 = rf(ctx, admin, id, p)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Service_ListBalancesForToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListBalancesForToken'
type Service_ListBalancesForToken_Call struct {
	*mock.Call
}

// ListBalancesForToken is a helper method to define mock.On call
//   - ctx context.Context
//   - admin string
//   - id string
//   - p indexer.Pagination
func (_e *Service_Expecter) ListBalancesForToken(ctx interface{}, admin interface{}, id interface{}, p interface{}) *Service_ListBalancesForToken_Call {
	return &Service_ListBalancesForToken_Call{Call: _e.mock.On("ListBalancesForToken", ctx, admin, id, p)}
}

func (_c *Service_ListBalancesForToken_Call) Run(run func(ctx context.Context, admin string, id string, p indexer.Pagination)) *Service_ListBalancesForToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(indexer.Pagination))
	})
	return _c
}

func (_c *Service_ListBalancesForToken_Call) Return(_a0 *indexer.Page[*indexer.Balance], _a1 error) *Service_ListBalancesForToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Service_ListBalancesForToken_Call) RunAndReturn(run func(context.Context, string, string, indexer.Pagination) (*indexer.Page[*indexer.Balance], error)) *Service_ListBalancesForToken_Call {
	_c.Call.Return(run)
	return _c
}

// ListPartyEvents provides a mock function with given fields: ctx, partyID, f, p
func (_m *Service) ListPartyEvents(ctx context.Context, partyID string, f indexer.EventFilter, p indexer.Pagination) (*indexer.Page[*indexer.ParsedEvent], error) {
	ret := _m.Called(ctx, partyID, f, p)

	if len(ret) == 0 {
		panic("no return value specified for ListPartyEvents")
	}

	var r0 *indexer.Page[*indexer.ParsedEvent]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, indexer.EventFilter, indexer.Pagination) (*indexer.Page[*indexer.ParsedEvent], error)); ok {
		return rf(ctx, partyID, f, p)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, indexer.EventFilter, indexer.Pagination) *indexer.Page[*indexer.ParsedEvent]); ok {
		r0 = rf(ctx, partyID, f, p)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*indexer.Page[*indexer.ParsedEvent])
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, indexer.EventFilter, indexer.Pagination) error); ok {
		r1 = rf(ctx, partyID, f, p)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Service_ListPartyEvents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPartyEvents'
type Service_ListPartyEvents_Call struct {
	*mock.Call
}

// ListPartyEvents is a helper method to define mock.On call
//   - ctx context.Context
//   - partyID string
//   - f indexer.EventFilter
//   - p indexer.Pagination
func (_e *Service_Expecter) ListPartyEvents(ctx interface{}, partyID interface{}, f interface{}, p interface{}) *Service_ListPartyEvents_Call {
	return &Service_ListPartyEvents_Call{Call: _e.mock.On("ListPartyEvents", ctx, partyID, f, p)}
}

func (_c *Service_ListPartyEvents_Call) Run(run func(ctx context.Context, partyID string, f indexer.EventFilter, p indexer.Pagination)) *Service_ListPartyEvents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(indexer.EventFilter), args[3].(indexer.Pagination))
	})
	return _c
}

func (_c *Service_ListPartyEvents_Call) Return(_a0 *indexer.Page[*indexer.ParsedEvent], _a1 error) *Service_ListPartyEvents_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Service_ListPartyEvents_Call) RunAndReturn(run func(context.Context, string, indexer.EventFilter, indexer.Pagination) (*indexer.Page[*indexer.ParsedEvent], error)) *Service_ListPartyEvents_Call {
	_c.Call.Return(run)
	return _c
}

// ListTokenEvents provides a mock function with given fields: ctx, admin, id, f, p
func (_m *Service) ListTokenEvents(ctx context.Context, admin string, id string, f indexer.EventFilter, p indexer.Pagination) (*indexer.Page[*indexer.ParsedEvent], error) {
	ret := _m.Called(ctx, admin, id, f, p)

	if len(ret) == 0 {
		panic("no return value specified for ListTokenEvents")
	}

	var r0 *indexer.Page[*indexer.ParsedEvent]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, indexer.EventFilter, indexer.Pagination) (*indexer.Page[*indexer.ParsedEvent], error)); ok {
		return rf(ctx, admin, id, f, p)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, indexer.EventFilter, indexer.Pagination) *indexer.Page[*indexer.ParsedEvent]); ok {
		r0 = rf(ctx, admin, id, f, p)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*indexer.Page[*indexer.ParsedEvent])
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, indexer.EventFilter, indexer.Pagination) error); ok {
		r1 = rf(ctx, admin, id, f, p)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Service_ListTokenEvents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTokenEvents'
type Service_ListTokenEvents_Call struct {
	*mock.Call
}

// ListTokenEvents is a helper method to define mock.On call
//   - ctx context.Context
//   - admin string
//   - id string
//   - f indexer.EventFilter
//   - p indexer.Pagination
func (_e *Service_Expecter) ListTokenEvents(ctx interface{}, admin interface{}, id interface{}, f interface{}, p interface{}) *Service_ListTokenEvents_Call {
	return &Service_ListTokenEvents_Call{Call: _e.mock.On("ListTokenEvents", ctx, admin, id, f, p)}
}

func (_c *Service_ListTokenEvents_Call) Run(run func(ctx context.Context, admin string, id string, f indexer.EventFilter, p indexer.Pagination)) *Service_ListTokenEvents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(indexer.EventFilter), args[4].(indexer.Pagination))
	})
	return _c
}

func (_c *Service_ListTokenEvents_Call) Return(_a0 *indexer.Page[*indexer.ParsedEvent], _a1 error) *Service_ListTokenEvents_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Service_ListTokenEvents_Call) RunAndReturn(run func(context.Context, string, string, indexer.EventFilter, indexer.Pagination) (*indexer.Page[*indexer.ParsedEvent], error)) *Service_ListTokenEvents_Call {
	_c.Call.Return(run)
	return _c
}

// ListTokens provides a mock function with given fields: ctx, p
func (_m *Service) ListTokens(ctx context.Context, p indexer.Pagination) (*indexer.Page[*indexer.Token], error) {
	ret := _m.Called(ctx, p)

	if len(ret) == 0 {
		panic("no return value specified for ListTokens")
	}

	var r0 *indexer.Page[*indexer.Token]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, indexer.Pagination) (*indexer.Page[*indexer.Token], error)); ok {
		return rf(ctx, p)
	}
	if rf, ok := ret.Get(0).(func(context.Context, indexer.Pagination) *indexer.Page[*indexer.Token]); ok {
		r0 = rf(ctx, p)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*indexer.Page[*indexer.Token])
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, indexer.Pagination) error); ok {
		r1 = rf(ctx, p)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Service_ListTokens_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTokens'
type Service_ListTokens_Call struct {
	*mock.Call
}

// ListTokens is a helper method to define mock.On call
//   - ctx context.Context
//   - p indexer.Pagination
func (_e *Service_Expecter) ListTokens(ctx interface{}, p interface{}) *Service_ListTokens_Call {
	return &Service_ListTokens_Call{Call: _e.mock.On("ListTokens", ctx, p)}
}

func (_c *Service_ListTokens_Call) Run(run func(ctx context.Context, p indexer.Pagination)) *Service_ListTokens_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(indexer.Pagination))
	})
	return _c
}

func (_c *Service_ListTokens_Call) Return(_a0 *indexer.Page[*indexer.Token], _a1 error) *Service_ListTokens_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Service_ListTokens_Call) RunAndReturn(run func(context.Context, indexer.Pagination) (*indexer.Page[*indexer.Token], error)) *Service_ListTokens_Call {
	_c.Call.Return(run)
	return _c
}

// TotalSupply provides a mock function with given fields: ctx, admin, id
func (_m *Service) TotalSupply(ctx context.Context, admin string, id string) (string, error) {
	ret := _m.Called(ctx, admin, id)

	if len(ret) == 0 {
		panic("no return value specified for TotalSupply")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (string, error)); ok {
		return rf(ctx, admin, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = rf(ctx, admin, id)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, admin, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Service_TotalSupply_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TotalSupply'
type Service_TotalSupply_Call struct {
	*mock.Call
}

// TotalSupply is a helper method to define mock.On call
//   - ctx context.Context
//   - admin string
//   - id string
func (_e *Service_Expecter) TotalSupply(ctx interface{}, admin interface{}, id interface{}) *Service_TotalSupply_Call {
	return &Service_TotalSupply_Call{Call: _e.mock.On("TotalSupply", ctx, admin, id)}
}

func (_c *Service_TotalSupply_Call) Run(run func(ctx context.Context, admin string, id string)) *Service_TotalSupply_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *Service_TotalSupply_Call) Return(_a0 string, _a1 error) *Service_TotalSupply_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Service_TotalSupply_Call) RunAndReturn(run func(context.Context, string, string) (string, error)) *Service_TotalSupply_Call {
	_c.Call.Return(run)
	return _c
}

// GetPendingOffersForParty provides a mock function with given fields: ctx, partyID, p
func (_m *Service) GetPendingOffersForParty(ctx context.Context, partyID string, p indexer.Pagination) (*indexer.Page[indexer.PendingOffer], error) {
	ret := _m.Called(ctx, partyID, p)

	if len(ret) == 0 {
		panic("no return value specified for GetPendingOffersForParty")
	}

	var r0 *indexer.Page[indexer.PendingOffer]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, indexer.Pagination) (*indexer.Page[indexer.PendingOffer], error)); ok {
		return rf(ctx, partyID, p)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, indexer.Pagination) *indexer.Page[indexer.PendingOffer]); ok {
		r0 = rf(ctx, partyID, p)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*indexer.Page[indexer.PendingOffer])
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, indexer.Pagination) error); ok {
		r1 = rf(ctx, partyID, p)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Service_GetPendingOffersForParty_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPendingOffersForParty'
type Service_GetPendingOffersForParty_Call struct {
	*mock.Call
}

// GetPendingOffersForParty is a helper method to define mock.On call
//   - ctx context.Context
//   - partyID string
//   - p indexer.Pagination
func (_e *Service_Expecter) GetPendingOffersForParty(ctx any, partyID any, p any) *Service_GetPendingOffersForParty_Call {
	return &Service_GetPendingOffersForParty_Call{Call: _e.mock.On("GetPendingOffersForParty", ctx, partyID, p)}
}

func (_c *Service_GetPendingOffersForParty_Call) Run(run func(ctx context.Context, partyID string, p indexer.Pagination)) *Service_GetPendingOffersForParty_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(indexer.Pagination))
	})
	return _c
}

func (_c *Service_GetPendingOffersForParty_Call) Return(_a0 *indexer.Page[indexer.PendingOffer], _a1 error) *Service_GetPendingOffersForParty_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Service_GetPendingOffersForParty_Call) RunAndReturn(run func(context.Context, string, indexer.Pagination) (*indexer.Page[indexer.PendingOffer], error)) *Service_GetPendingOffersForParty_Call {
	_c.Call.Return(run)
	return _c
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
