// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Checker is an autogenerated mock type for the Checker type
type Checker struct {
	mock.Mock
}

type Checker_Expecter struct {
	mock *mock.Mock
}

func (_m *Checker) EXPECT() *Checker_Expecter {
	return &Checker_Expecter{mock: &_m.Mock}
}

// IsWhitelisted provides a mock function with given fields: ctx, evmAddress
func (_m *Checker) IsWhitelisted(ctx context.Context, evmAddress string) (bool, error) {
	ret := _m.Called(ctx, evmAddress)

	if len(ret) == 0 {
		panic("no return value specified for IsWhitelisted")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, evmAddress)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, evmAddress)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, evmAddress)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Checker_IsWhitelisted_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsWhitelisted'
type Checker_IsWhitelisted_Call struct {
	*mock.Call
}

// IsWhitelisted is a helper method to define mock.On call
//   - ctx context.Context
//   - evmAddress string
func (_e *Checker_Expecter) IsWhitelisted(ctx interface{}, evmAddress interface{}) *Checker_IsWhitelisted_Call {
	return &Checker_IsWhitelisted_Call{Call: _e.mock.On("IsWhitelisted", ctx, evmAddress)}
}

func (_c *Checker_IsWhitelisted_Call) Run(run func(ctx context.Context, evmAddress string)) *Checker_IsWhitelisted_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Checker_IsWhitelisted_Call) Return(_a0 bool, _a1 error) *Checker_IsWhitelisted_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Checker_IsWhitelisted_Call) RunAndReturn(run func(context.Context, string) (bool, error)) *Checker_IsWhitelisted_Call {
	_c.Call.Return(run)
	return _c
}

// NewChecker creates a new instance of Checker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewChecker(t interface {
	mock.TestingT
	Cleanup(func())
}) *Checker {
	mock := &Checker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
