// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	whitelist "github.com/chainsafe/canton-middleware/pkg/user/whitelist"
	mock "github.com/stretchr/testify/mock"
)

// Manager is an autogenerated mock type for the Manager type
type Manager struct {
	mock.Mock
}

type Manager_Expecter struct {
	mock *mock.Mock
}

func (_m *Manager) EXPECT() *Manager_Expecter {
	return &Manager_Expecter{mock: &_m.Mock}
}

// Add provides a mock function with given fields: ctx, evmAddress, note
func (_m *Manager) Add(ctx context.Context, evmAddress string, note string) error {
	ret := _m.Called(ctx, evmAddress, note)

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, evmAddress, note)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Manager_Add_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Add'
type Manager_Add_Call struct {
	*mock.Call
}

// Add is a helper method to define mock.On call
//   - ctx context.Context
//   - evmAddress string
//   - note string
func (_e *Manager_Expecter) Add(ctx interface{}, evmAddress interface{}, note interface{}) *Manager_Add_Call {
	return &Manager_Add_Call{Call: _e.mock.On("Add", ctx, evmAddress, note)}
}

func (_c *Manager_Add_Call) Run(run func(ctx context.Context, evmAddress string, note string)) *Manager_Add_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *Manager_Add_Call) Return(_a0 error) *Manager_Add_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Manager_Add_Call) RunAndReturn(run func(context.Context, string, string) error) *Manager_Add_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, cursor, limit
func (_m *Manager) List(ctx context.Context, cursor string, limit int) (*whitelist.Page, error) {
	ret := _m.Called(ctx, cursor, limit)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *whitelist.Page
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int) (*whitelist.Page, error)); ok {
		return rf(ctx, cursor, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int) *whitelist.Page); ok {
		r0 = rf(ctx, cursor, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*whitelist.Page)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int) error); ok {
		r1 = rf(ctx, cursor, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Manager_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type Manager_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - cursor string
//   - limit int
func (_e *Manager_Expecter) List(ctx interface{}, cursor interface{}, limit interface{}) *Manager_List_Call {
	return &Manager_List_Call{Call: _e.mock.On("List", ctx, cursor, limit)}
}

func (_c *Manager_List_Call) Run(run func(ctx context.Context, cursor string, limit int)) *Manager_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int))
	})
	return _c
}

func (_c *Manager_List_Call) Return(_a0 *whitelist.Page, _a1 error) *Manager_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Manager_List_Call) RunAndReturn(run func(context.Context, string, int) (*whitelist.Page, error)) *Manager_List_Call {
	_c.Call.Return(run)
	return _c
}

// Remove provides a mock function with given fields: ctx, evmAddress
func (_m *Manager) Remove(ctx context.Context, evmAddress string) error {
	ret := _m.Called(ctx, evmAddress)

	if len(ret) == 0 {
		panic("no return value specified for Remove")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, evmAddress)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Manager_Remove_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Remove'
type Manager_Remove_Call struct {
	*mock.Call
}

// Remove is a helper method to define mock.On call
//   - ctx context.Context
//   - evmAddress string
func (_e *Manager_Expecter) Remove(ctx interface{}, evmAddress interface{}) *Manager_Remove_Call {
	return &Manager_Remove_Call{Call: _e.mock.On("Remove", ctx, evmAddress)}
}

func (_c *Manager_Remove_Call) Run(run func(ctx context.Context, evmAddress string)) *Manager_Remove_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Manager_Remove_Call) Return(_a0 error) *Manager_Remove_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Manager_Remove_Call) RunAndReturn(run func(context.Context, string) error) *Manager_Remove_Call {
	_c.Call.Return(run)
	return _c
}

// NewManager creates a new instance of Manager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *Manager {
	mock := &Manager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
