---
name: Bug
about: a fault with unintended results
title: ""
type: Bug
assignees: ""
---

**What**

Describe the bug.

**How to Reproduce**

Ways (steps to take) to reproduce the bug.

**Expectation**

A clear description of the intended result.

**Additional Context (optional)**

Add any other context to help explain or fix the bug.

**Estimation**

Put in a number relative to an anchor item of work estimation.

**Dependencies**

List any work items that this one depends on.