---
name: Epic
about: a large piece of work that spans multiple items of work with similar context
title: "[EPIC] "
labels: ""
type: Epic
assignees: ""
---

**Objective**

The overall goal this epic aims to achieve.

**Estimation**

The sum estimation of all the items of work that make up this epic.

**Dependencies**

List any work items that this one depends on.