---
name: Feature
about: a new item of work that'll add or improve value
title: ""
labels: ""
type: Feature
assignees: ""
---

**What**

Describe the feature.

**Why**

Why is this important/relevant

**How**

Ways (steps to take) to implement the feature.

**Acceptance Criteria**

A set of conditions that must be met for the work to be considered complete.

**Estimation**

Put in a number relative to an anchor item of work estimation.

**Dependencies**

List any work items that this one depends on.