// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	user "github.com/chainsafe/canton-middleware/pkg/user"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

type Service_Expecter struct {
	mock *mock.Mock
}

func (_m *Service) EXPECT() *Service_Expecter {
	return &Service_Expecter{mock: &_m.Mock}
}

// GetUser provides a mock function with given fields: ctx, evmAddress, msg, sig
func (_m *Service) GetUser(ctx context.Context, evmAddress string, msg string, sig string) (*user.User, error) {
	ret := _m.Called(ctx, evmAddress, msg, sig)

	if len(ret) == 0 {
		panic("no return value specified for GetUser")
	}

	var r0 *user.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (*user.User, error)); ok {
		return rf(ctx, evmAddress, msg, sig)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) *user.User); ok {
		r0 = rf(ctx, evmAddress, msg, sig)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, evmAddress, msg, sig)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Service_GetUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUser'
type Service_GetUser_Call struct {
	*mock.Call
}

// GetUser is a helper method to define mock.On call
//   - ctx context.Context
//   - evmAddress string
//   - msg string
//   - sig string
func (_e *Service_Expecter) GetUser(ctx interface{}, evmAddress interface{}, msg interface{}, sig interface{}) *Service_GetUser_Call {
	return &Service_GetUser_Call{Call: _e.mock.On("GetUser", ctx, evmAddress, msg, sig)}
}

func (_c *Service_GetUser_Call) Run(run func(ctx context.Context, evmAddress string, msg string, sig string)) *Service_GetUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *Service_GetUser_Call) Return(_a0 *user.User, _a1 error) *Service_GetUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Service_GetUser_Call) RunAndReturn(run func(context.Context, string, string, string) (*user.User, error)) *Service_GetUser_Call {
	_c.Call.Return(run)
	return _c
}

// PrepareExternalRegistration provides a mock function with given fields: ctx, req
func (_m *Service) PrepareExternalRegistration(ctx context.Context, req *user.RegisterRequest) (*user.PrepareTopologyResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for PrepareExternalRegistration")
	}

	var r0 *user.PrepareTopologyResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *user.RegisterRequest) (*user.PrepareTopologyResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *user.RegisterRequest) *user.PrepareTopologyResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.PrepareTopologyResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *user.RegisterRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Service_PrepareExternalRegistration_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PrepareExternalRegistration'
type Service_PrepareExternalRegistration_Call struct {
	*mock.Call
}

// PrepareExternalRegistration is a helper method to define mock.On call
//   - ctx context.Context
//   - req *user.RegisterRequest
func (_e *Service_Expecter) PrepareExternalRegistration(ctx interface{}, req interface{}) *Service_PrepareExternalRegistration_Call {
	return &Service_PrepareExternalRegistration_Call{Call: _e.mock.On("PrepareExternalRegistration", ctx, req)}
}

func (_c *Service_PrepareExternalRegistration_Call) Run(run func(ctx context.Context, req *user.RegisterRequest)) *Service_PrepareExternalRegistration_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*user.RegisterRequest))
	})
	return _c
}

func (_c *Service_PrepareExternalRegistration_Call) Return(_a0 *user.PrepareTopologyResponse, _a1 error) *Service_PrepareExternalRegistration_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Service_PrepareExternalRegistration_Call) RunAndReturn(run func(context.Context, *user.RegisterRequest) (*user.PrepareTopologyResponse, error)) *Service_PrepareExternalRegistration_Call {
	_c.Call.Return(run)
	return _c
}

// RegisterCantonNativeUser provides a mock function with given fields: ctx, req
func (_m *Service) RegisterCantonNativeUser(ctx context.Context, req *user.RegisterRequest) (*user.RegisterResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for RegisterCantonNativeUser")
	}

	var r0 *user.RegisterResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *user.RegisterRequest) (*user.RegisterResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *user.RegisterRequest) *user.RegisterResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.RegisterResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *user.RegisterRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Service_RegisterCantonNativeUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterCantonNativeUser'
type Service_RegisterCantonNativeUser_Call struct {
	*mock.Call
}

// RegisterCantonNativeUser is a helper method to define mock.On call
//   - ctx context.Context
//   - req *user.RegisterRequest
func (_e *Service_Expecter) RegisterCantonNativeUser(ctx interface{}, req interface{}) *Service_RegisterCantonNativeUser_Call {
	return &Service_RegisterCantonNativeUser_Call{Call: _e.mock.On("RegisterCantonNativeUser", ctx, req)}
}

func (_c *Service_RegisterCantonNativeUser_Call) Run(run func(ctx context.Context, req *user.RegisterRequest)) *Service_RegisterCantonNativeUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*user.RegisterRequest))
	})
	return _c
}

func (_c *Service_RegisterCantonNativeUser_Call) Return(_a0 *user.RegisterResponse, _a1 error) *Service_RegisterCantonNativeUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Service_RegisterCantonNativeUser_Call) RunAndReturn(run func(context.Context, *user.RegisterRequest) (*user.RegisterResponse, error)) *Service_RegisterCantonNativeUser_Call {
	_c.Call.Return(run)
	return _c
}

// RegisterWeb3User provides a mock function with given fields: ctx, req
func (_m *Service) RegisterWeb3User(ctx context.Context, req *user.RegisterRequest) (*user.RegisterResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for RegisterWeb3User")
	}

	var r0 *user.RegisterResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *user.RegisterRequest) (*user.RegisterResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *user.RegisterRequest) *user.RegisterResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.RegisterResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *user.RegisterRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Service_RegisterWeb3User_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterWeb3User'
type Service_RegisterWeb3User_Call struct {
	*mock.Call
}

// RegisterWeb3User is a helper method to define mock.On call
//   - ctx context.Context
//   - req *user.RegisterRequest
func (_e *Service_Expecter) RegisterWeb3User(ctx interface{}, req interface{}) *Service_RegisterWeb3User_Call {
	return &Service_RegisterWeb3User_Call{Call: _e.mock.On("RegisterWeb3User", ctx, req)}
}

func (_c *Service_RegisterWeb3User_Call) Run(run func(ctx context.Context, req *user.RegisterRequest)) *Service_RegisterWeb3User_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*user.RegisterRequest))
	})
	return _c
}

func (_c *Service_RegisterWeb3User_Call) Return(_a0 *user.RegisterResponse, _a1 error) *Service_RegisterWeb3User_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Service_RegisterWeb3User_Call) RunAndReturn(run func(context.Context, *user.RegisterRequest) (*user.RegisterResponse, error)) *Service_RegisterWeb3User_Call {
	_c.Call.Return(run)
	return _c
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
