// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	user "github.com/chainsafe/canton-middleware/pkg/user"
)

// Store is an autogenerated mock type for the Store type
type Store struct {
	mock.Mock
}

type Store_Expecter struct {
	mock *mock.Mock
}

func (_m *Store) EXPECT() *Store_Expecter {
	return &Store_Expecter{mock: &_m.Mock}
}

// CreateUser provides a mock function with given fields: ctx, _a1
func (_m *Store) CreateUser(ctx context.Context, _a1 *user.User) error {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *user.User) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Store_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type Store_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 *user.User
func (_e *Store_Expecter) CreateUser(ctx interface{}, _a1 interface{}) *Store_CreateUser_Call {
	return &Store_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, _a1)}
}

func (_c *Store_CreateUser_Call) Run(run func(ctx context.Context, _a1 *user.User)) *Store_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*user.User))
	})
	return _c
}

func (_c *Store_CreateUser_Call) Return(_a0 error) *Store_CreateUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Store_CreateUser_Call) RunAndReturn(run func(context.Context, *user.User) error) *Store_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteUser provides a mock function with given fields: ctx, evmAddress
func (_m *Store) DeleteUser(ctx context.Context, evmAddress string) error {
	ret := _m.Called(ctx, evmAddress)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, evmAddress)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Store_DeleteUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteUser'
type Store_DeleteUser_Call struct {
	*mock.Call
}

// DeleteUser is a helper method to define mock.On call
//   - ctx context.Context
//   - evmAddress string
func (_e *Store_Expecter) DeleteUser(ctx interface{}, evmAddress interface{}) *Store_DeleteUser_Call {
	return &Store_DeleteUser_Call{Call: _e.mock.On("DeleteUser", ctx, evmAddress)}
}

func (_c *Store_DeleteUser_Call) Run(run func(ctx context.Context, evmAddress string)) *Store_DeleteUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Store_DeleteUser_Call) Return(_a0 error) *Store_DeleteUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Store_DeleteUser_Call) RunAndReturn(run func(context.Context, string) error) *Store_DeleteUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByCantonPartyID provides a mock function with given fields: ctx, partyID
func (_m *Store) GetUserByCantonPartyID(ctx context.Context, partyID string) (*user.User, error) {
	ret := _m.Called(ctx, partyID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByCantonPartyID")
	}

	var r0 *user.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*user.User, error)); ok {
		return rf(ctx, partyID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *user.User); ok {
		r0 = rf(ctx, partyID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, partyID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store_GetUserByCantonPartyID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByCantonPartyID'
type Store_GetUserByCantonPartyID_Call struct {
	*mock.Call
}

// GetUserByCantonPartyID is a helper method to define mock.On call
//   - ctx context.Context
//   - partyID string
func (_e *Store_Expecter) GetUserByCantonPartyID(ctx interface{}, partyID interface{}) *Store_GetUserByCantonPartyID_Call {
	return &Store_GetUserByCantonPartyID_Call{Call: _e.mock.On("GetUserByCantonPartyID", ctx, partyID)}
}

func (_c *Store_GetUserByCantonPartyID_Call) Run(run func(ctx context.Context, partyID string)) *Store_GetUserByCantonPartyID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Store_GetUserByCantonPartyID_Call) Return(_a0 *user.User, _a1 error) *Store_GetUserByCantonPartyID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Store_GetUserByCantonPartyID_Call) RunAndReturn(run func(context.Context, string) (*user.User, error)) *Store_GetUserByCantonPartyID_Call {
	_c.Call.Return(run)
	return _c
}

// IsWhitelisted provides a mock function with given fields: ctx, evmAddress
func (_m *Store) IsWhitelisted(ctx context.Context, evmAddress string) (bool, error) {
	ret := _m.Called(ctx, evmAddress)

	if len(ret) == 0 {
		panic("no return value specified for IsWhitelisted")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, evmAddress)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, evmAddress)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, evmAddress)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store_IsWhitelisted_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsWhitelisted'
type Store_IsWhitelisted_Call struct {
	*mock.Call
}

// IsWhitelisted is a helper method to define mock.On call
//   - ctx context.Context
//   - evmAddress string
func (_e *Store_Expecter) IsWhitelisted(ctx interface{}, evmAddress interface{}) *Store_IsWhitelisted_Call {
	return &Store_IsWhitelisted_Call{Call: _e.mock.On("IsWhitelisted", ctx, evmAddress)}
}

func (_c *Store_IsWhitelisted_Call) Run(run func(ctx context.Context, evmAddress string)) *Store_IsWhitelisted_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Store_IsWhitelisted_Call) Return(_a0 bool, _a1 error) *Store_IsWhitelisted_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Store_IsWhitelisted_Call) RunAndReturn(run func(context.Context, string) (bool, error)) *Store_IsWhitelisted_Call {
	_c.Call.Return(run)
	return _c
}

// UserExists provides a mock function with given fields: ctx, evmAddress
func (_m *Store) UserExists(ctx context.Context, evmAddress string) (bool, error) {
	ret := _m.Called(ctx, evmAddress)

	if len(ret) == 0 {
		panic("no return value specified for UserExists")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, evmAddress)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, evmAddress)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, evmAddress)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store_UserExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UserExists'
type Store_UserExists_Call struct {
	*mock.Call
}

// UserExists is a helper method to define mock.On call
//   - ctx context.Context
//   - evmAddress string
func (_e *Store_Expecter) UserExists(ctx interface{}, evmAddress interface{}) *Store_UserExists_Call {
	return &Store_UserExists_Call{Call: _e.mock.On("UserExists", ctx, evmAddress)}
}

func (_c *Store_UserExists_Call) Run(run func(ctx context.Context, evmAddress string)) *Store_UserExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Store_UserExists_Call) Return(_a0 bool, _a1 error) *Store_UserExists_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Store_UserExists_Call) RunAndReturn(run func(context.Context, string) (bool, error)) *Store_UserExists_Call {
	_c.Call.Return(run)
	return _c
}

// NewStore creates a new instance of Store. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *Store {
	mock := &Store{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
