// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	identity "github.com/chainsafe/canton-middleware/pkg/cantonsdk/identity"
	user "github.com/chainsafe/canton-middleware/pkg/user"
)

// TopologyCacheProvider is an autogenerated mock type for the TopologyCacheProvider type
type TopologyCacheProvider struct {
	mock.Mock
}

type TopologyCacheProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *TopologyCacheProvider) EXPECT() *TopologyCacheProvider_Expecter {
	return &TopologyCacheProvider_Expecter{mock: &_m.Mock}
}

// Put provides a mock function with given fields: token, topo, spkiKey
func (_m *TopologyCacheProvider) Put(token string, topo *identity.ExternalPartyTopology, spkiKey []byte) {
	_m.Called(token, topo, spkiKey)
}

// TopologyCacheProvider_Put_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Put'
type TopologyCacheProvider_Put_Call struct {
	*mock.Call
}

// Put is a helper method to define mock.On call
//   - token string
//   - topo *identity.ExternalPartyTopology
//   - spkiKey []byte
func (_e *TopologyCacheProvider_Expecter) Put(token interface{}, topo interface{}, spkiKey interface{}) *TopologyCacheProvider_Put_Call {
	return &TopologyCacheProvider_Put_Call{Call: _e.mock.On("Put", token, topo, spkiKey)}
}

func (_c *TopologyCacheProvider_Put_Call) Run(run func(token string, topo *identity.ExternalPartyTopology, spkiKey []byte)) *TopologyCacheProvider_Put_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(*identity.ExternalPartyTopology), args[2].([]byte))
	})
	return _c
}

func (_c *TopologyCacheProvider_Put_Call) Return() *TopologyCacheProvider_Put_Call {
	_c.Call.Return()
	return _c
}

func (_c *TopologyCacheProvider_Put_Call) RunAndReturn(run func(string, *identity.ExternalPartyTopology, []byte)) *TopologyCacheProvider_Put_Call {
	_c.Run(run)
	return _c
}

// GetAndDelete provides a mock function with given fields: token
func (_m *TopologyCacheProvider) GetAndDelete(token string) (*user.PendingTopology, error) {
	ret := _m.Called(token)

	if len(ret) == 0 {
		panic("no return value specified for GetAndDelete")
	}

	var r0 *user.PendingTopology
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*user.PendingTopology, error)); ok {
		return rf(token)
	}
	if rf, ok := ret.Get(0).(func(string) *user.PendingTopology); ok {
		r0 = rf(token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.PendingTopology)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TopologyCacheProvider_GetAndDelete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAndDelete'
type TopologyCacheProvider_GetAndDelete_Call struct {
	*mock.Call
}

// GetAndDelete is a helper method to define mock.On call
//   - token string
func (_e *TopologyCacheProvider_Expecter) GetAndDelete(token interface{}) *TopologyCacheProvider_GetAndDelete_Call {
	return &TopologyCacheProvider_GetAndDelete_Call{Call: _e.mock.On("GetAndDelete", token)}
}

func (_c *TopologyCacheProvider_GetAndDelete_Call) Run(run func(token string)) *TopologyCacheProvider_GetAndDelete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *TopologyCacheProvider_GetAndDelete_Call) Return(_a0 *user.PendingTopology, _a1 error) *TopologyCacheProvider_GetAndDelete_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TopologyCacheProvider_GetAndDelete_Call) RunAndReturn(run func(string) (*user.PendingTopology, error)) *TopologyCacheProvider_GetAndDelete_Call {
	_c.Call.Return(run)
	return _c
}

// NewTopologyCacheProvider creates a new instance of TopologyCacheProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTopologyCacheProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *TopologyCacheProvider {
	mock := &TopologyCacheProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
