// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	ethrpc "github.com/chainsafe/canton-middleware/pkg/ethrpc"
	mock "github.com/stretchr/testify/mock"
)

// PendingBlock is an autogenerated mock type for the PendingBlock type
type PendingBlock struct {
	mock.Mock
}

type PendingBlock_Expecter struct {
	mock *mock.Mock
}

func (_m *PendingBlock) EXPECT() *PendingBlock_Expecter {
	return &PendingBlock_Expecter{mock: &_m.Mock}
}

// Abort provides a mock function with given fields: ctx
func (_m *PendingBlock) Abort(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Abort")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PendingBlock_Abort_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Abort'
type PendingBlock_Abort_Call struct {
	*mock.Call
}

// Abort is a helper method to define mock.On call
//   - ctx context.Context
func (_e *PendingBlock_Expecter) Abort(ctx interface{}) *PendingBlock_Abort_Call {
	return &PendingBlock_Abort_Call{Call: _e.mock.On("Abort", ctx)}
}

func (_c *PendingBlock_Abort_Call) Run(run func(ctx context.Context)) *PendingBlock_Abort_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *PendingBlock_Abort_Call) Return(_a0 error) *PendingBlock_Abort_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PendingBlock_Abort_Call) RunAndReturn(run func(context.Context) error) *PendingBlock_Abort_Call {
	_c.Call.Return(run)
	return _c
}

// AddEvmLog provides a mock function with given fields: ctx, log
func (_m *PendingBlock) AddEvmLog(ctx context.Context, log *ethrpc.EvmLog) error {
	ret := _m.Called(ctx, log)

	if len(ret) == 0 {
		panic("no return value specified for AddEvmLog")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *ethrpc.EvmLog) error); ok {
		r0 = rf(ctx, log)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PendingBlock_AddEvmLog_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddEvmLog'
type PendingBlock_AddEvmLog_Call struct {
	*mock.Call
}

// AddEvmLog is a helper method to define mock.On call
//   - ctx context.Context
//   - log *ethrpc.EvmLog
func (_e *PendingBlock_Expecter) AddEvmLog(ctx interface{}, log interface{}) *PendingBlock_AddEvmLog_Call {
	return &PendingBlock_AddEvmLog_Call{Call: _e.mock.On("AddEvmLog", ctx, log)}
}

func (_c *PendingBlock_AddEvmLog_Call) Run(run func(ctx context.Context, log *ethrpc.EvmLog)) *PendingBlock_AddEvmLog_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*ethrpc.EvmLog))
	})
	return _c
}

func (_c *PendingBlock_AddEvmLog_Call) Return(_a0 error) *PendingBlock_AddEvmLog_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PendingBlock_AddEvmLog_Call) RunAndReturn(run func(context.Context, *ethrpc.EvmLog) error) *PendingBlock_AddEvmLog_Call {
	_c.Call.Return(run)
	return _c
}

// AddEvmTransaction provides a mock function with given fields: ctx, tx
func (_m *PendingBlock) AddEvmTransaction(ctx context.Context, tx *ethrpc.EvmTransaction) error {
	ret := _m.Called(ctx, tx)

	if len(ret) == 0 {
		panic("no return value specified for AddEvmTransaction")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *ethrpc.EvmTransaction) error); ok {
		r0 = rf(ctx, tx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PendingBlock_AddEvmTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddEvmTransaction'
type PendingBlock_AddEvmTransaction_Call struct {
	*mock.Call
}

// AddEvmTransaction is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *ethrpc.EvmTransaction
func (_e *PendingBlock_Expecter) AddEvmTransaction(ctx interface{}, tx interface{}) *PendingBlock_AddEvmTransaction_Call {
	return &PendingBlock_AddEvmTransaction_Call{Call: _e.mock.On("AddEvmTransaction", ctx, tx)}
}

func (_c *PendingBlock_AddEvmTransaction_Call) Run(run func(ctx context.Context, tx *ethrpc.EvmTransaction)) *PendingBlock_AddEvmTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*ethrpc.EvmTransaction))
	})
	return _c
}

func (_c *PendingBlock_AddEvmTransaction_Call) Return(_a0 error) *PendingBlock_AddEvmTransaction_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PendingBlock_AddEvmTransaction_Call) RunAndReturn(run func(context.Context, *ethrpc.EvmTransaction) error) *PendingBlock_AddEvmTransaction_Call {
	_c.Call.Return(run)
	return _c
}

// Finalize provides a mock function with given fields: ctx
func (_m *PendingBlock) Finalize(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Finalize")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PendingBlock_Finalize_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Finalize'
type PendingBlock_Finalize_Call struct {
	*mock.Call
}

// Finalize is a helper method to define mock.On call
//   - ctx context.Context
func (_e *PendingBlock_Expecter) Finalize(ctx interface{}) *PendingBlock_Finalize_Call {
	return &PendingBlock_Finalize_Call{Call: _e.mock.On("Finalize", ctx)}
}

func (_c *PendingBlock_Finalize_Call) Run(run func(ctx context.Context)) *PendingBlock_Finalize_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *PendingBlock_Finalize_Call) Return(_a0 error) *PendingBlock_Finalize_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PendingBlock_Finalize_Call) RunAndReturn(run func(context.Context) error) *PendingBlock_Finalize_Call {
	_c.Call.Return(run)
	return _c
}

// Hash provides a mock function with no fields
func (_m *PendingBlock) Hash() []byte {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Hash")
	}

	var r0 []byte
	if rf, ok := ret.Get(0).(func() []byte); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	return r0
}

// PendingBlock_Hash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Hash'
type PendingBlock_Hash_Call struct {
	*mock.Call
}

// Hash is a helper method to define mock.On call
func (_e *PendingBlock_Expecter) Hash() *PendingBlock_Hash_Call {
	return &PendingBlock_Hash_Call{Call: _e.mock.On("Hash")}
}

func (_c *PendingBlock_Hash_Call) Run(run func()) *PendingBlock_Hash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *PendingBlock_Hash_Call) Return(_a0 []byte) *PendingBlock_Hash_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PendingBlock_Hash_Call) RunAndReturn(run func() []byte) *PendingBlock_Hash_Call {
	_c.Call.Return(run)
	return _c
}

// Number provides a mock function with no fields
func (_m *PendingBlock) Number() uint64 {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Number")
	}

	var r0 uint64
	if rf, ok := ret.Get(0).(func() uint64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(uint64)
	}

	return r0
}

// PendingBlock_Number_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Number'
type PendingBlock_Number_Call struct {
	*mock.Call
}

// Number is a helper method to define mock.On call
func (_e *PendingBlock_Expecter) Number() *PendingBlock_Number_Call {
	return &PendingBlock_Number_Call{Call: _e.mock.On("Number")}
}

func (_c *PendingBlock_Number_Call) Run(run func()) *PendingBlock_Number_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *PendingBlock_Number_Call) Return(_a0 uint64) *PendingBlock_Number_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PendingBlock_Number_Call) RunAndReturn(run func() uint64) *PendingBlock_Number_Call {
	_c.Call.Return(run)
	return _c
}

// SealMempoolEntries provides a mock function with given fields: ctx, txHashes
func (_m *PendingBlock) SealMempoolEntries(ctx context.Context, txHashes [][]byte) error {
	ret := _m.Called(ctx, txHashes)

	if len(ret) == 0 {
		panic("no return value specified for SealMempoolEntries")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, [][]byte) error); ok {
		r0 = rf(ctx, txHashes)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PendingBlock_SealMempoolEntries_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SealMempoolEntries'
type PendingBlock_SealMempoolEntries_Call struct {
	*mock.Call
}

// SealMempoolEntries is a helper method to define mock.On call
//   - ctx context.Context
//   - txHashes [][]byte
func (_e *PendingBlock_Expecter) SealMempoolEntries(ctx interface{}, txHashes interface{}) *PendingBlock_SealMempoolEntries_Call {
	return &PendingBlock_SealMempoolEntries_Call{Call: _e.mock.On("SealMempoolEntries", ctx, txHashes)}
}

func (_c *PendingBlock_SealMempoolEntries_Call) Run(run func(ctx context.Context, txHashes [][]byte)) *PendingBlock_SealMempoolEntries_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([][]byte))
	})
	return _c
}

func (_c *PendingBlock_SealMempoolEntries_Call) Return(_a0 error) *PendingBlock_SealMempoolEntries_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PendingBlock_SealMempoolEntries_Call) RunAndReturn(run func(context.Context, [][]byte) error) *PendingBlock_SealMempoolEntries_Call {
	_c.Call.Return(run)
	return _c
}

// NewPendingBlock creates a new instance of PendingBlock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPendingBlock(t interface {
	mock.TestingT
	Cleanup(func())
}) *PendingBlock {
	mock := &PendingBlock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
