// Copyright (c) 2024 Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: com/daml/ledger/api/v1/transaction_filter.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A filter both for filtering create and archive events as well as for
// filtering transaction trees.
type TransactionFilter struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Each key must be a valid PartyIdString (as described in “value.proto“).
	// The interpretation of the filter depends on the stream being filtered:
	//
	//  1. For **transaction tree streams** only party filters with wildcards are allowed, and all subtrees
	//     whose root has one of the listed parties as an informee are returned.
	//  2. For **transaction and active-contract-set streams** create and archive events are returned for all contracts whose
	//     stakeholders include at least one of the listed parties and match the
	//     per-party filter.
	//
	// Required
	FiltersByParty map[string]*Filters `protobuf:"bytes,1,rep,name=filters_by_party,json=filtersByParty,proto3" json:"filters_by_party,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TransactionFilter) Reset() {
	*x = TransactionFilter{}
	mi := &file_com_daml_ledger_api_v1_transaction_filter_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionFilter) ProtoMessage() {}

func (x *TransactionFilter) ProtoReflect() protoreflect.Message {
	mi := &file_com_daml_ledger_api_v1_transaction_filter_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionFilter.ProtoReflect.Descriptor instead.
func (*TransactionFilter) Descriptor() ([]byte, []int) {
	return file_com_daml_ledger_api_v1_transaction_filter_proto_rawDescGZIP(), []int{0}
}

func (x *TransactionFilter) GetFiltersByParty() map[string]*Filters {
	if x != nil {
		return x.FiltersByParty
	}
	return nil
}

// The union of a set of contract filters, or a wildcard.
type Filters struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// If set, then contracts matching any of the “InclusiveFilters“ match
	// this filter.
	// If not set, or if “InclusiveFilters“ has empty “template_ids“ and empty “interface_filters“:
	// any contract matches this filter.
	// Optional
	Inclusive     *InclusiveFilters `protobuf:"bytes,1,opt,name=inclusive,proto3" json:"inclusive,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Filters) Reset() {
	*x = Filters{}
	mi := &file_com_daml_ledger_api_v1_transaction_filter_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Filters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Filters) ProtoMessage() {}

func (x *Filters) ProtoReflect() protoreflect.Message {
	mi := &file_com_daml_ledger_api_v1_transaction_filter_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Filters.ProtoReflect.Descriptor instead.
func (*Filters) Descriptor() ([]byte, []int) {
	return file_com_daml_ledger_api_v1_transaction_filter_proto_rawDescGZIP(), []int{1}
}

func (x *Filters) GetInclusive() *InclusiveFilters {
	if x != nil {
		return x.Inclusive
	}
	return nil
}

// A filter that matches all contracts that are either an instance of one of
// the “template_ids“ or that match one of the “interface_filters“.
type InclusiveFilters struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A collection of templates for which the data will be included in the
	// “create_arguments“ of a matching “CreatedEvent“.
	// SHOULD NOT contain duplicates.
	// All “template_ids“ need to be valid: corresponding templates should be defined in one of
	// the available packages at the time of the query.
	// Deprecated in favor of the “template_filters“. If the “template_filters“ field is set,
	// the “template_ids“ field is ignored.
	// Optional
	//
	// Deprecated: Marked as deprecated in com/daml/ledger/api/v1/transaction_filter.proto.
	TemplateIds []*Identifier `protobuf:"bytes,1,rep,name=template_ids,json=templateIds,proto3" json:"template_ids,omitempty"`
	// Include an “InterfaceView“ for every “InterfaceFilter“ matching a contract.
	// The “InterfaceFilter“ instances MUST each use a unique “interface_id“.
	// Optional
	InterfaceFilters []*InterfaceFilter `protobuf:"bytes,2,rep,name=interface_filters,json=interfaceFilters,proto3" json:"interface_filters,omitempty"`
	// A collection of templates for which the data will be included in the
	// “create_arguments“ of a matching “CreatedEvent“.
	// SHOULD NOT contain duplicate templates.
	// In contrast to the “template_ids“ field, one can specify whether the create event payloads
	// should be provided alongside the create arguments.
	// If a contract is simultaneously selected by a template filter and one or more interface filters,
	// the corresponding “include_created_event_blob“ are consolidated using an OR operation.
	// Optional
	TemplateFilters []*TemplateFilter `protobuf:"bytes,3,rep,name=template_filters,json=templateFilters,proto3" json:"template_filters,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *InclusiveFilters) Reset() {
	*x = InclusiveFilters{}
	mi := &file_com_daml_ledger_api_v1_transaction_filter_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InclusiveFilters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InclusiveFilters) ProtoMessage() {}

func (x *InclusiveFilters) ProtoReflect() protoreflect.Message {
	mi := &file_com_daml_ledger_api_v1_transaction_filter_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InclusiveFilters.ProtoReflect.Descriptor instead.
func (*InclusiveFilters) Descriptor() ([]byte, []int) {
	return file_com_daml_ledger_api_v1_transaction_filter_proto_rawDescGZIP(), []int{2}
}

// Deprecated: Marked as deprecated in com/daml/ledger/api/v1/transaction_filter.proto.
func (x *InclusiveFilters) GetTemplateIds() []*Identifier {
	if x != nil {
		return x.TemplateIds
	}
	return nil
}

func (x *InclusiveFilters) GetInterfaceFilters() []*InterfaceFilter {
	if x != nil {
		return x.InterfaceFilters
	}
	return nil
}

func (x *InclusiveFilters) GetTemplateFilters() []*TemplateFilter {
	if x != nil {
		return x.TemplateFilters
	}
	return nil
}

// This filter matches contracts that implement a specific interface.
type InterfaceFilter struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The interface that a matching contract must implement.
	// The “interface_id“ needs to be valid: corresponding interface should be defined in
	// one of the available packages at the time of the query.
	// Both package-name and package-id reference formats for the identifier are supported.
	//
	// Required
	InterfaceId *Identifier `protobuf:"bytes,1,opt,name=interface_id,json=interfaceId,proto3" json:"interface_id,omitempty"`
	// Whether to include the interface view on the contract in the returned “CreatedEvent“.
	// Use this to access contract data in a uniform manner in your API client.
	// Optional
	IncludeInterfaceView bool `protobuf:"varint,2,opt,name=include_interface_view,json=includeInterfaceView,proto3" json:"include_interface_view,omitempty"`
	// Whether to include a “created_event_blob“ in the returned “CreatedEvent“.
	// Use this to access the contract create event payload in your API client
	// for submitting it as a disclosed contract with future commands.
	// Optional
	IncludeCreatedEventBlob bool `protobuf:"varint,4,opt,name=include_created_event_blob,json=includeCreatedEventBlob,proto3" json:"include_created_event_blob,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *InterfaceFilter) Reset() {
	*x = InterfaceFilter{}
	mi := &file_com_daml_ledger_api_v1_transaction_filter_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InterfaceFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InterfaceFilter) ProtoMessage() {}

func (x *InterfaceFilter) ProtoReflect() protoreflect.Message {
	mi := &file_com_daml_ledger_api_v1_transaction_filter_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InterfaceFilter.ProtoReflect.Descriptor instead.
func (*InterfaceFilter) Descriptor() ([]byte, []int) {
	return file_com_daml_ledger_api_v1_transaction_filter_proto_rawDescGZIP(), []int{3}
}

func (x *InterfaceFilter) GetInterfaceId() *Identifier {
	if x != nil {
		return x.InterfaceId
	}
	return nil
}

func (x *InterfaceFilter) GetIncludeInterfaceView() bool {
	if x != nil {
		return x.IncludeInterfaceView
	}
	return false
}

func (x *InterfaceFilter) GetIncludeCreatedEventBlob() bool {
	if x != nil {
		return x.IncludeCreatedEventBlob
	}
	return false
}

// This filter matches contracts of a specific template.
type TemplateFilter struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A template for which the payload should be included in the response.
	// The “template_id“ needs to be valid: corresponding template should be defined in
	// one of the available packages at the time of the query.
	// Both package-name and package-id reference formats for the identifier are supported.
	//
	// Required
	TemplateId *Identifier `protobuf:"bytes,1,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	// Whether to include a “created_event_blob“ in the returned “CreatedEvent“.
	// Use this to access the contract event payload in your API client
	// for submitting it as a disclosed contract with future commands.
	// Optional
	IncludeCreatedEventBlob bool `protobuf:"varint,2,opt,name=include_created_event_blob,json=includeCreatedEventBlob,proto3" json:"include_created_event_blob,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *TemplateFilter) Reset() {
	*x = TemplateFilter{}
	mi := &file_com_daml_ledger_api_v1_transaction_filter_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TemplateFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemplateFilter) ProtoMessage() {}

func (x *TemplateFilter) ProtoReflect() protoreflect.Message {
	mi := &file_com_daml_ledger_api_v1_transaction_filter_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemplateFilter.ProtoReflect.Descriptor instead.
func (*TemplateFilter) Descriptor() ([]byte, []int) {
	return file_com_daml_ledger_api_v1_transaction_filter_proto_rawDescGZIP(), []int{4}
}

func (x *TemplateFilter) GetTemplateId() *Identifier {
	if x != nil {
		return x.TemplateId
	}
	return nil
}

func (x *TemplateFilter) GetIncludeCreatedEventBlob() bool {
	if x != nil {
		return x.IncludeCreatedEventBlob
	}
	return false
}

var File_com_daml_ledger_api_v1_transaction_filter_proto protoreflect.FileDescriptor

const file_com_daml_ledger_api_v1_transaction_filter_proto_rawDesc = "" +
	"\n" +
	"/com/daml/ledger/api/v1/transaction_filter.proto\x12\x16com.daml.ledger.api.v1\x1a\"com/daml/ledger/api/v1/value.proto\"\xe0\x01\n" +
	"\x11TransactionFilter\x12g\n" +
	"\x10filters_by_party\x18\x01 \x03(\v2=.com.daml.ledger.api.v1.TransactionFilter.FiltersByPartyEntryR\x0efiltersByParty\x1ab\n" +
	"\x13FiltersByPartyEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x125\n" +
	"\x05value\x18\x02 \x01(\v2\x1f.com.daml.ledger.api.v1.FiltersR\x05value:\x028\x01\"Q\n" +
	"\aFilters\x12F\n" +
	"\tinclusive\x18\x01 \x01(\v2(.com.daml.ledger.api.v1.InclusiveFiltersR\tinclusive\"\x86\x02\n" +
	"\x10InclusiveFilters\x12I\n" +
	"\ftemplate_ids\x18\x01 \x03(\v2\".com.daml.ledger.api.v1.IdentifierB\x02\x18\x01R\vtemplateIds\x12T\n" +
	"\x11interface_filters\x18\x02 \x03(\v2'.com.daml.ledger.api.v1.InterfaceFilterR\x10interfaceFilters\x12Q\n" +
	"\x10template_filters\x18\x03 \x03(\v2&.com.daml.ledger.api.v1.TemplateFilterR\x0ftemplateFilters\"\xd1\x01\n" +
	"\x0fInterfaceFilter\x12E\n" +
	"\finterface_id\x18\x01 \x01(\v2\".com.daml.ledger.api.v1.IdentifierR\vinterfaceId\x124\n" +
	"\x16include_interface_view\x18\x02 \x01(\bR\x14includeInterfaceView\x12;\n" +
	"\x1ainclude_created_event_blob\x18\x04 \x01(\bR\x17includeCreatedEventBlobJ\x04\b\x03\x10\x04\"\x92\x01\n" +
	"\x0eTemplateFilter\x12C\n" +
	"\vtemplate_id\x18\x01 \x01(\v2\".com.daml.ledger.api.v1.IdentifierR\n" +
	"templateId\x12;\n" +
	"\x1ainclude_created_event_blob\x18\x02 \x01(\bR\x17includeCreatedEventBlobB\x89\x01\n" +
	"\x16com.daml.ledger.api.v1B\x1bTransactionFilterOuterClassZ9github.com/chainsafe/canton-middleware/pkg/canton/lapi/v1\xaa\x02\x16Com.Daml.Ledger.Api.V1b\x06proto3"

var (
	file_com_daml_ledger_api_v1_transaction_filter_proto_rawDescOnce sync.Once
	file_com_daml_ledger_api_v1_transaction_filter_proto_rawDescData []byte
)

func file_com_daml_ledger_api_v1_transaction_filter_proto_rawDescGZIP() []byte {
	file_com_daml_ledger_api_v1_transaction_filter_proto_rawDescOnce.Do(func() {
		file_com_daml_ledger_api_v1_transaction_filter_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_com_daml_ledger_api_v1_transaction_filter_proto_rawDesc), len(file_com_daml_ledger_api_v1_transaction_filter_proto_rawDesc)))
	})
	return file_com_daml_ledger_api_v1_transaction_filter_proto_rawDescData
}

var file_com_daml_ledger_api_v1_transaction_filter_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_com_daml_ledger_api_v1_transaction_filter_proto_goTypes = []any{
	(*TransactionFilter)(nil), // 0: com.daml.ledger.api.v1.TransactionFilter
	(*Filters)(nil),           // 1: com.daml.ledger.api.v1.Filters
	(*InclusiveFilters)(nil),  // 2: com.daml.ledger.api.v1.InclusiveFilters
	(*InterfaceFilter)(nil),   // 3: com.daml.ledger.api.v1.InterfaceFilter
	(*TemplateFilter)(nil),    // 4: com.daml.ledger.api.v1.TemplateFilter
	nil,                       // 5: com.daml.ledger.api.v1.TransactionFilter.FiltersByPartyEntry
	(*Identifier)(nil),        // 6: com.daml.ledger.api.v1.Identifier
}
var file_com_daml_ledger_api_v1_transaction_filter_proto_depIdxs = []int32{
	5, // 0: com.daml.ledger.api.v1.TransactionFilter.filters_by_party:type_name -> com.daml.ledger.api.v1.TransactionFilter.FiltersByPartyEntry
	2, // 1: com.daml.ledger.api.v1.Filters.inclusive:type_name -> com.daml.ledger.api.v1.InclusiveFilters
	6, // 2: com.daml.ledger.api.v1.InclusiveFilters.template_ids:type_name -> com.daml.ledger.api.v1.Identifier
	3, // 3: com.daml.ledger.api.v1.InclusiveFilters.interface_filters:type_name -> com.daml.ledger.api.v1.InterfaceFilter
	4, // 4: com.daml.ledger.api.v1.InclusiveFilters.template_filters:type_name -> com.daml.ledger.api.v1.TemplateFilter
	6, // 5: com.daml.ledger.api.v1.InterfaceFilter.interface_id:type_name -> com.daml.ledger.api.v1.Identifier
	6, // 6: com.daml.ledger.api.v1.TemplateFilter.template_id:type_name -> com.daml.ledger.api.v1.Identifier
	1, // 7: com.daml.ledger.api.v1.TransactionFilter.FiltersByPartyEntry.value:type_name -> com.daml.ledger.api.v1.Filters
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_com_daml_ledger_api_v1_transaction_filter_proto_init() }
func file_com_daml_ledger_api_v1_transaction_filter_proto_init() {
	if File_com_daml_ledger_api_v1_transaction_filter_proto != nil {
		return
	}
	file_com_daml_ledger_api_v1_value_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_com_daml_ledger_api_v1_transaction_filter_proto_rawDesc), len(file_com_daml_ledger_api_v1_transaction_filter_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_com_daml_ledger_api_v1_transaction_filter_proto_goTypes,
		DependencyIndexes: file_com_daml_ledger_api_v1_transaction_filter_proto_depIdxs,
		MessageInfos:      file_com_daml_ledger_api_v1_transaction_filter_proto_msgTypes,
	}.Build()
	File_com_daml_ledger_api_v1_transaction_filter_proto = out.File
	file_com_daml_ledger_api_v1_transaction_filter_proto_goTypes = nil
	file_com_daml_ledger_api_v1_transaction_filter_proto_depIdxs = nil
}
