// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	ethrpc "github.com/chainsafe/canton-middleware/pkg/ethrpc"
	mock "github.com/stretchr/testify/mock"
)

// Store is an autogenerated mock type for the Store type
type Store struct {
	mock.Mock
}

type Store_Expecter struct {
	mock *mock.Mock
}

func (_m *Store) EXPECT() *Store_Expecter {
	return &Store_Expecter{mock: &_m.Mock}
}

// CompleteMempoolEntry provides a mock function with given fields: ctx, txHash
func (_m *Store) CompleteMempoolEntry(ctx context.Context, txHash []byte) error {
	ret := _m.Called(ctx, txHash)

	if len(ret) == 0 {
		panic("no return value specified for CompleteMempoolEntry")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []byte) error); ok {
		r0 = rf(ctx, txHash)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Store_CompleteMempoolEntry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CompleteMempoolEntry'
type Store_CompleteMempoolEntry_Call struct {
	*mock.Call
}

// CompleteMempoolEntry is a helper method to define mock.On call
//   - ctx context.Context
//   - txHash []byte
func (_e *Store_Expecter) CompleteMempoolEntry(ctx interface{}, txHash interface{}) *Store_CompleteMempoolEntry_Call {
	return &Store_CompleteMempoolEntry_Call{Call: _e.mock.On("CompleteMempoolEntry", ctx, txHash)}
}

func (_c *Store_CompleteMempoolEntry_Call) Run(run func(ctx context.Context, txHash []byte)) *Store_CompleteMempoolEntry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]byte))
	})
	return _c
}

func (_c *Store_CompleteMempoolEntry_Call) Return(_a0 error) *Store_CompleteMempoolEntry_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Store_CompleteMempoolEntry_Call) RunAndReturn(run func(context.Context, []byte) error) *Store_CompleteMempoolEntry_Call {
	_c.Call.Return(run)
	return _c
}

// FailMempoolEntry provides a mock function with given fields: ctx, txHash, errMsg
func (_m *Store) FailMempoolEntry(ctx context.Context, txHash []byte, errMsg string) error {
	ret := _m.Called(ctx, txHash, errMsg)

	if len(ret) == 0 {
		panic("no return value specified for FailMempoolEntry")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []byte, string) error); ok {
		r0 = rf(ctx, txHash, errMsg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Store_FailMempoolEntry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FailMempoolEntry'
type Store_FailMempoolEntry_Call struct {
	*mock.Call
}

// FailMempoolEntry is a helper method to define mock.On call
//   - ctx context.Context
//   - txHash []byte
//   - errMsg string
func (_e *Store_Expecter) FailMempoolEntry(ctx interface{}, txHash interface{}, errMsg interface{}) *Store_FailMempoolEntry_Call {
	return &Store_FailMempoolEntry_Call{Call: _e.mock.On("FailMempoolEntry", ctx, txHash, errMsg)}
}

func (_c *Store_FailMempoolEntry_Call) Run(run func(ctx context.Context, txHash []byte, errMsg string)) *Store_FailMempoolEntry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]byte), args[2].(string))
	})
	return _c
}

func (_c *Store_FailMempoolEntry_Call) Return(_a0 error) *Store_FailMempoolEntry_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Store_FailMempoolEntry_Call) RunAndReturn(run func(context.Context, []byte, string) error) *Store_FailMempoolEntry_Call {
	_c.Call.Return(run)
	return _c
}

// GetMempoolEntriesByStatus provides a mock function with given fields: ctx, status, limit
func (_m *Store) GetMempoolEntriesByStatus(ctx context.Context, status ethrpc.MempoolStatus, limit int) ([]ethrpc.MempoolEntry, error) {
	ret := _m.Called(ctx, status, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetMempoolEntriesByStatus")
	}

	var r0 []ethrpc.MempoolEntry
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ethrpc.MempoolStatus, int) ([]ethrpc.MempoolEntry, error)); ok {
		return rf(ctx, status, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ethrpc.MempoolStatus, int) []ethrpc.MempoolEntry); ok {
		r0 = rf(ctx, status, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]ethrpc.MempoolEntry)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ethrpc.MempoolStatus, int) error); ok {
		r1 = rf(ctx, status, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store_GetMempoolEntriesByStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMempoolEntriesByStatus'
type Store_GetMempoolEntriesByStatus_Call struct {
	*mock.Call
}

// GetMempoolEntriesByStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - status ethrpc.MempoolStatus
//   - limit int
func (_e *Store_Expecter) GetMempoolEntriesByStatus(ctx interface{}, status interface{}, limit interface{}) *Store_GetMempoolEntriesByStatus_Call {
	return &Store_GetMempoolEntriesByStatus_Call{Call: _e.mock.On("GetMempoolEntriesByStatus", ctx, status, limit)}
}

func (_c *Store_GetMempoolEntriesByStatus_Call) Run(run func(ctx context.Context, status ethrpc.MempoolStatus, limit int)) *Store_GetMempoolEntriesByStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(ethrpc.MempoolStatus), args[2].(int))
	})
	return _c
}

func (_c *Store_GetMempoolEntriesByStatus_Call) Return(_a0 []ethrpc.MempoolEntry, _a1 error) *Store_GetMempoolEntriesByStatus_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Store_GetMempoolEntriesByStatus_Call) RunAndReturn(run func(context.Context, ethrpc.MempoolStatus, int) ([]ethrpc.MempoolEntry, error)) *Store_GetMempoolEntriesByStatus_Call {
	_c.Call.Return(run)
	return _c
}

// NewStore creates a new instance of Store. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *Store {
	mock := &Store{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
