// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	token "github.com/chainsafe/canton-middleware/pkg/token"
	mock "github.com/stretchr/testify/mock"
)

// ListService is an autogenerated mock type for the ListService type
type ListService struct {
	mock.Mock
}

type ListService_Expecter struct {
	mock *mock.Mock
}

func (_m *ListService) EXPECT() *ListService_Expecter {
	return &ListService_Expecter{mock: &_m.Mock}
}

// GetSupportedTokens provides a mock function with given fields: ctx, page, limit
func (_m *ListService) GetSupportedTokens(ctx context.Context, page int, limit int) (*token.TokensPage, error) {
	ret := _m.Called(ctx, page, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetSupportedTokens")
	}

	var r0 *token.TokensPage
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) (*token.TokensPage, error)); ok {
		return rf(ctx, page, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) *token.TokensPage); ok {
		r0 = rf(ctx, page, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*token.TokensPage)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = rf(ctx, page, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListService_GetSupportedTokens_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSupportedTokens'
type ListService_GetSupportedTokens_Call struct {
	*mock.Call
}

// GetSupportedTokens is a helper method to define mock.On call
//   - ctx context.Context
//   - page int
//   - limit int
func (_e *ListService_Expecter) GetSupportedTokens(ctx interface{}, page interface{}, limit interface{}) *ListService_GetSupportedTokens_Call {
	return &ListService_GetSupportedTokens_Call{Call: _e.mock.On("GetSupportedTokens", ctx, page, limit)}
}

func (_c *ListService_GetSupportedTokens_Call) Run(run func(ctx context.Context, page int, limit int)) *ListService_GetSupportedTokens_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *ListService_GetSupportedTokens_Call) Return(_a0 *token.TokensPage, _a1 error) *ListService_GetSupportedTokens_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ListService_GetSupportedTokens_Call) RunAndReturn(run func(context.Context, int, int) (*token.TokensPage, error)) *ListService_GetSupportedTokens_Call {
	_c.Call.Return(run)
	return _c
}

// NewListService creates a new instance of ListService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewListService(t interface {
	mock.TestingT
	Cleanup(func())
}) *ListService {
	mock := &ListService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
