// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	token "github.com/chainsafe/canton-middleware/pkg/token"
	mock "github.com/stretchr/testify/mock"

	user "github.com/chainsafe/canton-middleware/pkg/user"
)

// UserStore is an autogenerated mock type for the UserStore type
type UserStore struct {
	mock.Mock
}

type UserStore_Expecter struct {
	mock *mock.Mock
}

func (_m *UserStore) EXPECT() *UserStore_Expecter {
	return &UserStore_Expecter{mock: &_m.Mock}
}

// GetUserByCantonPartyID provides a mock function with given fields: ctx, partyID
func (_m *UserStore) GetUserByCantonPartyID(ctx context.Context, partyID string) (*user.User, error) {
	ret := _m.Called(ctx, partyID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByCantonPartyID")
	}

	var r0 *user.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*user.User, error)); ok {
		return rf(ctx, partyID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *user.User); ok {
		r0 = rf(ctx, partyID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, partyID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserStore_GetUserByCantonPartyID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByCantonPartyID'
type UserStore_GetUserByCantonPartyID_Call struct {
	*mock.Call
}

// GetUserByCantonPartyID is a helper method to define mock.On call
//   - ctx context.Context
//   - partyID string
func (_e *UserStore_Expecter) GetUserByCantonPartyID(ctx interface{}, partyID interface{}) *UserStore_GetUserByCantonPartyID_Call {
	return &UserStore_GetUserByCantonPartyID_Call{Call: _e.mock.On("GetUserByCantonPartyID", ctx, partyID)}
}

func (_c *UserStore_GetUserByCantonPartyID_Call) Run(run func(ctx context.Context, partyID string)) *UserStore_GetUserByCantonPartyID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *UserStore_GetUserByCantonPartyID_Call) Return(_a0 *user.User, _a1 error) *UserStore_GetUserByCantonPartyID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserStore_GetUserByCantonPartyID_Call) RunAndReturn(run func(context.Context, string) (*user.User, error)) *UserStore_GetUserByCantonPartyID_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByEVMAddress provides a mock function with given fields: ctx, evmAddress
func (_m *UserStore) GetUserByEVMAddress(ctx context.Context, evmAddress string) (*user.User, error) {
	ret := _m.Called(ctx, evmAddress)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByEVMAddress")
	}

	var r0 *user.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*user.User, error)); ok {
		return rf(ctx, evmAddress)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *user.User); ok {
		r0 = rf(ctx, evmAddress)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, evmAddress)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserStore_GetUserByEVMAddress_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByEVMAddress'
type UserStore_GetUserByEVMAddress_Call struct {
	*mock.Call
}

// GetUserByEVMAddress is a helper method to define mock.On call
//   - ctx context.Context
//   - evmAddress string
func (_e *UserStore_Expecter) GetUserByEVMAddress(ctx interface{}, evmAddress interface{}) *UserStore_GetUserByEVMAddress_Call {
	return &UserStore_GetUserByEVMAddress_Call{Call: _e.mock.On("GetUserByEVMAddress", ctx, evmAddress)}
}

func (_c *UserStore_GetUserByEVMAddress_Call) Run(run func(ctx context.Context, evmAddress string)) *UserStore_GetUserByEVMAddress_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *UserStore_GetUserByEVMAddress_Call) Return(_a0 *user.User, _a1 error) *UserStore_GetUserByEVMAddress_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserStore_GetUserByEVMAddress_Call) RunAndReturn(run func(context.Context, string) (*user.User, error)) *UserStore_GetUserByEVMAddress_Call {
	_c.Call.Return(run)
	return _c
}

// TransferBalanceByFingerprint provides a mock function with given fields: ctx, fromFingerprint, toFingerprint, amount, tokenType
func (_m *UserStore) TransferBalanceByFingerprint(ctx context.Context, fromFingerprint string, toFingerprint string, amount string, tokenType token.Type) error {
	ret := _m.Called(ctx, fromFingerprint, toFingerprint, amount, tokenType)

	if len(ret) == 0 {
		panic("no return value specified for TransferBalanceByFingerprint")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, token.Type) error); ok {
		r0 = rf(ctx, fromFingerprint, toFingerprint, amount, tokenType)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UserStore_TransferBalanceByFingerprint_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TransferBalanceByFingerprint'
type UserStore_TransferBalanceByFingerprint_Call struct {
	*mock.Call
}

// TransferBalanceByFingerprint is a helper method to define mock.On call
//   - ctx context.Context
//   - fromFingerprint string
//   - toFingerprint string
//   - amount string
//   - tokenType token.Type
func (_e *UserStore_Expecter) TransferBalanceByFingerprint(ctx interface{}, fromFingerprint interface{}, toFingerprint interface{}, amount interface{}, tokenType interface{}) *UserStore_TransferBalanceByFingerprint_Call {
	return &UserStore_TransferBalanceByFingerprint_Call{Call: _e.mock.On("TransferBalanceByFingerprint", ctx, fromFingerprint, toFingerprint, amount, tokenType)}
}

func (_c *UserStore_TransferBalanceByFingerprint_Call) Run(run func(ctx context.Context, fromFingerprint string, toFingerprint string, amount string, tokenType token.Type)) *UserStore_TransferBalanceByFingerprint_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(token.Type))
	})
	return _c
}

func (_c *UserStore_TransferBalanceByFingerprint_Call) Return(_a0 error) *UserStore_TransferBalanceByFingerprint_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *UserStore_TransferBalanceByFingerprint_Call) RunAndReturn(run func(context.Context, string, string, string, token.Type) error) *UserStore_TransferBalanceByFingerprint_Call {
	_c.Call.Return(run)
	return _c
}

// NewUserStore creates a new instance of UserStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserStore {
	mock := &UserStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
