// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	relayer "github.com/chainsafe/canton-middleware/pkg/relayer"
)

// Source is an autogenerated mock type for the Source type
type Source struct {
	mock.Mock
}

type Source_Expecter struct {
	mock *mock.Mock
}

func (_m *Source) EXPECT() *Source_Expecter {
	return &Source_Expecter{mock: &_m.Mock}
}

// ExtractOffset provides a mock function with given fields: event
func (_m *Source) ExtractOffset(event *relayer.Event) string {
	ret := _m.Called(event)

	if len(ret) == 0 {
		panic("no return value specified for ExtractOffset")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(*relayer.Event) string); ok {
		r0 = rf(event)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Source_ExtractOffset_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExtractOffset'
type Source_ExtractOffset_Call struct {
	*mock.Call
}

// ExtractOffset is a helper method to define mock.On call
//   - event *relayer.Event
func (_e *Source_Expecter) ExtractOffset(event interface{}) *Source_ExtractOffset_Call {
	return &Source_ExtractOffset_Call{Call: _e.mock.On("ExtractOffset", event)}
}

func (_c *Source_ExtractOffset_Call) Run(run func(event *relayer.Event)) *Source_ExtractOffset_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*relayer.Event))
	})
	return _c
}

func (_c *Source_ExtractOffset_Call) Return(_a0 string) *Source_ExtractOffset_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Source_ExtractOffset_Call) RunAndReturn(run func(*relayer.Event) string) *Source_ExtractOffset_Call {
	_c.Call.Return(run)
	return _c
}

// GetChainID provides a mock function with no fields
func (_m *Source) GetChainID() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetChainID")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Source_GetChainID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetChainID'
type Source_GetChainID_Call struct {
	*mock.Call
}

// GetChainID is a helper method to define mock.On call
func (_e *Source_Expecter) GetChainID() *Source_GetChainID_Call {
	return &Source_GetChainID_Call{Call: _e.mock.On("GetChainID")}
}

func (_c *Source_GetChainID_Call) Run(run func()) *Source_GetChainID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Source_GetChainID_Call) Return(_a0 string) *Source_GetChainID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Source_GetChainID_Call) RunAndReturn(run func() string) *Source_GetChainID_Call {
	_c.Call.Return(run)
	return _c
}

// StreamEvents provides a mock function with given fields: ctx, offset
func (_m *Source) StreamEvents(ctx context.Context, offset string) (<-chan *relayer.Event, <-chan error) {
	ret := _m.Called(ctx, offset)

	if len(ret) == 0 {
		panic("no return value specified for StreamEvents")
	}

	var r0 <-chan *relayer.Event
	var r1 <-chan error
	if rf, ok := ret.Get(0).(func(context.Context, string) (<-chan *relayer.Event, <-chan error)); ok {
		return rf(ctx, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) <-chan *relayer.Event); ok {
		r0 = rf(ctx, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan *relayer.Event)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) <-chan error); ok {
		r1 = rf(ctx, offset)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(<-chan error)
		}
	}

	return r0, r1
}

// Source_StreamEvents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StreamEvents'
type Source_StreamEvents_Call struct {
	*mock.Call
}

// StreamEvents is a helper method to define mock.On call
//   - ctx context.Context
//   - offset string
func (_e *Source_Expecter) StreamEvents(ctx interface{}, offset interface{}) *Source_StreamEvents_Call {
	return &Source_StreamEvents_Call{Call: _e.mock.On("StreamEvents", ctx, offset)}
}

func (_c *Source_StreamEvents_Call) Run(run func(ctx context.Context, offset string)) *Source_StreamEvents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Source_StreamEvents_Call) Return(_a0 <-chan *relayer.Event, _a1 <-chan error) *Source_StreamEvents_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Source_StreamEvents_Call) RunAndReturn(run func(context.Context, string) (<-chan *relayer.Event, <-chan error)) *Source_StreamEvents_Call {
	_c.Call.Return(run)
	return _c
}

// NewSource creates a new instance of Source. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSource(t interface {
	mock.TestingT
	Cleanup(func())
}) *Source {
	mock := &Source{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
