// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	relayer "github.com/chainsafe/canton-middleware/pkg/relayer"
)

// Destination is an autogenerated mock type for the Destination type
type Destination struct {
	mock.Mock
}

type Destination_Expecter struct {
	mock *mock.Mock
}

func (_m *Destination) EXPECT() *Destination_Expecter {
	return &Destination_Expecter{mock: &_m.Mock}
}

// GetChainID provides a mock function with no fields
func (_m *Destination) GetChainID() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetChainID")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Destination_GetChainID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetChainID'
type Destination_GetChainID_Call struct {
	*mock.Call
}

// GetChainID is a helper method to define mock.On call
func (_e *Destination_Expecter) GetChainID() *Destination_GetChainID_Call {
	return &Destination_GetChainID_Call{Call: _e.mock.On("GetChainID")}
}

func (_c *Destination_GetChainID_Call) Run(run func()) *Destination_GetChainID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Destination_GetChainID_Call) Return(_a0 string) *Destination_GetChainID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Destination_GetChainID_Call) RunAndReturn(run func() string) *Destination_GetChainID_Call {
	_c.Call.Return(run)
	return _c
}

// SubmitTransfer provides a mock function with given fields: ctx, event
func (_m *Destination) SubmitTransfer(ctx context.Context, event *relayer.Event) (string, bool, error) {
	ret := _m.Called(ctx, event)

	if len(ret) == 0 {
		panic("no return value specified for SubmitTransfer")
	}

	var r0 string
	var r1 bool
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, *relayer.Event) (string, bool, error)); ok {
		return rf(ctx, event)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *relayer.Event) string); ok {
		r0 = rf(ctx, event)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *relayer.Event) bool); ok {
		r1 = rf(ctx, event)
	} else {
		r1 = ret.Get(1).(bool)
	}

	if rf, ok := ret.Get(2).(func(context.Context, *relayer.Event) error); ok {
		r2 = rf(ctx, event)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Destination_SubmitTransfer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SubmitTransfer'
type Destination_SubmitTransfer_Call struct {
	*mock.Call
}

// SubmitTransfer is a helper method to define mock.On call
//   - ctx context.Context
//   - event *relayer.Event
func (_e *Destination_Expecter) SubmitTransfer(ctx interface{}, event interface{}) *Destination_SubmitTransfer_Call {
	return &Destination_SubmitTransfer_Call{Call: _e.mock.On("SubmitTransfer", ctx, event)}
}

func (_c *Destination_SubmitTransfer_Call) Run(run func(ctx context.Context, event *relayer.Event)) *Destination_SubmitTransfer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*relayer.Event))
	})
	return _c
}

func (_c *Destination_SubmitTransfer_Call) Return(destTxHash string, skipped bool, err error) *Destination_SubmitTransfer_Call {
	_c.Call.Return(destTxHash, skipped, err)
	return _c
}

func (_c *Destination_SubmitTransfer_Call) RunAndReturn(run func(context.Context, *relayer.Event) (string, bool, error)) *Destination_SubmitTransfer_Call {
	_c.Call.Return(run)
	return _c
}

// NewDestination creates a new instance of Destination. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDestination(t interface {
	mock.TestingT
	Cleanup(func())
}) *Destination {
	mock := &Destination{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
