// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	bridge "github.com/chainsafe/canton-middleware/pkg/cantonsdk/bridge"

	mock "github.com/stretchr/testify/mock"
)

// CantonBridge is an autogenerated mock type for the CantonBridgeClient type
type CantonBridge struct {
	mock.Mock
}

type CantonBridge_Expecter struct {
	mock *mock.Mock
}

func (_m *CantonBridge) EXPECT() *CantonBridge_Expecter {
	return &CantonBridge_Expecter{mock: &_m.Mock}
}

// CompleteWithdrawal provides a mock function with given fields: ctx, req
func (_m *CantonBridge) CompleteWithdrawal(ctx context.Context, req bridge.CompleteWithdrawalRequest) error {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CompleteWithdrawal")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, bridge.CompleteWithdrawalRequest) error); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CantonBridge_CompleteWithdrawal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CompleteWithdrawal'
type CantonBridge_CompleteWithdrawal_Call struct {
	*mock.Call
}

// CompleteWithdrawal is a helper method to define mock.On call
//   - ctx context.Context
//   - req bridge.CompleteWithdrawalRequest
func (_e *CantonBridge_Expecter) CompleteWithdrawal(ctx interface{}, req interface{}) *CantonBridge_CompleteWithdrawal_Call {
	return &CantonBridge_CompleteWithdrawal_Call{Call: _e.mock.On("CompleteWithdrawal", ctx, req)}
}

func (_c *CantonBridge_CompleteWithdrawal_Call) Run(run func(ctx context.Context, req bridge.CompleteWithdrawalRequest)) *CantonBridge_CompleteWithdrawal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(bridge.CompleteWithdrawalRequest))
	})
	return _c
}

func (_c *CantonBridge_CompleteWithdrawal_Call) Return(_a0 error) *CantonBridge_CompleteWithdrawal_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CantonBridge_CompleteWithdrawal_Call) RunAndReturn(run func(context.Context, bridge.CompleteWithdrawalRequest) error) *CantonBridge_CompleteWithdrawal_Call {
	_c.Call.Return(run)
	return _c
}

// CreatePendingDeposit provides a mock function with given fields: ctx, req
func (_m *CantonBridge) CreatePendingDeposit(ctx context.Context, req bridge.CreatePendingDepositRequest) (*bridge.PendingDeposit, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreatePendingDeposit")
	}

	var r0 *bridge.PendingDeposit
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, bridge.CreatePendingDepositRequest) (*bridge.PendingDeposit, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, bridge.CreatePendingDepositRequest) *bridge.PendingDeposit); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*bridge.PendingDeposit)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, bridge.CreatePendingDepositRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CantonBridge_CreatePendingDeposit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreatePendingDeposit'
type CantonBridge_CreatePendingDeposit_Call struct {
	*mock.Call
}

// CreatePendingDeposit is a helper method to define mock.On call
//   - ctx context.Context
//   - req bridge.CreatePendingDepositRequest
func (_e *CantonBridge_Expecter) CreatePendingDeposit(ctx interface{}, req interface{}) *CantonBridge_CreatePendingDeposit_Call {
	return &CantonBridge_CreatePendingDeposit_Call{Call: _e.mock.On("CreatePendingDeposit", ctx, req)}
}

func (_c *CantonBridge_CreatePendingDeposit_Call) Run(run func(ctx context.Context, req bridge.CreatePendingDepositRequest)) *CantonBridge_CreatePendingDeposit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(bridge.CreatePendingDepositRequest))
	})
	return _c
}

func (_c *CantonBridge_CreatePendingDeposit_Call) Return(_a0 *bridge.PendingDeposit, _a1 error) *CantonBridge_CreatePendingDeposit_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CantonBridge_CreatePendingDeposit_Call) RunAndReturn(run func(context.Context, bridge.CreatePendingDepositRequest) (*bridge.PendingDeposit, error)) *CantonBridge_CreatePendingDeposit_Call {
	_c.Call.Return(run)
	return _c
}

// GetLatestLedgerOffset provides a mock function with given fields: ctx
func (_m *CantonBridge) GetLatestLedgerOffset(ctx context.Context) (int64, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetLatestLedgerOffset")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (int64, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) int64); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CantonBridge_GetLatestLedgerOffset_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLatestLedgerOffset'
type CantonBridge_GetLatestLedgerOffset_Call struct {
	*mock.Call
}

// GetLatestLedgerOffset is a helper method to define mock.On call
//   - ctx context.Context
func (_e *CantonBridge_Expecter) GetLatestLedgerOffset(ctx interface{}) *CantonBridge_GetLatestLedgerOffset_Call {
	return &CantonBridge_GetLatestLedgerOffset_Call{Call: _e.mock.On("GetLatestLedgerOffset", ctx)}
}

func (_c *CantonBridge_GetLatestLedgerOffset_Call) Run(run func(ctx context.Context)) *CantonBridge_GetLatestLedgerOffset_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *CantonBridge_GetLatestLedgerOffset_Call) Return(_a0 int64, _a1 error) *CantonBridge_GetLatestLedgerOffset_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CantonBridge_GetLatestLedgerOffset_Call) RunAndReturn(run func(context.Context) (int64, error)) *CantonBridge_GetLatestLedgerOffset_Call {
	_c.Call.Return(run)
	return _c
}

// GetWayfinderBridgeConfigCID provides a mock function with given fields: ctx
func (_m *CantonBridge) GetWayfinderBridgeConfigCID(ctx context.Context) (string, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetWayfinderBridgeConfigCID")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (string, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) string); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CantonBridge_GetWayfinderBridgeConfigCID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWayfinderBridgeConfigCID'
type CantonBridge_GetWayfinderBridgeConfigCID_Call struct {
	*mock.Call
}

// GetWayfinderBridgeConfigCID is a helper method to define mock.On call
//   - ctx context.Context
func (_e *CantonBridge_Expecter) GetWayfinderBridgeConfigCID(ctx interface{}) *CantonBridge_GetWayfinderBridgeConfigCID_Call {
	return &CantonBridge_GetWayfinderBridgeConfigCID_Call{Call: _e.mock.On("GetWayfinderBridgeConfigCID", ctx)}
}

func (_c *CantonBridge_GetWayfinderBridgeConfigCID_Call) Run(run func(ctx context.Context)) *CantonBridge_GetWayfinderBridgeConfigCID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *CantonBridge_GetWayfinderBridgeConfigCID_Call) Return(_a0 string, _a1 error) *CantonBridge_GetWayfinderBridgeConfigCID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CantonBridge_GetWayfinderBridgeConfigCID_Call) RunAndReturn(run func(context.Context) (string, error)) *CantonBridge_GetWayfinderBridgeConfigCID_Call {
	_c.Call.Return(run)
	return _c
}

// InitiateWithdrawal provides a mock function with given fields: ctx, req
func (_m *CantonBridge) InitiateWithdrawal(ctx context.Context, req bridge.InitiateWithdrawalRequest) (string, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for InitiateWithdrawal")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, bridge.InitiateWithdrawalRequest) (string, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, bridge.InitiateWithdrawalRequest) string); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, bridge.InitiateWithdrawalRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CantonBridge_InitiateWithdrawal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InitiateWithdrawal'
type CantonBridge_InitiateWithdrawal_Call struct {
	*mock.Call
}

// InitiateWithdrawal is a helper method to define mock.On call
//   - ctx context.Context
//   - req bridge.InitiateWithdrawalRequest
func (_e *CantonBridge_Expecter) InitiateWithdrawal(ctx interface{}, req interface{}) *CantonBridge_InitiateWithdrawal_Call {
	return &CantonBridge_InitiateWithdrawal_Call{Call: _e.mock.On("InitiateWithdrawal", ctx, req)}
}

func (_c *CantonBridge_InitiateWithdrawal_Call) Run(run func(ctx context.Context, req bridge.InitiateWithdrawalRequest)) *CantonBridge_InitiateWithdrawal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(bridge.InitiateWithdrawalRequest))
	})
	return _c
}

func (_c *CantonBridge_InitiateWithdrawal_Call) Return(_a0 string, _a1 error) *CantonBridge_InitiateWithdrawal_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CantonBridge_InitiateWithdrawal_Call) RunAndReturn(run func(context.Context, bridge.InitiateWithdrawalRequest) (string, error)) *CantonBridge_InitiateWithdrawal_Call {
	_c.Call.Return(run)
	return _c
}

// IsDepositProcessed provides a mock function with given fields: ctx, evmTxHash
func (_m *CantonBridge) IsDepositProcessed(ctx context.Context, evmTxHash string) (bool, error) {
	ret := _m.Called(ctx, evmTxHash)

	if len(ret) == 0 {
		panic("no return value specified for IsDepositProcessed")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, evmTxHash)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, evmTxHash)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, evmTxHash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CantonBridge_IsDepositProcessed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsDepositProcessed'
type CantonBridge_IsDepositProcessed_Call struct {
	*mock.Call
}

// IsDepositProcessed is a helper method to define mock.On call
//   - ctx context.Context
//   - evmTxHash string
func (_e *CantonBridge_Expecter) IsDepositProcessed(ctx interface{}, evmTxHash interface{}) *CantonBridge_IsDepositProcessed_Call {
	return &CantonBridge_IsDepositProcessed_Call{Call: _e.mock.On("IsDepositProcessed", ctx, evmTxHash)}
}

func (_c *CantonBridge_IsDepositProcessed_Call) Run(run func(ctx context.Context, evmTxHash string)) *CantonBridge_IsDepositProcessed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *CantonBridge_IsDepositProcessed_Call) Return(_a0 bool, _a1 error) *CantonBridge_IsDepositProcessed_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CantonBridge_IsDepositProcessed_Call) RunAndReturn(run func(context.Context, string) (bool, error)) *CantonBridge_IsDepositProcessed_Call {
	_c.Call.Return(run)
	return _c
}

// ProcessDepositAndMint provides a mock function with given fields: ctx, req
func (_m *CantonBridge) ProcessDepositAndMint(ctx context.Context, req bridge.ProcessDepositRequest) (*bridge.ProcessedDeposit, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for ProcessDepositAndMint")
	}

	var r0 *bridge.ProcessedDeposit
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, bridge.ProcessDepositRequest) (*bridge.ProcessedDeposit, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, bridge.ProcessDepositRequest) *bridge.ProcessedDeposit); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*bridge.ProcessedDeposit)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, bridge.ProcessDepositRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CantonBridge_ProcessDepositAndMint_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProcessDepositAndMint'
type CantonBridge_ProcessDepositAndMint_Call struct {
	*mock.Call
}

// ProcessDepositAndMint is a helper method to define mock.On call
//   - ctx context.Context
//   - req bridge.ProcessDepositRequest
func (_e *CantonBridge_Expecter) ProcessDepositAndMint(ctx interface{}, req interface{}) *CantonBridge_ProcessDepositAndMint_Call {
	return &CantonBridge_ProcessDepositAndMint_Call{Call: _e.mock.On("ProcessDepositAndMint", ctx, req)}
}

func (_c *CantonBridge_ProcessDepositAndMint_Call) Run(run func(ctx context.Context, req bridge.ProcessDepositRequest)) *CantonBridge_ProcessDepositAndMint_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(bridge.ProcessDepositRequest))
	})
	return _c
}

func (_c *CantonBridge_ProcessDepositAndMint_Call) Return(_a0 *bridge.ProcessedDeposit, _a1 error) *CantonBridge_ProcessDepositAndMint_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CantonBridge_ProcessDepositAndMint_Call) RunAndReturn(run func(context.Context, bridge.ProcessDepositRequest) (*bridge.ProcessedDeposit, error)) *CantonBridge_ProcessDepositAndMint_Call {
	_c.Call.Return(run)
	return _c
}

// StreamWithdrawalEvents provides a mock function with given fields: ctx, offset
func (_m *CantonBridge) StreamWithdrawalEvents(ctx context.Context, offset string) <-chan *bridge.WithdrawalEvent {
	ret := _m.Called(ctx, offset)

	if len(ret) == 0 {
		panic("no return value specified for StreamWithdrawalEvents")
	}

	var r0 <-chan *bridge.WithdrawalEvent
	if rf, ok := ret.Get(0).(func(context.Context, string) <-chan *bridge.WithdrawalEvent); ok {
		r0 = rf(ctx, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan *bridge.WithdrawalEvent)
		}
	}

	return r0
}

// CantonBridge_StreamWithdrawalEvents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StreamWithdrawalEvents'
type CantonBridge_StreamWithdrawalEvents_Call struct {
	*mock.Call
}

// StreamWithdrawalEvents is a helper method to define mock.On call
//   - ctx context.Context
//   - offset string
func (_e *CantonBridge_Expecter) StreamWithdrawalEvents(ctx interface{}, offset interface{}) *CantonBridge_StreamWithdrawalEvents_Call {
	return &CantonBridge_StreamWithdrawalEvents_Call{Call: _e.mock.On("StreamWithdrawalEvents", ctx, offset)}
}

func (_c *CantonBridge_StreamWithdrawalEvents_Call) Run(run func(ctx context.Context, offset string)) *CantonBridge_StreamWithdrawalEvents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *CantonBridge_StreamWithdrawalEvents_Call) Return(_a0 <-chan *bridge.WithdrawalEvent) *CantonBridge_StreamWithdrawalEvents_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CantonBridge_StreamWithdrawalEvents_Call) RunAndReturn(run func(context.Context, string) <-chan *bridge.WithdrawalEvent) *CantonBridge_StreamWithdrawalEvents_Call {
	_c.Call.Return(run)
	return _c
}

// NewCantonBridge creates a new instance of CantonBridge. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCantonBridge(t interface {
	mock.TestingT
	Cleanup(func())
}) *CantonBridge {
	mock := &CantonBridge{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
