// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	relayer "github.com/chainsafe/canton-middleware/pkg/relayer"
	mock "github.com/stretchr/testify/mock"
)

// TokenBridge is an autogenerated mock type for the TokenBridge type
type TokenBridge struct {
	mock.Mock
}

type TokenBridge_Expecter struct {
	mock *mock.Mock
}

func (_m *TokenBridge) EXPECT() *TokenBridge_Expecter {
	return &TokenBridge_Expecter{mock: &_m.Mock}
}

// Key provides a mock function with no fields
func (_m *TokenBridge) Key() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Key")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// TokenBridge_Key_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Key'
type TokenBridge_Key_Call struct {
	*mock.Call
}

// Key is a helper method to define mock.On call
func (_e *TokenBridge_Expecter) Key() *TokenBridge_Key_Call {
	return &TokenBridge_Key_Call{Call: _e.mock.On("Key")}
}

func (_c *TokenBridge_Key_Call) Run(run func()) *TokenBridge_Key_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *TokenBridge_Key_Call) Return(_a0 string) *TokenBridge_Key_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TokenBridge_Key_Call) RunAndReturn(run func() string) *TokenBridge_Key_Call {
	_c.Call.Return(run)
	return _c
}

// Sources provides a mock function with given fields: ctx
func (_m *TokenBridge) Sources(ctx context.Context) ([]relayer.Source, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Sources")
	}

	var r0 []relayer.Source
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]relayer.Source, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []relayer.Source); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]relayer.Source)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TokenBridge_Sources_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Sources'
type TokenBridge_Sources_Call struct {
	*mock.Call
}

// Sources is a helper method to define mock.On call
//   - ctx context.Context
func (_e *TokenBridge_Expecter) Sources(ctx interface{}) *TokenBridge_Sources_Call {
	return &TokenBridge_Sources_Call{Call: _e.mock.On("Sources", ctx)}
}

func (_c *TokenBridge_Sources_Call) Run(run func(ctx context.Context)) *TokenBridge_Sources_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *TokenBridge_Sources_Call) Return(_a0 []relayer.Source, _a1 error) *TokenBridge_Sources_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TokenBridge_Sources_Call) RunAndReturn(run func(context.Context) ([]relayer.Source, error)) *TokenBridge_Sources_Call {
	_c.Call.Return(run)
	return _c
}

// Step provides a mock function with given fields: ctx, t
func (_m *TokenBridge) Step(ctx context.Context, t *relayer.Transfer) (relayer.StepResult, error) {
	ret := _m.Called(ctx, t)

	if len(ret) == 0 {
		panic("no return value specified for Step")
	}

	var r0 relayer.StepResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *relayer.Transfer) (relayer.StepResult, error)); ok {
		return rf(ctx, t)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *relayer.Transfer) relayer.StepResult); ok {
		r0 = rf(ctx, t)
	} else {
		r0 = ret.Get(0).(relayer.StepResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *relayer.Transfer) error); ok {
		r1 = rf(ctx, t)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TokenBridge_Step_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Step'
type TokenBridge_Step_Call struct {
	*mock.Call
}

// Step is a helper method to define mock.On call
//   - ctx context.Context
//   - t *relayer.Transfer
func (_e *TokenBridge_Expecter) Step(ctx interface{}, t interface{}) *TokenBridge_Step_Call {
	return &TokenBridge_Step_Call{Call: _e.mock.On("Step", ctx, t)}
}

func (_c *TokenBridge_Step_Call) Run(run func(ctx context.Context, t *relayer.Transfer)) *TokenBridge_Step_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*relayer.Transfer))
	})
	return _c
}

func (_c *TokenBridge_Step_Call) Return(_a0 relayer.StepResult, _a1 error) *TokenBridge_Step_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TokenBridge_Step_Call) RunAndReturn(run func(context.Context, *relayer.Transfer) (relayer.StepResult, error)) *TokenBridge_Step_Call {
	_c.Call.Return(run)
	return _c
}

// NewTokenBridge creates a new instance of TokenBridge. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTokenBridge(t interface {
	mock.TestingT
	Cleanup(func())
}) *TokenBridge {
	mock := &TokenBridge{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
