// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	big "math/big"

	common "github.com/ethereum/go-ethereum/common"

	ethereum "github.com/chainsafe/canton-middleware/pkg/ethereum"

	mock "github.com/stretchr/testify/mock"
)

// EthereumBridgeClient is an autogenerated mock type for the EthereumBridgeClient type
type EthereumBridgeClient struct {
	mock.Mock
}

type EthereumBridgeClient_Expecter struct {
	mock *mock.Mock
}

func (_m *EthereumBridgeClient) EXPECT() *EthereumBridgeClient_Expecter {
	return &EthereumBridgeClient_Expecter{mock: &_m.Mock}
}

// GetLastScannedBlock provides a mock function with no fields
func (_m *EthereumBridgeClient) GetLastScannedBlock() uint64 {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetLastScannedBlock")
	}

	var r0 uint64
	if rf, ok := ret.Get(0).(func() uint64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(uint64)
	}

	return r0
}

// EthereumBridgeClient_GetLastScannedBlock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLastScannedBlock'
type EthereumBridgeClient_GetLastScannedBlock_Call struct {
	*mock.Call
}

// GetLastScannedBlock is a helper method to define mock.On call
func (_e *EthereumBridgeClient_Expecter) GetLastScannedBlock() *EthereumBridgeClient_GetLastScannedBlock_Call {
	return &EthereumBridgeClient_GetLastScannedBlock_Call{Call: _e.mock.On("GetLastScannedBlock")}
}

func (_c *EthereumBridgeClient_GetLastScannedBlock_Call) Run(run func()) *EthereumBridgeClient_GetLastScannedBlock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *EthereumBridgeClient_GetLastScannedBlock_Call) Return(_a0 uint64) *EthereumBridgeClient_GetLastScannedBlock_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *EthereumBridgeClient_GetLastScannedBlock_Call) RunAndReturn(run func() uint64) *EthereumBridgeClient_GetLastScannedBlock_Call {
	_c.Call.Return(run)
	return _c
}

// GetLatestBlockNumber provides a mock function with given fields: ctx
func (_m *EthereumBridgeClient) GetLatestBlockNumber(ctx context.Context) (uint64, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetLatestBlockNumber")
	}

	var r0 uint64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (uint64, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) uint64); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(uint64)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// EthereumBridgeClient_GetLatestBlockNumber_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLatestBlockNumber'
type EthereumBridgeClient_GetLatestBlockNumber_Call struct {
	*mock.Call
}

// GetLatestBlockNumber is a helper method to define mock.On call
//   - ctx context.Context
func (_e *EthereumBridgeClient_Expecter) GetLatestBlockNumber(ctx interface{}) *EthereumBridgeClient_GetLatestBlockNumber_Call {
	return &EthereumBridgeClient_GetLatestBlockNumber_Call{Call: _e.mock.On("GetLatestBlockNumber", ctx)}
}

func (_c *EthereumBridgeClient_GetLatestBlockNumber_Call) Run(run func(ctx context.Context)) *EthereumBridgeClient_GetLatestBlockNumber_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *EthereumBridgeClient_GetLatestBlockNumber_Call) Return(_a0 uint64, _a1 error) *EthereumBridgeClient_GetLatestBlockNumber_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *EthereumBridgeClient_GetLatestBlockNumber_Call) RunAndReturn(run func(context.Context) (uint64, error)) *EthereumBridgeClient_GetLatestBlockNumber_Call {
	_c.Call.Return(run)
	return _c
}

// IsWithdrawalProcessed provides a mock function with given fields: ctx, cantonTxHash
func (_m *EthereumBridgeClient) IsWithdrawalProcessed(ctx context.Context, cantonTxHash [32]byte) (bool, error) {
	ret := _m.Called(ctx, cantonTxHash)

	if len(ret) == 0 {
		panic("no return value specified for IsWithdrawalProcessed")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, [32]byte) (bool, error)); ok {
		return rf(ctx, cantonTxHash)
	}
	if rf, ok := ret.Get(0).(func(context.Context, [32]byte) bool); ok {
		r0 = rf(ctx, cantonTxHash)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, [32]byte) error); ok {
		r1 = rf(ctx, cantonTxHash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// EthereumBridgeClient_IsWithdrawalProcessed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsWithdrawalProcessed'
type EthereumBridgeClient_IsWithdrawalProcessed_Call struct {
	*mock.Call
}

// IsWithdrawalProcessed is a helper method to define mock.On call
//   - ctx context.Context
//   - cantonTxHash [32]byte
func (_e *EthereumBridgeClient_Expecter) IsWithdrawalProcessed(ctx interface{}, cantonTxHash interface{}) *EthereumBridgeClient_IsWithdrawalProcessed_Call {
	return &EthereumBridgeClient_IsWithdrawalProcessed_Call{Call: _e.mock.On("IsWithdrawalProcessed", ctx, cantonTxHash)}
}

func (_c *EthereumBridgeClient_IsWithdrawalProcessed_Call) Run(run func(ctx context.Context, cantonTxHash [32]byte)) *EthereumBridgeClient_IsWithdrawalProcessed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([32]byte))
	})
	return _c
}

func (_c *EthereumBridgeClient_IsWithdrawalProcessed_Call) Return(_a0 bool, _a1 error) *EthereumBridgeClient_IsWithdrawalProcessed_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *EthereumBridgeClient_IsWithdrawalProcessed_Call) RunAndReturn(run func(context.Context, [32]byte) (bool, error)) *EthereumBridgeClient_IsWithdrawalProcessed_Call {
	_c.Call.Return(run)
	return _c
}

// WatchDepositEvents provides a mock function with given fields: ctx, fromBlock, handler
func (_m *EthereumBridgeClient) WatchDepositEvents(ctx context.Context, fromBlock uint64, handler func(*ethereum.DepositEvent) error) error {
	ret := _m.Called(ctx, fromBlock, handler)

	if len(ret) == 0 {
		panic("no return value specified for WatchDepositEvents")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64, func(*ethereum.DepositEvent) error) error); ok {
		r0 = rf(ctx, fromBlock, handler)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// EthereumBridgeClient_WatchDepositEvents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WatchDepositEvents'
type EthereumBridgeClient_WatchDepositEvents_Call struct {
	*mock.Call
}

// WatchDepositEvents is a helper method to define mock.On call
//   - ctx context.Context
//   - fromBlock uint64
//   - handler func(*ethereum.DepositEvent) error
func (_e *EthereumBridgeClient_Expecter) WatchDepositEvents(ctx interface{}, fromBlock interface{}, handler interface{}) *EthereumBridgeClient_WatchDepositEvents_Call {
	return &EthereumBridgeClient_WatchDepositEvents_Call{Call: _e.mock.On("WatchDepositEvents", ctx, fromBlock, handler)}
}

func (_c *EthereumBridgeClient_WatchDepositEvents_Call) Run(run func(ctx context.Context, fromBlock uint64, handler func(*ethereum.DepositEvent) error)) *EthereumBridgeClient_WatchDepositEvents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64), args[2].(func(*ethereum.DepositEvent) error))
	})
	return _c
}

func (_c *EthereumBridgeClient_WatchDepositEvents_Call) Return(_a0 error) *EthereumBridgeClient_WatchDepositEvents_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *EthereumBridgeClient_WatchDepositEvents_Call) RunAndReturn(run func(context.Context, uint64, func(*ethereum.DepositEvent) error) error) *EthereumBridgeClient_WatchDepositEvents_Call {
	_c.Call.Return(run)
	return _c
}

// WithdrawFromCanton provides a mock function with given fields: ctx, token, recipient, amount, nonce, cantonTxHash
func (_m *EthereumBridgeClient) WithdrawFromCanton(ctx context.Context, token common.Address, recipient common.Address, amount *big.Int, nonce *big.Int, cantonTxHash [32]byte) (common.Hash, error) {
	ret := _m.Called(ctx, token, recipient, amount, nonce, cantonTxHash)

	if len(ret) == 0 {
		panic("no return value specified for WithdrawFromCanton")
	}

	var r0 common.Hash
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, common.Address, common.Address, *big.Int, *big.Int, [32]byte) (common.Hash, error)); ok {
		return rf(ctx, token, recipient, amount, nonce, cantonTxHash)
	}
	if rf, ok := ret.Get(0).(func(context.Context, common.Address, common.Address, *big.Int, *big.Int, [32]byte) common.Hash); ok {
		r0 = rf(ctx, token, recipient, amount, nonce, cantonTxHash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(common.Hash)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, common.Address, common.Address, *big.Int, *big.Int, [32]byte) error); ok {
		r1 = rf(ctx, token, recipient, amount, nonce, cantonTxHash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// EthereumBridgeClient_WithdrawFromCanton_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithdrawFromCanton'
type EthereumBridgeClient_WithdrawFromCanton_Call struct {
	*mock.Call
}

// WithdrawFromCanton is a helper method to define mock.On call
//   - ctx context.Context
//   - token common.Address
//   - recipient common.Address
//   - amount *big.Int
//   - nonce *big.Int
//   - cantonTxHash [32]byte
func (_e *EthereumBridgeClient_Expecter) WithdrawFromCanton(ctx interface{}, token interface{}, recipient interface{}, amount interface{}, nonce interface{}, cantonTxHash interface{}) *EthereumBridgeClient_WithdrawFromCanton_Call {
	return &EthereumBridgeClient_WithdrawFromCanton_Call{Call: _e.mock.On("WithdrawFromCanton", ctx, token, recipient, amount, nonce, cantonTxHash)}
}

func (_c *EthereumBridgeClient_WithdrawFromCanton_Call) Run(run func(ctx context.Context, token common.Address, recipient common.Address, amount *big.Int, nonce *big.Int, cantonTxHash [32]byte)) *EthereumBridgeClient_WithdrawFromCanton_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(common.Address), args[2].(common.Address), args[3].(*big.Int), args[4].(*big.Int), args[5].([32]byte))
	})
	return _c
}

func (_c *EthereumBridgeClient_WithdrawFromCanton_Call) Return(_a0 common.Hash, _a1 error) *EthereumBridgeClient_WithdrawFromCanton_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *EthereumBridgeClient_WithdrawFromCanton_Call) RunAndReturn(run func(context.Context, common.Address, common.Address, *big.Int, *big.Int, [32]byte) (common.Hash, error)) *EthereumBridgeClient_WithdrawFromCanton_Call {
	_c.Call.Return(run)
	return _c
}

// NewEthereumBridgeClient creates a new instance of EthereumBridgeClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEthereumBridgeClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *EthereumBridgeClient {
	mock := &EthereumBridgeClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
