// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	relayer "github.com/chainsafe/canton-middleware/pkg/relayer"
	mock "github.com/stretchr/testify/mock"
)

// BridgeStore is an autogenerated mock type for the BridgeStore type
type BridgeStore struct {
	mock.Mock
}

type BridgeStore_Expecter struct {
	mock *mock.Mock
}

func (_m *BridgeStore) EXPECT() *BridgeStore_Expecter {
	return &BridgeStore_Expecter{mock: &_m.Mock}
}

// CreateTransfer provides a mock function with given fields: ctx, transfer
func (_m *BridgeStore) CreateTransfer(ctx context.Context, transfer *relayer.Transfer) (bool, error) {
	ret := _m.Called(ctx, transfer)

	if len(ret) == 0 {
		panic("no return value specified for CreateTransfer")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *relayer.Transfer) (bool, error)); ok {
		return rf(ctx, transfer)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *relayer.Transfer) bool); ok {
		r0 = rf(ctx, transfer)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *relayer.Transfer) error); ok {
		r1 = rf(ctx, transfer)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// BridgeStore_CreateTransfer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTransfer'
type BridgeStore_CreateTransfer_Call struct {
	*mock.Call
}

// CreateTransfer is a helper method to define mock.On call
//   - ctx context.Context
//   - transfer *relayer.Transfer
func (_e *BridgeStore_Expecter) CreateTransfer(ctx interface{}, transfer interface{}) *BridgeStore_CreateTransfer_Call {
	return &BridgeStore_CreateTransfer_Call{Call: _e.mock.On("CreateTransfer", ctx, transfer)}
}

func (_c *BridgeStore_CreateTransfer_Call) Run(run func(ctx context.Context, transfer *relayer.Transfer)) *BridgeStore_CreateTransfer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*relayer.Transfer))
	})
	return _c
}

func (_c *BridgeStore_CreateTransfer_Call) Return(_a0 bool, _a1 error) *BridgeStore_CreateTransfer_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *BridgeStore_CreateTransfer_Call) RunAndReturn(run func(context.Context, *relayer.Transfer) (bool, error)) *BridgeStore_CreateTransfer_Call {
	_c.Call.Return(run)
	return _c
}

// GetChainState provides a mock function with given fields: ctx, chainID
func (_m *BridgeStore) GetChainState(ctx context.Context, chainID string) (*relayer.ChainState, error) {
	ret := _m.Called(ctx, chainID)

	if len(ret) == 0 {
		panic("no return value specified for GetChainState")
	}

	var r0 *relayer.ChainState
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*relayer.ChainState, error)); ok {
		return rf(ctx, chainID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *relayer.ChainState); ok {
		r0 = rf(ctx, chainID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*relayer.ChainState)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, chainID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// BridgeStore_GetChainState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetChainState'
type BridgeStore_GetChainState_Call struct {
	*mock.Call
}

// GetChainState is a helper method to define mock.On call
//   - ctx context.Context
//   - chainID string
func (_e *BridgeStore_Expecter) GetChainState(ctx interface{}, chainID interface{}) *BridgeStore_GetChainState_Call {
	return &BridgeStore_GetChainState_Call{Call: _e.mock.On("GetChainState", ctx, chainID)}
}

func (_c *BridgeStore_GetChainState_Call) Run(run func(ctx context.Context, chainID string)) *BridgeStore_GetChainState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *BridgeStore_GetChainState_Call) Return(_a0 *relayer.ChainState, _a1 error) *BridgeStore_GetChainState_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *BridgeStore_GetChainState_Call) RunAndReturn(run func(context.Context, string) (*relayer.ChainState, error)) *BridgeStore_GetChainState_Call {
	_c.Call.Return(run)
	return _c
}

// GetPendingTransfers provides a mock function with given fields: ctx, direction
func (_m *BridgeStore) GetPendingTransfers(ctx context.Context, direction relayer.TransferDirection) ([]*relayer.Transfer, error) {
	ret := _m.Called(ctx, direction)

	if len(ret) == 0 {
		panic("no return value specified for GetPendingTransfers")
	}

	var r0 []*relayer.Transfer
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, relayer.TransferDirection) ([]*relayer.Transfer, error)); ok {
		return rf(ctx, direction)
	}
	if rf, ok := ret.Get(0).(func(context.Context, relayer.TransferDirection) []*relayer.Transfer); ok {
		r0 = rf(ctx, direction)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*relayer.Transfer)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, relayer.TransferDirection) error); ok {
		r1 = rf(ctx, direction)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// BridgeStore_GetPendingTransfers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPendingTransfers'
type BridgeStore_GetPendingTransfers_Call struct {
	*mock.Call
}

// GetPendingTransfers is a helper method to define mock.On call
//   - ctx context.Context
//   - direction relayer.TransferDirection
func (_e *BridgeStore_Expecter) GetPendingTransfers(ctx interface{}, direction interface{}) *BridgeStore_GetPendingTransfers_Call {
	return &BridgeStore_GetPendingTransfers_Call{Call: _e.mock.On("GetPendingTransfers", ctx, direction)}
}

func (_c *BridgeStore_GetPendingTransfers_Call) Run(run func(ctx context.Context, direction relayer.TransferDirection)) *BridgeStore_GetPendingTransfers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(relayer.TransferDirection))
	})
	return _c
}

func (_c *BridgeStore_GetPendingTransfers_Call) Return(_a0 []*relayer.Transfer, _a1 error) *BridgeStore_GetPendingTransfers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *BridgeStore_GetPendingTransfers_Call) RunAndReturn(run func(context.Context, relayer.TransferDirection) ([]*relayer.Transfer, error)) *BridgeStore_GetPendingTransfers_Call {
	_c.Call.Return(run)
	return _c
}

// GetTransfer provides a mock function with given fields: ctx, id
func (_m *BridgeStore) GetTransfer(ctx context.Context, id string) (*relayer.Transfer, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetTransfer")
	}

	var r0 *relayer.Transfer
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*relayer.Transfer, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *relayer.Transfer); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*relayer.Transfer)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// BridgeStore_GetTransfer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTransfer'
type BridgeStore_GetTransfer_Call struct {
	*mock.Call
}

// GetTransfer is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *BridgeStore_Expecter) GetTransfer(ctx interface{}, id interface{}) *BridgeStore_GetTransfer_Call {
	return &BridgeStore_GetTransfer_Call{Call: _e.mock.On("GetTransfer", ctx, id)}
}

func (_c *BridgeStore_GetTransfer_Call) Run(run func(ctx context.Context, id string)) *BridgeStore_GetTransfer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *BridgeStore_GetTransfer_Call) Return(_a0 *relayer.Transfer, _a1 error) *BridgeStore_GetTransfer_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *BridgeStore_GetTransfer_Call) RunAndReturn(run func(context.Context, string) (*relayer.Transfer, error)) *BridgeStore_GetTransfer_Call {
	_c.Call.Return(run)
	return _c
}

// IncrementRetryCount provides a mock function with given fields: ctx, id
func (_m *BridgeStore) IncrementRetryCount(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for IncrementRetryCount")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// BridgeStore_IncrementRetryCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IncrementRetryCount'
type BridgeStore_IncrementRetryCount_Call struct {
	*mock.Call
}

// IncrementRetryCount is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *BridgeStore_Expecter) IncrementRetryCount(ctx interface{}, id interface{}) *BridgeStore_IncrementRetryCount_Call {
	return &BridgeStore_IncrementRetryCount_Call{Call: _e.mock.On("IncrementRetryCount", ctx, id)}
}

func (_c *BridgeStore_IncrementRetryCount_Call) Run(run func(ctx context.Context, id string)) *BridgeStore_IncrementRetryCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *BridgeStore_IncrementRetryCount_Call) Return(_a0 error) *BridgeStore_IncrementRetryCount_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *BridgeStore_IncrementRetryCount_Call) RunAndReturn(run func(context.Context, string) error) *BridgeStore_IncrementRetryCount_Call {
	_c.Call.Return(run)
	return _c
}

// ListTransfers provides a mock function with given fields: ctx, limit
func (_m *BridgeStore) ListTransfers(ctx context.Context, limit int) ([]*relayer.Transfer, error) {
	ret := _m.Called(ctx, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListTransfers")
	}

	var r0 []*relayer.Transfer
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) ([]*relayer.Transfer, error)); ok {
		return rf(ctx, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) []*relayer.Transfer); ok {
		r0 = rf(ctx, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*relayer.Transfer)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// BridgeStore_ListTransfers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTransfers'
type BridgeStore_ListTransfers_Call struct {
	*mock.Call
}

// ListTransfers is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
func (_e *BridgeStore_Expecter) ListTransfers(ctx interface{}, limit interface{}) *BridgeStore_ListTransfers_Call {
	return &BridgeStore_ListTransfers_Call{Call: _e.mock.On("ListTransfers", ctx, limit)}
}

func (_c *BridgeStore_ListTransfers_Call) Run(run func(ctx context.Context, limit int)) *BridgeStore_ListTransfers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *BridgeStore_ListTransfers_Call) Return(_a0 []*relayer.Transfer, _a1 error) *BridgeStore_ListTransfers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *BridgeStore_ListTransfers_Call) RunAndReturn(run func(context.Context, int) ([]*relayer.Transfer, error)) *BridgeStore_ListTransfers_Call {
	_c.Call.Return(run)
	return _c
}

// SetChainState provides a mock function with given fields: ctx, chainID, blockNumber, offset
func (_m *BridgeStore) SetChainState(ctx context.Context, chainID string, blockNumber int64, offset string) error {
	ret := _m.Called(ctx, chainID, blockNumber, offset)

	if len(ret) == 0 {
		panic("no return value specified for SetChainState")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int64, string) error); ok {
		r0 = rf(ctx, chainID, blockNumber, offset)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// BridgeStore_SetChainState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetChainState'
type BridgeStore_SetChainState_Call struct {
	*mock.Call
}

// SetChainState is a helper method to define mock.On call
//   - ctx context.Context
//   - chainID string
//   - blockNumber int64
//   - offset string
func (_e *BridgeStore_Expecter) SetChainState(ctx interface{}, chainID interface{}, blockNumber interface{}, offset interface{}) *BridgeStore_SetChainState_Call {
	return &BridgeStore_SetChainState_Call{Call: _e.mock.On("SetChainState", ctx, chainID, blockNumber, offset)}
}

func (_c *BridgeStore_SetChainState_Call) Run(run func(ctx context.Context, chainID string, blockNumber int64, offset string)) *BridgeStore_SetChainState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int64), args[3].(string))
	})
	return _c
}

func (_c *BridgeStore_SetChainState_Call) Return(_a0 error) *BridgeStore_SetChainState_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *BridgeStore_SetChainState_Call) RunAndReturn(run func(context.Context, string, int64, string) error) *BridgeStore_SetChainState_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateTransferStatus provides a mock function with given fields: ctx, id, status, destTxHash, errMsg
func (_m *BridgeStore) UpdateTransferStatus(ctx context.Context, id string, status relayer.TransferStatus, destTxHash *string, errMsg *string) error {
	ret := _m.Called(ctx, id, status, destTxHash, errMsg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTransferStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, relayer.TransferStatus, *string, *string) error); ok {
		r0 = rf(ctx, id, status, destTxHash, errMsg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// BridgeStore_UpdateTransferStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateTransferStatus'
type BridgeStore_UpdateTransferStatus_Call struct {
	*mock.Call
}

// UpdateTransferStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - status relayer.TransferStatus
//   - destTxHash *string
//   - errMsg *string
func (_e *BridgeStore_Expecter) UpdateTransferStatus(ctx interface{}, id interface{}, status interface{}, destTxHash interface{}, errMsg interface{}) *BridgeStore_UpdateTransferStatus_Call {
	return &BridgeStore_UpdateTransferStatus_Call{Call: _e.mock.On("UpdateTransferStatus", ctx, id, status, destTxHash, errMsg)}
}

func (_c *BridgeStore_UpdateTransferStatus_Call) Run(run func(ctx context.Context, id string, status relayer.TransferStatus, destTxHash *string, errMsg *string)) *BridgeStore_UpdateTransferStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(relayer.TransferStatus), args[3].(*string), args[4].(*string))
	})
	return _c
}

func (_c *BridgeStore_UpdateTransferStatus_Call) Return(_a0 error) *BridgeStore_UpdateTransferStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *BridgeStore_UpdateTransferStatus_Call) RunAndReturn(run func(context.Context, string, relayer.TransferStatus, *string, *string) error) *BridgeStore_UpdateTransferStatus_Call {
	_c.Call.Return(run)
	return _c
}

// NewBridgeStore creates a new instance of BridgeStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBridgeStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *BridgeStore {
	mock := &BridgeStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
