// Copyright (c) 2024 Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: com/daml/ledger/api/v2/participant_offset.proto

package v2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ParticipantOffset_ParticipantBoundary int32

const (
	// Refers to the first transaction.
	ParticipantOffset_PARTICIPANT_BEGIN ParticipantOffset_ParticipantBoundary = 0
	// Refers to the currently last transaction, which is a moving target.
	ParticipantOffset_PARTICIPANT_END ParticipantOffset_ParticipantBoundary = 1
)

// Enum value maps for ParticipantOffset_ParticipantBoundary.
var (
	ParticipantOffset_ParticipantBoundary_name = map[int32]string{
		0: "PARTICIPANT_BEGIN",
		1: "PARTICIPANT_END",
	}
	ParticipantOffset_ParticipantBoundary_value = map[string]int32{
		"PARTICIPANT_BEGIN": 0,
		"PARTICIPANT_END":   1,
	}
)

func (x ParticipantOffset_ParticipantBoundary) Enum() *ParticipantOffset_ParticipantBoundary {
	p := new(ParticipantOffset_ParticipantBoundary)
	*p = x
	return p
}

func (x ParticipantOffset_ParticipantBoundary) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ParticipantOffset_ParticipantBoundary) Descriptor() protoreflect.EnumDescriptor {
	return file_com_daml_ledger_api_v2_participant_offset_proto_enumTypes[0].Descriptor()
}

func (ParticipantOffset_ParticipantBoundary) Type() protoreflect.EnumType {
	return &file_com_daml_ledger_api_v2_participant_offset_proto_enumTypes[0]
}

func (x ParticipantOffset_ParticipantBoundary) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ParticipantOffset_ParticipantBoundary.Descriptor instead.
func (ParticipantOffset_ParticipantBoundary) EnumDescriptor() ([]byte, []int) {
	return file_com_daml_ledger_api_v2_participant_offset_proto_rawDescGZIP(), []int{0, 0}
}

// Describes a specific point on the participant. This is a participant local value:
// a participant offset is meaningful only in the context of its participant. Different
// participants may associate different offsets to the same change synchronized over a domain,
// and conversely, the same literal participant offset may refer to different changes on
// different participants.
//
// This is also a unique index of the changes which happened on the virtual shared ledger.
// Participant offset define an order, which is the same in which order the updates are
// visible as subscribing to the “UpdateService“. This ordering is also a fully causal
// ordering for one specific domain: for two updates synchronized by the same domain, the
// one with a bigger participant offset happened after than the one with a smaller participant
// offset. Please note this is not true for updates synchronized by a different domain.
// Accordingly, the participant offset order may deviate from the order of the changes
// on the virtual shared ledger.
//
// The Ledger API endpoints that take offsets allow to specify portions
// of the participant that are relevant for the client to read.
//
// Offsets returned by the Ledger API can be used as-is (e.g.
// to keep track of processed transactions and provide a restart
// point to use in case of need).
//
// The format of absolute offsets is opaque to the client: no
// client-side transformation of an offset is guaranteed
// to return a meaningful offset.
//
// The server implementation ensures internally that offsets
// are lexicographically comparable.
type ParticipantOffset struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*ParticipantOffset_Absolute
	//	*ParticipantOffset_Boundary
	Value         isParticipantOffset_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParticipantOffset) Reset() {
	*x = ParticipantOffset{}
	mi := &file_com_daml_ledger_api_v2_participant_offset_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParticipantOffset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParticipantOffset) ProtoMessage() {}

func (x *ParticipantOffset) ProtoReflect() protoreflect.Message {
	mi := &file_com_daml_ledger_api_v2_participant_offset_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParticipantOffset.ProtoReflect.Descriptor instead.
func (*ParticipantOffset) Descriptor() ([]byte, []int) {
	return file_com_daml_ledger_api_v2_participant_offset_proto_rawDescGZIP(), []int{0}
}

func (x *ParticipantOffset) GetValue() isParticipantOffset_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *ParticipantOffset) GetAbsolute() string {
	if x != nil {
		if x, ok := x.Value.(*ParticipantOffset_Absolute); ok {
			return x.Absolute
		}
	}
	return ""
}

func (x *ParticipantOffset) GetBoundary() ParticipantOffset_ParticipantBoundary {
	if x != nil {
		if x, ok := x.Value.(*ParticipantOffset_Boundary); ok {
			return x.Boundary
		}
	}
	return ParticipantOffset_PARTICIPANT_BEGIN
}

type isParticipantOffset_Value interface {
	isParticipantOffset_Value()
}

type ParticipantOffset_Absolute struct {
	// The format of this string is specific to the participant and opaque to the client.
	Absolute string `protobuf:"bytes,1,opt,name=absolute,proto3,oneof"`
}

type ParticipantOffset_Boundary struct {
	Boundary ParticipantOffset_ParticipantBoundary `protobuf:"varint,2,opt,name=boundary,proto3,enum=com.daml.ledger.api.v2.ParticipantOffset_ParticipantBoundary,oneof"`
}

func (*ParticipantOffset_Absolute) isParticipantOffset_Value() {}

func (*ParticipantOffset_Boundary) isParticipantOffset_Value() {}

var File_com_daml_ledger_api_v2_participant_offset_proto protoreflect.FileDescriptor

const file_com_daml_ledger_api_v2_participant_offset_proto_rawDesc = "" +
	"\n" +
	"/com/daml/ledger/api/v2/participant_offset.proto\x12\x16com.daml.ledger.api.v2\"\xda\x01\n" +
	"\x11ParticipantOffset\x12\x1c\n" +
	"\babsolute\x18\x01 \x01(\tH\x00R\babsolute\x12[\n" +
	"\bboundary\x18\x02 \x01(\x0e2=.com.daml.ledger.api.v2.ParticipantOffset.ParticipantBoundaryH\x00R\bboundary\"A\n" +
	"\x13ParticipantBoundary\x12\x15\n" +
	"\x11PARTICIPANT_BEGIN\x10\x00\x12\x13\n" +
	"\x0fPARTICIPANT_END\x10\x01B\a\n" +
	"\x05valueB\x89\x01\n" +
	"\x16com.daml.ledger.api.v2B\x1bParticipantOffsetOuterClassZ9github.com/chainsafe/canton-middleware/pkg/canton/lapi/v2\xaa\x02\x16Com.Daml.Ledger.Api.V2b\x06proto3"

var (
	file_com_daml_ledger_api_v2_participant_offset_proto_rawDescOnce sync.Once
	file_com_daml_ledger_api_v2_participant_offset_proto_rawDescData []byte
)

func file_com_daml_ledger_api_v2_participant_offset_proto_rawDescGZIP() []byte {
	file_com_daml_ledger_api_v2_participant_offset_proto_rawDescOnce.Do(func() {
		file_com_daml_ledger_api_v2_participant_offset_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_com_daml_ledger_api_v2_participant_offset_proto_rawDesc), len(file_com_daml_ledger_api_v2_participant_offset_proto_rawDesc)))
	})
	return file_com_daml_ledger_api_v2_participant_offset_proto_rawDescData
}

var file_com_daml_ledger_api_v2_participant_offset_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_com_daml_ledger_api_v2_participant_offset_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_com_daml_ledger_api_v2_participant_offset_proto_goTypes = []any{
	(ParticipantOffset_ParticipantBoundary)(0), // 0: com.daml.ledger.api.v2.ParticipantOffset.ParticipantBoundary
	(*ParticipantOffset)(nil),                  // 1: com.daml.ledger.api.v2.ParticipantOffset
}
var file_com_daml_ledger_api_v2_participant_offset_proto_depIdxs = []int32{
	0, // 0: com.daml.ledger.api.v2.ParticipantOffset.boundary:type_name -> com.daml.ledger.api.v2.ParticipantOffset.ParticipantBoundary
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_com_daml_ledger_api_v2_participant_offset_proto_init() }
func file_com_daml_ledger_api_v2_participant_offset_proto_init() {
	if File_com_daml_ledger_api_v2_participant_offset_proto != nil {
		return
	}
	file_com_daml_ledger_api_v2_participant_offset_proto_msgTypes[0].OneofWrappers = []any{
		(*ParticipantOffset_Absolute)(nil),
		(*ParticipantOffset_Boundary)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_com_daml_ledger_api_v2_participant_offset_proto_rawDesc), len(file_com_daml_ledger_api_v2_participant_offset_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_com_daml_ledger_api_v2_participant_offset_proto_goTypes,
		DependencyIndexes: file_com_daml_ledger_api_v2_participant_offset_proto_depIdxs,
		EnumInfos:         file_com_daml_ledger_api_v2_participant_offset_proto_enumTypes,
		MessageInfos:      file_com_daml_ledger_api_v2_participant_offset_proto_msgTypes,
	}.Build()
	File_com_daml_ledger_api_v2_participant_offset_proto = out.File
	file_com_daml_ledger_api_v2_participant_offset_proto_goTypes = nil
	file_com_daml_ledger_api_v2_participant_offset_proto_depIdxs = nil
}
