// Copyright (c) 2024 Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: com/daml/ledger/api/v2/transaction.proto

package v2

import (
	v1 "github.com/chainsafe/canton-middleware/pkg/canton/lapi/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Complete view of an on-ledger transaction.
type TransactionTree struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Assigned by the server. Useful for correlating logs.
	// Must be a valid LedgerString (as described in “value.proto“).
	// Required
	UpdateId string `protobuf:"bytes,1,opt,name=update_id,json=updateId,proto3" json:"update_id,omitempty"`
	// The ID of the command which resulted in this transaction. Missing for everyone except the submitting party.
	// Must be a valid LedgerString (as described in “value.proto“).
	// Optional
	CommandId string `protobuf:"bytes,2,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	// The workflow ID used in command submission. Only set if the “workflow_id“ for the command was set.
	// Must be a valid LedgerString (as described in “value.proto“).
	// Optional
	WorkflowId string `protobuf:"bytes,3,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	// Ledger effective time.
	// Required
	EffectiveAt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=effective_at,json=effectiveAt,proto3" json:"effective_at,omitempty"`
	// The absolute offset. The format of this field is described in “participant_offset.proto“.
	// Required
	Offset string `protobuf:"bytes,5,opt,name=offset,proto3" json:"offset,omitempty"`
	// Changes to the ledger that were caused by this transaction. Nodes of the transaction tree.
	// Each key be a valid LedgerString (as describe in “value.proto“).
	// Required
	EventsById map[string]*v1.TreeEvent `protobuf:"bytes,6,rep,name=events_by_id,json=eventsById,proto3" json:"events_by_id,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Roots of the transaction tree.
	// Each element must be a valid LedgerString (as describe in “value.proto“).
	// The elements are in the same order as the commands in the
	// corresponding Commands object that triggered this transaction.
	// Required
	RootEventIds []string `protobuf:"bytes,7,rep,name=root_event_ids,json=rootEventIds,proto3" json:"root_event_ids,omitempty"`
	// A valid domain ID.
	// Identifies the domain that synchronized the transaction.
	// Required
	DomainId string `protobuf:"bytes,8,opt,name=domain_id,json=domainId,proto3" json:"domain_id,omitempty"`
	// Optional; ledger api trace context
	//
	// The trace context transported in this message corresponds to the trace context supplied
	// by the client application in a HTTP2 header of the original command submission.
	// We typically use a header to transfer this type of information. Here we use message
	// body, because it is used in gRPC streams which do not support per message headers.
	// This field will be populated with the trace context contained in the original submission.
	// If that was not provided, a unique ledger-api-server generated trace context will be used
	// instead.
	TraceContext  *v1.TraceContext `protobuf:"bytes,9,opt,name=trace_context,json=traceContext,proto3" json:"trace_context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionTree) Reset() {
	*x = TransactionTree{}
	mi := &file_com_daml_ledger_api_v2_transaction_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionTree) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionTree) ProtoMessage() {}

func (x *TransactionTree) ProtoReflect() protoreflect.Message {
	mi := &file_com_daml_ledger_api_v2_transaction_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionTree.ProtoReflect.Descriptor instead.
func (*TransactionTree) Descriptor() ([]byte, []int) {
	return file_com_daml_ledger_api_v2_transaction_proto_rawDescGZIP(), []int{0}
}

func (x *TransactionTree) GetUpdateId() string {
	if x != nil {
		return x.UpdateId
	}
	return ""
}

func (x *TransactionTree) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *TransactionTree) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *TransactionTree) GetEffectiveAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EffectiveAt
	}
	return nil
}

func (x *TransactionTree) GetOffset() string {
	if x != nil {
		return x.Offset
	}
	return ""
}

func (x *TransactionTree) GetEventsById() map[string]*v1.TreeEvent {
	if x != nil {
		return x.EventsById
	}
	return nil
}

func (x *TransactionTree) GetRootEventIds() []string {
	if x != nil {
		return x.RootEventIds
	}
	return nil
}

func (x *TransactionTree) GetDomainId() string {
	if x != nil {
		return x.DomainId
	}
	return ""
}

func (x *TransactionTree) GetTraceContext() *v1.TraceContext {
	if x != nil {
		return x.TraceContext
	}
	return nil
}

// Filtered view of an on-ledger transaction's create and archive events.
type Transaction struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Assigned by the server. Useful for correlating logs.
	// Must be a valid LedgerString (as described in “value.proto“).
	// Required
	UpdateId string `protobuf:"bytes,1,opt,name=update_id,json=updateId,proto3" json:"update_id,omitempty"`
	// The ID of the command which resulted in this transaction. Missing for everyone except the submitting party.
	// Must be a valid LedgerString (as described in “value.proto“).
	// Optional
	CommandId string `protobuf:"bytes,2,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	// The workflow ID used in command submission.
	// Must be a valid LedgerString (as described in “value.proto“).
	// Optional
	WorkflowId string `protobuf:"bytes,3,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	// Ledger effective time.
	// Must be a valid LedgerString (as described in “value.proto“).
	// Required
	EffectiveAt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=effective_at,json=effectiveAt,proto3" json:"effective_at,omitempty"`
	// The collection of events.
	// Only contains “CreatedEvent“ or “ArchivedEvent“.
	// Required
	Events []*v1.Event `protobuf:"bytes,5,rep,name=events,proto3" json:"events,omitempty"`
	// The absolute offset. The format of this field is described in “participant_offset.proto“.
	// Required
	Offset string `protobuf:"bytes,6,opt,name=offset,proto3" json:"offset,omitempty"`
	// A valid domain ID.
	// Identifies the domain that synchronized the transaction.
	// Required
	DomainId string `protobuf:"bytes,7,opt,name=domain_id,json=domainId,proto3" json:"domain_id,omitempty"`
	// Optional; ledger api trace context
	//
	// The trace context transported in this message corresponds to the trace context supplied
	// by the client application in a HTTP2 header of the original command submission.
	// We typically use a header to transfer this type of information. Here we use message
	// body, because it is used in gRPC streams which do not support per message headers.
	// This field will be populated with the trace context contained in the original submission.
	// If that was not provided, a unique ledger-api-server generated trace context will be used
	// instead.
	TraceContext  *v1.TraceContext `protobuf:"bytes,8,opt,name=trace_context,json=traceContext,proto3" json:"trace_context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_com_daml_ledger_api_v2_transaction_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_com_daml_ledger_api_v2_transaction_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_com_daml_ledger_api_v2_transaction_proto_rawDescGZIP(), []int{1}
}

func (x *Transaction) GetUpdateId() string {
	if x != nil {
		return x.UpdateId
	}
	return ""
}

func (x *Transaction) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *Transaction) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *Transaction) GetEffectiveAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EffectiveAt
	}
	return nil
}

func (x *Transaction) GetEvents() []*v1.Event {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *Transaction) GetOffset() string {
	if x != nil {
		return x.Offset
	}
	return ""
}

func (x *Transaction) GetDomainId() string {
	if x != nil {
		return x.DomainId
	}
	return ""
}

func (x *Transaction) GetTraceContext() *v1.TraceContext {
	if x != nil {
		return x.TraceContext
	}
	return nil
}

var File_com_daml_ledger_api_v2_transaction_proto protoreflect.FileDescriptor

const file_com_daml_ledger_api_v2_transaction_proto_rawDesc = "" +
	"\n" +
	"(com/daml/ledger/api/v2/transaction.proto\x12\x16com.daml.ledger.api.v2\x1a\"com/daml/ledger/api/v1/event.proto\x1a*com/daml/ledger/api/v1/trace_context.proto\x1a(com/daml/ledger/api/v1/transaction.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x90\x04\n" +
	"\x0fTransactionTree\x12\x1b\n" +
	"\tupdate_id\x18\x01 \x01(\tR\bupdateId\x12\x1d\n" +
	"\n" +
	"command_id\x18\x02 \x01(\tR\tcommandId\x12\x1f\n" +
	"\vworkflow_id\x18\x03 \x01(\tR\n" +
	"workflowId\x12=\n" +
	"\feffective_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\veffectiveAt\x12\x16\n" +
	"\x06offset\x18\x05 \x01(\tR\x06offset\x12Y\n" +
	"\fevents_by_id\x18\x06 \x03(\v27.com.daml.ledger.api.v2.TransactionTree.EventsByIdEntryR\n" +
	"eventsById\x12$\n" +
	"\x0eroot_event_ids\x18\a \x03(\tR\frootEventIds\x12\x1b\n" +
	"\tdomain_id\x18\b \x01(\tR\bdomainId\x12I\n" +
	"\rtrace_context\x18\t \x01(\v2$.com.daml.ledger.api.v1.TraceContextR\ftraceContext\x1a`\n" +
	"\x0fEventsByIdEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x127\n" +
	"\x05value\x18\x02 \x01(\v2!.com.daml.ledger.api.v1.TreeEventR\x05value:\x028\x01\"\xe0\x02\n" +
	"\vTransaction\x12\x1b\n" +
	"\tupdate_id\x18\x01 \x01(\tR\bupdateId\x12\x1d\n" +
	"\n" +
	"command_id\x18\x02 \x01(\tR\tcommandId\x12\x1f\n" +
	"\vworkflow_id\x18\x03 \x01(\tR\n" +
	"workflowId\x12=\n" +
	"\feffective_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\veffectiveAt\x125\n" +
	"\x06events\x18\x05 \x03(\v2\x1d.com.daml.ledger.api.v1.EventR\x06events\x12\x16\n" +
	"\x06offset\x18\x06 \x01(\tR\x06offset\x12\x1b\n" +
	"\tdomain_id\x18\a \x01(\tR\bdomainId\x12I\n" +
	"\rtrace_context\x18\b \x01(\v2$.com.daml.ledger.api.v1.TraceContextR\ftraceContextB\x83\x01\n" +
	"\x16com.daml.ledger.api.v2B\x15TransactionOuterClassZ9github.com/chainsafe/canton-middleware/pkg/canton/lapi/v2\xaa\x02\x16Com.Daml.Ledger.Api.V2b\x06proto3"

var (
	file_com_daml_ledger_api_v2_transaction_proto_rawDescOnce sync.Once
	file_com_daml_ledger_api_v2_transaction_proto_rawDescData []byte
)

func file_com_daml_ledger_api_v2_transaction_proto_rawDescGZIP() []byte {
	file_com_daml_ledger_api_v2_transaction_proto_rawDescOnce.Do(func() {
		file_com_daml_ledger_api_v2_transaction_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_com_daml_ledger_api_v2_transaction_proto_rawDesc), len(file_com_daml_ledger_api_v2_transaction_proto_rawDesc)))
	})
	return file_com_daml_ledger_api_v2_transaction_proto_rawDescData
}

var file_com_daml_ledger_api_v2_transaction_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_com_daml_ledger_api_v2_transaction_proto_goTypes = []any{
	(*TransactionTree)(nil),       // 0: com.daml.ledger.api.v2.TransactionTree
	(*Transaction)(nil),           // 1: com.daml.ledger.api.v2.Transaction
	nil,                           // 2: com.daml.ledger.api.v2.TransactionTree.EventsByIdEntry
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
	(*v1.TraceContext)(nil),       // 4: com.daml.ledger.api.v1.TraceContext
	(*v1.Event)(nil),              // 5: com.daml.ledger.api.v1.Event
	(*v1.TreeEvent)(nil),          // 6: com.daml.ledger.api.v1.TreeEvent
}
var file_com_daml_ledger_api_v2_transaction_proto_depIdxs = []int32{
	3, // 0: com.daml.ledger.api.v2.TransactionTree.effective_at:type_name -> google.protobuf.Timestamp
	2, // 1: com.daml.ledger.api.v2.TransactionTree.events_by_id:type_name -> com.daml.ledger.api.v2.TransactionTree.EventsByIdEntry
	4, // 2: com.daml.ledger.api.v2.TransactionTree.trace_context:type_name -> com.daml.ledger.api.v1.TraceContext
	3, // 3: com.daml.ledger.api.v2.Transaction.effective_at:type_name -> google.protobuf.Timestamp
	5, // 4: com.daml.ledger.api.v2.Transaction.events:type_name -> com.daml.ledger.api.v1.Event
	4, // 5: com.daml.ledger.api.v2.Transaction.trace_context:type_name -> com.daml.ledger.api.v1.TraceContext
	6, // 6: com.daml.ledger.api.v2.TransactionTree.EventsByIdEntry.value:type_name -> com.daml.ledger.api.v1.TreeEvent
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_com_daml_ledger_api_v2_transaction_proto_init() }
func file_com_daml_ledger_api_v2_transaction_proto_init() {
	if File_com_daml_ledger_api_v2_transaction_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_com_daml_ledger_api_v2_transaction_proto_rawDesc), len(file_com_daml_ledger_api_v2_transaction_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_com_daml_ledger_api_v2_transaction_proto_goTypes,
		DependencyIndexes: file_com_daml_ledger_api_v2_transaction_proto_depIdxs,
		MessageInfos:      file_com_daml_ledger_api_v2_transaction_proto_msgTypes,
	}.Build()
	File_com_daml_ledger_api_v2_transaction_proto = out.File
	file_com_daml_ledger_api_v2_transaction_proto_goTypes = nil
	file_com_daml_ledger_api_v2_transaction_proto_depIdxs = nil
}
