// Copyright (c) 2024 Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: com/daml/ledger/api/v2/transaction_filter.proto

package v2

import (
	v1 "github.com/chainsafe/canton-middleware/pkg/canton/lapi/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A filter both for filtering create and archive events as well as for
// filtering transaction trees.
type TransactionFilter struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Each key must be a valid PartyIdString (as described in “value.proto“).
	// The interpretation of the filter depends on the stream being filtered:
	//
	//  1. For **transaction tree streams** all party keys used as wildcard filters, and all subtrees
	//     whose root has one of the listed parties as an informee are returned.
	//     If there are InclusiveFilters, those will control returned “CreatedEvent“ fields were applicable, but not
	//     used for template/interface filtering.
	//  2. For **transaction and active-contract-set streams** create and archive events are returned for all contracts whose
	//     stakeholders include at least one of the listed parties and match the
	//     per-party filter.
	//
	// Required
	FiltersByParty map[string]*v1.Filters `protobuf:"bytes,1,rep,name=filters_by_party,json=filtersByParty,proto3" json:"filters_by_party,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TransactionFilter) Reset() {
	*x = TransactionFilter{}
	mi := &file_com_daml_ledger_api_v2_transaction_filter_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionFilter) ProtoMessage() {}

func (x *TransactionFilter) ProtoReflect() protoreflect.Message {
	mi := &file_com_daml_ledger_api_v2_transaction_filter_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionFilter.ProtoReflect.Descriptor instead.
func (*TransactionFilter) Descriptor() ([]byte, []int) {
	return file_com_daml_ledger_api_v2_transaction_filter_proto_rawDescGZIP(), []int{0}
}

func (x *TransactionFilter) GetFiltersByParty() map[string]*v1.Filters {
	if x != nil {
		return x.FiltersByParty
	}
	return nil
}

var File_com_daml_ledger_api_v2_transaction_filter_proto protoreflect.FileDescriptor

const file_com_daml_ledger_api_v2_transaction_filter_proto_rawDesc = "" +
	"\n" +
	"/com/daml/ledger/api/v2/transaction_filter.proto\x12\x16com.daml.ledger.api.v2\x1a/com/daml/ledger/api/v1/transaction_filter.proto\"\xe0\x01\n" +
	"\x11TransactionFilter\x12g\n" +
	"\x10filters_by_party\x18\x01 \x03(\v2=.com.daml.ledger.api.v2.TransactionFilter.FiltersByPartyEntryR\x0efiltersByParty\x1ab\n" +
	"\x13FiltersByPartyEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x125\n" +
	"\x05value\x18\x02 \x01(\v2\x1f.com.daml.ledger.api.v1.FiltersR\x05value:\x028\x01B\x89\x01\n" +
	"\x16com.daml.ledger.api.v2B\x1bTransactionFilterOuterClassZ9github.com/chainsafe/canton-middleware/pkg/canton/lapi/v2\xaa\x02\x16Com.Daml.Ledger.Api.V2b\x06proto3"

var (
	file_com_daml_ledger_api_v2_transaction_filter_proto_rawDescOnce sync.Once
	file_com_daml_ledger_api_v2_transaction_filter_proto_rawDescData []byte
)

func file_com_daml_ledger_api_v2_transaction_filter_proto_rawDescGZIP() []byte {
	file_com_daml_ledger_api_v2_transaction_filter_proto_rawDescOnce.Do(func() {
		file_com_daml_ledger_api_v2_transaction_filter_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_com_daml_ledger_api_v2_transaction_filter_proto_rawDesc), len(file_com_daml_ledger_api_v2_transaction_filter_proto_rawDesc)))
	})
	return file_com_daml_ledger_api_v2_transaction_filter_proto_rawDescData
}

var file_com_daml_ledger_api_v2_transaction_filter_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_com_daml_ledger_api_v2_transaction_filter_proto_goTypes = []any{
	(*TransactionFilter)(nil), // 0: com.daml.ledger.api.v2.TransactionFilter
	nil,                       // 1: com.daml.ledger.api.v2.TransactionFilter.FiltersByPartyEntry
	(*v1.Filters)(nil),        // 2: com.daml.ledger.api.v1.Filters
}
var file_com_daml_ledger_api_v2_transaction_filter_proto_depIdxs = []int32{
	1, // 0: com.daml.ledger.api.v2.TransactionFilter.filters_by_party:type_name -> com.daml.ledger.api.v2.TransactionFilter.FiltersByPartyEntry
	2, // 1: com.daml.ledger.api.v2.TransactionFilter.FiltersByPartyEntry.value:type_name -> com.daml.ledger.api.v1.Filters
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_com_daml_ledger_api_v2_transaction_filter_proto_init() }
func file_com_daml_ledger_api_v2_transaction_filter_proto_init() {
	if File_com_daml_ledger_api_v2_transaction_filter_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_com_daml_ledger_api_v2_transaction_filter_proto_rawDesc), len(file_com_daml_ledger_api_v2_transaction_filter_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_com_daml_ledger_api_v2_transaction_filter_proto_goTypes,
		DependencyIndexes: file_com_daml_ledger_api_v2_transaction_filter_proto_depIdxs,
		MessageInfos:      file_com_daml_ledger_api_v2_transaction_filter_proto_msgTypes,
	}.Build()
	File_com_daml_ledger_api_v2_transaction_filter_proto = out.File
	file_com_daml_ledger_api_v2_transaction_filter_proto_goTypes = nil
	file_com_daml_ledger_api_v2_transaction_filter_proto_depIdxs = nil
}
