// Copyright (c) 2024 Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: com/daml/ledger/api/v2/update_service.proto

package v2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetUpdatesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Beginning of the requested ledger section.
	// The response will only contain transactions whose offset is strictly greater than this.
	// Required
	BeginExclusive *ParticipantOffset `protobuf:"bytes,1,opt,name=begin_exclusive,json=beginExclusive,proto3" json:"begin_exclusive,omitempty"`
	// End of the requested ledger section.
	// The response will only contain transactions whose offset is less than or equal to this.
	// Optional, if not set, the stream will not terminate.
	EndInclusive *ParticipantOffset `protobuf:"bytes,2,opt,name=end_inclusive,json=endInclusive,proto3" json:"end_inclusive,omitempty"`
	// Requesting parties with template filters.
	// Template filters must be empty for GetUpdateTrees requests.
	// Required
	Filter *TransactionFilter `protobuf:"bytes,3,opt,name=filter,proto3" json:"filter,omitempty"`
	// If enabled, values served over the API will contain more information than strictly necessary to interpret the data.
	// In particular, setting the verbose flag to true triggers the ledger to include labels, record and variant type ids
	// for record fields.
	// Optional
	Verbose bool `protobuf:"varint,4,opt,name=verbose,proto3" json:"verbose,omitempty"`
	// If set to true, the server will send responses containing pruned offset upon pruning completion.
	// Optional
	SendPrunedOffsets bool `protobuf:"varint,5,opt,name=send_pruned_offsets,json=sendPrunedOffsets,proto3" json:"send_pruned_offsets,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetUpdatesRequest) Reset() {
	*x = GetUpdatesRequest{}
	mi := &file_com_daml_ledger_api_v2_update_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUpdatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUpdatesRequest) ProtoMessage() {}

func (x *GetUpdatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_com_daml_ledger_api_v2_update_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUpdatesRequest.ProtoReflect.Descriptor instead.
func (*GetUpdatesRequest) Descriptor() ([]byte, []int) {
	return file_com_daml_ledger_api_v2_update_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetUpdatesRequest) GetBeginExclusive() *ParticipantOffset {
	if x != nil {
		return x.BeginExclusive
	}
	return nil
}

func (x *GetUpdatesRequest) GetEndInclusive() *ParticipantOffset {
	if x != nil {
		return x.EndInclusive
	}
	return nil
}

func (x *GetUpdatesRequest) GetFilter() *TransactionFilter {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *GetUpdatesRequest) GetVerbose() bool {
	if x != nil {
		return x.Verbose
	}
	return false
}

func (x *GetUpdatesRequest) GetSendPrunedOffsets() bool {
	if x != nil {
		return x.SendPrunedOffsets
	}
	return false
}

type GetUpdatesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The update that matches the filter in the request.
	//
	// Types that are valid to be assigned to Update:
	//
	//	*GetUpdatesResponse_Transaction
	//	*GetUpdatesResponse_Reassignment
	Update isGetUpdatesResponse_Update `protobuf_oneof:"update"`
	// Current pruned offset. It is sent when following three conditions are met:
	// - a pruning operation has completed
	// - the transaction stream tails the LEDGER_END
	// - the `send_pruned_offsets` field was set on the corresponding request.
	// The conditions for including the `pruned_offset` in messages may change in the future implementations.
	// When `pruned_offset` is set, the message does not contain any transactions in the transactions field.
	PrunedOffset  string `protobuf:"bytes,3,opt,name=pruned_offset,json=prunedOffset,proto3" json:"pruned_offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUpdatesResponse) Reset() {
	*x = GetUpdatesResponse{}
	mi := &file_com_daml_ledger_api_v2_update_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUpdatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUpdatesResponse) ProtoMessage() {}

func (x *GetUpdatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_com_daml_ledger_api_v2_update_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUpdatesResponse.ProtoReflect.Descriptor instead.
func (*GetUpdatesResponse) Descriptor() ([]byte, []int) {
	return file_com_daml_ledger_api_v2_update_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetUpdatesResponse) GetUpdate() isGetUpdatesResponse_Update {
	if x != nil {
		return x.Update
	}
	return nil
}

func (x *GetUpdatesResponse) GetTransaction() *Transaction {
	if x != nil {
		if x, ok := x.Update.(*GetUpdatesResponse_Transaction); ok {
			return x.Transaction
		}
	}
	return nil
}

func (x *GetUpdatesResponse) GetReassignment() *Reassignment {
	if x != nil {
		if x, ok := x.Update.(*GetUpdatesResponse_Reassignment); ok {
			return x.Reassignment
		}
	}
	return nil
}

func (x *GetUpdatesResponse) GetPrunedOffset() string {
	if x != nil {
		return x.PrunedOffset
	}
	return ""
}

type isGetUpdatesResponse_Update interface {
	isGetUpdatesResponse_Update()
}

type GetUpdatesResponse_Transaction struct {
	Transaction *Transaction `protobuf:"bytes,1,opt,name=transaction,proto3,oneof"`
}

type GetUpdatesResponse_Reassignment struct {
	Reassignment *Reassignment `protobuf:"bytes,2,opt,name=reassignment,proto3,oneof"`
}

func (*GetUpdatesResponse_Transaction) isGetUpdatesResponse_Update() {}

func (*GetUpdatesResponse_Reassignment) isGetUpdatesResponse_Update() {}

type GetUpdateTreesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The update that matches the filter in the request.
	//
	// Types that are valid to be assigned to Update:
	//
	//	*GetUpdateTreesResponse_TransactionTree
	//	*GetUpdateTreesResponse_Reassignment
	Update isGetUpdateTreesResponse_Update `protobuf_oneof:"update"`
	// Current pruned offset. It is sent when following three conditions are met:
	// - a pruning operation has completed
	// - the transaction stream tails the LEDGER_END
	// - the `send_pruned_offsets` field was set on the corresponding request.
	// The conditions for including the `pruned_offset` in messages may change in the future implementations.
	// When `pruned_offset` is set, the message does not contain any transactions in the transactions field.
	PrunedOffset  string `protobuf:"bytes,3,opt,name=pruned_offset,json=prunedOffset,proto3" json:"pruned_offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUpdateTreesResponse) Reset() {
	*x = GetUpdateTreesResponse{}
	mi := &file_com_daml_ledger_api_v2_update_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUpdateTreesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUpdateTreesResponse) ProtoMessage() {}

func (x *GetUpdateTreesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_com_daml_ledger_api_v2_update_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUpdateTreesResponse.ProtoReflect.Descriptor instead.
func (*GetUpdateTreesResponse) Descriptor() ([]byte, []int) {
	return file_com_daml_ledger_api_v2_update_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetUpdateTreesResponse) GetUpdate() isGetUpdateTreesResponse_Update {
	if x != nil {
		return x.Update
	}
	return nil
}

func (x *GetUpdateTreesResponse) GetTransactionTree() *TransactionTree {
	if x != nil {
		if x, ok := x.Update.(*GetUpdateTreesResponse_TransactionTree); ok {
			return x.TransactionTree
		}
	}
	return nil
}

func (x *GetUpdateTreesResponse) GetReassignment() *Reassignment {
	if x != nil {
		if x, ok := x.Update.(*GetUpdateTreesResponse_Reassignment); ok {
			return x.Reassignment
		}
	}
	return nil
}

func (x *GetUpdateTreesResponse) GetPrunedOffset() string {
	if x != nil {
		return x.PrunedOffset
	}
	return ""
}

type isGetUpdateTreesResponse_Update interface {
	isGetUpdateTreesResponse_Update()
}

type GetUpdateTreesResponse_TransactionTree struct {
	TransactionTree *TransactionTree `protobuf:"bytes,1,opt,name=transaction_tree,json=transactionTree,proto3,oneof"`
}

type GetUpdateTreesResponse_Reassignment struct {
	Reassignment *Reassignment `protobuf:"bytes,2,opt,name=reassignment,proto3,oneof"`
}

func (*GetUpdateTreesResponse_TransactionTree) isGetUpdateTreesResponse_Update() {}

func (*GetUpdateTreesResponse_Reassignment) isGetUpdateTreesResponse_Update() {}

type GetTransactionByEventIdRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The ID of a particular event.
	// Must be a valid LedgerString (as described in “value.proto“).
	// Required
	EventId string `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	// The parties whose events the client expects to see.
	// Events that are not visible for the parties in this collection will not be present in the response.
	// Each element must be a valid PartyIdString (as described in “value.proto“).
	// Required
	RequestingParties []string `protobuf:"bytes,2,rep,name=requesting_parties,json=requestingParties,proto3" json:"requesting_parties,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetTransactionByEventIdRequest) Reset() {
	*x = GetTransactionByEventIdRequest{}
	mi := &file_com_daml_ledger_api_v2_update_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionByEventIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionByEventIdRequest) ProtoMessage() {}

func (x *GetTransactionByEventIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_com_daml_ledger_api_v2_update_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionByEventIdRequest.ProtoReflect.Descriptor instead.
func (*GetTransactionByEventIdRequest) Descriptor() ([]byte, []int) {
	return file_com_daml_ledger_api_v2_update_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetTransactionByEventIdRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *GetTransactionByEventIdRequest) GetRequestingParties() []string {
	if x != nil {
		return x.RequestingParties
	}
	return nil
}

type GetTransactionByIdRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The ID of a particular transaction.
	// Must be a valid LedgerString (as describe in “value.proto“).
	// Required
	UpdateId string `protobuf:"bytes,1,opt,name=update_id,json=updateId,proto3" json:"update_id,omitempty"`
	// The parties whose events the client expects to see.
	// Events that are not visible for the parties in this collection will not be present in the response.
	// Each element be a valid PartyIdString (as describe in “value.proto“).
	// Required
	RequestingParties []string `protobuf:"bytes,2,rep,name=requesting_parties,json=requestingParties,proto3" json:"requesting_parties,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetTransactionByIdRequest) Reset() {
	*x = GetTransactionByIdRequest{}
	mi := &file_com_daml_ledger_api_v2_update_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionByIdRequest) ProtoMessage() {}

func (x *GetTransactionByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_com_daml_ledger_api_v2_update_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionByIdRequest.ProtoReflect.Descriptor instead.
func (*GetTransactionByIdRequest) Descriptor() ([]byte, []int) {
	return file_com_daml_ledger_api_v2_update_service_proto_rawDescGZIP(), []int{4}
}

func (x *GetTransactionByIdRequest) GetUpdateId() string {
	if x != nil {
		return x.UpdateId
	}
	return ""
}

func (x *GetTransactionByIdRequest) GetRequestingParties() []string {
	if x != nil {
		return x.RequestingParties
	}
	return nil
}

type GetTransactionTreeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required
	Transaction   *TransactionTree `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactionTreeResponse) Reset() {
	*x = GetTransactionTreeResponse{}
	mi := &file_com_daml_ledger_api_v2_update_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionTreeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionTreeResponse) ProtoMessage() {}

func (x *GetTransactionTreeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_com_daml_ledger_api_v2_update_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionTreeResponse.ProtoReflect.Descriptor instead.
func (*GetTransactionTreeResponse) Descriptor() ([]byte, []int) {
	return file_com_daml_ledger_api_v2_update_service_proto_rawDescGZIP(), []int{5}
}

func (x *GetTransactionTreeResponse) GetTransaction() *TransactionTree {
	if x != nil {
		return x.Transaction
	}
	return nil
}

type GetTransactionResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required
	Transaction   *Transaction `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactionResponse) Reset() {
	*x = GetTransactionResponse{}
	mi := &file_com_daml_ledger_api_v2_update_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionResponse) ProtoMessage() {}

func (x *GetTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_com_daml_ledger_api_v2_update_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionResponse.ProtoReflect.Descriptor instead.
func (*GetTransactionResponse) Descriptor() ([]byte, []int) {
	return file_com_daml_ledger_api_v2_update_service_proto_rawDescGZIP(), []int{6}
}

func (x *GetTransactionResponse) GetTransaction() *Transaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

var File_com_daml_ledger_api_v2_update_service_proto protoreflect.FileDescriptor

const file_com_daml_ledger_api_v2_update_service_proto_rawDesc = "" +
	"\n" +
	"+com/daml/ledger/api/v2/update_service.proto\x12\x16com.daml.ledger.api.v2\x1a/com/daml/ledger/api/v2/participant_offset.proto\x1a)com/daml/ledger/api/v2/reassignment.proto\x1a(com/daml/ledger/api/v2/transaction.proto\x1a/com/daml/ledger/api/v2/transaction_filter.proto\"\xc4\x02\n" +
	"\x11GetUpdatesRequest\x12R\n" +
	"\x0fbegin_exclusive\x18\x01 \x01(\v2).com.daml.ledger.api.v2.ParticipantOffsetR\x0ebeginExclusive\x12N\n" +
	"\rend_inclusive\x18\x02 \x01(\v2).com.daml.ledger.api.v2.ParticipantOffsetR\fendInclusive\x12A\n" +
	"\x06filter\x18\x03 \x01(\v2).com.daml.ledger.api.v2.TransactionFilterR\x06filter\x12\x18\n" +
	"\averbose\x18\x04 \x01(\bR\averbose\x12.\n" +
	"\x13send_pruned_offsets\x18\x05 \x01(\bR\x11sendPrunedOffsets\"\xd8\x01\n" +
	"\x12GetUpdatesResponse\x12G\n" +
	"\vtransaction\x18\x01 \x01(\v2#.com.daml.ledger.api.v2.TransactionH\x00R\vtransaction\x12J\n" +
	"\freassignment\x18\x02 \x01(\v2$.com.daml.ledger.api.v2.ReassignmentH\x00R\freassignment\x12#\n" +
	"\rpruned_offset\x18\x03 \x01(\tR\fprunedOffsetB\b\n" +
	"\x06update\"\xe9\x01\n" +
	"\x16GetUpdateTreesResponse\x12T\n" +
	"\x10transaction_tree\x18\x01 \x01(\v2'.com.daml.ledger.api.v2.TransactionTreeH\x00R\x0ftransactionTree\x12J\n" +
	"\freassignment\x18\x02 \x01(\v2$.com.daml.ledger.api.v2.ReassignmentH\x00R\freassignment\x12#\n" +
	"\rpruned_offset\x18\x03 \x01(\tR\fprunedOffsetB\b\n" +
	"\x06update\"j\n" +
	"\x1eGetTransactionByEventIdRequest\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12-\n" +
	"\x12requesting_parties\x18\x02 \x03(\tR\x11requestingParties\"g\n" +
	"\x19GetTransactionByIdRequest\x12\x1b\n" +
	"\tupdate_id\x18\x01 \x01(\tR\bupdateId\x12-\n" +
	"\x12requesting_parties\x18\x02 \x03(\tR\x11requestingParties\"g\n" +
	"\x1aGetTransactionTreeResponse\x12I\n" +
	"\vtransaction\x18\x01 \x01(\v2'.com.daml.ledger.api.v2.TransactionTreeR\vtransaction\"_\n" +
	"\x16GetTransactionResponse\x12E\n" +
	"\vtransaction\x18\x01 \x01(\v2#.com.daml.ledger.api.v2.TransactionR\vtransaction2\xef\x05\n" +
	"\rUpdateService\x12e\n" +
	"\n" +
	"GetUpdates\x12).com.daml.ledger.api.v2.GetUpdatesRequest\x1a*.com.daml.ledger.api.v2.GetUpdatesResponse0\x01\x12m\n" +
	"\x0eGetUpdateTrees\x12).com.daml.ledger.api.v2.GetUpdatesRequest\x1a..com.daml.ledger.api.v2.GetUpdateTreesResponse0\x01\x12\x89\x01\n" +
	"\x1bGetTransactionTreeByEventId\x126.com.daml.ledger.api.v2.GetTransactionByEventIdRequest\x1a2.com.daml.ledger.api.v2.GetTransactionTreeResponse\x12\x7f\n" +
	"\x16GetTransactionTreeById\x121.com.daml.ledger.api.v2.GetTransactionByIdRequest\x1a2.com.daml.ledger.api.v2.GetTransactionTreeResponse\x12\x81\x01\n" +
	"\x17GetTransactionByEventId\x126.com.daml.ledger.api.v2.GetTransactionByEventIdRequest\x1a..com.daml.ledger.api.v2.GetTransactionResponse\x12w\n" +
	"\x12GetTransactionById\x121.com.daml.ledger.api.v2.GetTransactionByIdRequest\x1a..com.daml.ledger.api.v2.GetTransactionResponseB\x85\x01\n" +
	"\x16com.daml.ledger.api.v2B\x17UpdateServiceOuterClassZ9github.com/chainsafe/canton-middleware/pkg/canton/lapi/v2\xaa\x02\x16Com.Daml.Ledger.Api.V2b\x06proto3"

var (
	file_com_daml_ledger_api_v2_update_service_proto_rawDescOnce sync.Once
	file_com_daml_ledger_api_v2_update_service_proto_rawDescData []byte
)

func file_com_daml_ledger_api_v2_update_service_proto_rawDescGZIP() []byte {
	file_com_daml_ledger_api_v2_update_service_proto_rawDescOnce.Do(func() {
		file_com_daml_ledger_api_v2_update_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_com_daml_ledger_api_v2_update_service_proto_rawDesc), len(file_com_daml_ledger_api_v2_update_service_proto_rawDesc)))
	})
	return file_com_daml_ledger_api_v2_update_service_proto_rawDescData
}

var file_com_daml_ledger_api_v2_update_service_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_com_daml_ledger_api_v2_update_service_proto_goTypes = []any{
	(*GetUpdatesRequest)(nil),              // 0: com.daml.ledger.api.v2.GetUpdatesRequest
	(*GetUpdatesResponse)(nil),             // 1: com.daml.ledger.api.v2.GetUpdatesResponse
	(*GetUpdateTreesResponse)(nil),         // 2: com.daml.ledger.api.v2.GetUpdateTreesResponse
	(*GetTransactionByEventIdRequest)(nil), // 3: com.daml.ledger.api.v2.GetTransactionByEventIdRequest
	(*GetTransactionByIdRequest)(nil),      // 4: com.daml.ledger.api.v2.GetTransactionByIdRequest
	(*GetTransactionTreeResponse)(nil),     // 5: com.daml.ledger.api.v2.GetTransactionTreeResponse
	(*GetTransactionResponse)(nil),         // 6: com.daml.ledger.api.v2.GetTransactionResponse
	(*ParticipantOffset)(nil),              // 7: com.daml.ledger.api.v2.ParticipantOffset
	(*TransactionFilter)(nil),              // 8: com.daml.ledger.api.v2.TransactionFilter
	(*Transaction)(nil),                    // 9: com.daml.ledger.api.v2.Transaction
	(*Reassignment)(nil),                   // 10: com.daml.ledger.api.v2.Reassignment
	(*TransactionTree)(nil),                // 11: com.daml.ledger.api.v2.TransactionTree
}
var file_com_daml_ledger_api_v2_update_service_proto_depIdxs = []int32{
	7,  // 0: com.daml.ledger.api.v2.GetUpdatesRequest.begin_exclusive:type_name -> com.daml.ledger.api.v2.ParticipantOffset
	7,  // 1: com.daml.ledger.api.v2.GetUpdatesRequest.end_inclusive:type_name -> com.daml.ledger.api.v2.ParticipantOffset
	8,  // 2: com.daml.ledger.api.v2.GetUpdatesRequest.filter:type_name -> com.daml.ledger.api.v2.TransactionFilter
	9,  // 3: com.daml.ledger.api.v2.GetUpdatesResponse.transaction:type_name -> com.daml.ledger.api.v2.Transaction
	10, // 4: com.daml.ledger.api.v2.GetUpdatesResponse.reassignment:type_name -> com.daml.ledger.api.v2.Reassignment
	11, // 5: com.daml.ledger.api.v2.GetUpdateTreesResponse.transaction_tree:type_name -> com.daml.ledger.api.v2.TransactionTree
	10, // 6: com.daml.ledger.api.v2.GetUpdateTreesResponse.reassignment:type_name -> com.daml.ledger.api.v2.Reassignment
	11, // 7: com.daml.ledger.api.v2.GetTransactionTreeResponse.transaction:type_name -> com.daml.ledger.api.v2.TransactionTree
	9,  // 8: com.daml.ledger.api.v2.GetTransactionResponse.transaction:type_name -> com.daml.ledger.api.v2.Transaction
	0,  // 9: com.daml.ledger.api.v2.UpdateService.GetUpdates:input_type -> com.daml.ledger.api.v2.GetUpdatesRequest
	0,  // 10: com.daml.ledger.api.v2.UpdateService.GetUpdateTrees:input_type -> com.daml.ledger.api.v2.GetUpdatesRequest
	3,  // 11: com.daml.ledger.api.v2.UpdateService.GetTransactionTreeByEventId:input_type -> com.daml.ledger.api.v2.GetTransactionByEventIdRequest
	4,  // 12: com.daml.ledger.api.v2.UpdateService.GetTransactionTreeById:input_type -> com.daml.ledger.api.v2.GetTransactionByIdRequest
	3,  // 13: com.daml.ledger.api.v2.UpdateService.GetTransactionByEventId:input_type -> com.daml.ledger.api.v2.GetTransactionByEventIdRequest
	4,  // 14: com.daml.ledger.api.v2.UpdateService.GetTransactionById:input_type -> com.daml.ledger.api.v2.GetTransactionByIdRequest
	1,  // 15: com.daml.ledger.api.v2.UpdateService.GetUpdates:output_type -> com.daml.ledger.api.v2.GetUpdatesResponse
	2,  // 16: com.daml.ledger.api.v2.UpdateService.GetUpdateTrees:output_type -> com.daml.ledger.api.v2.GetUpdateTreesResponse
	5,  // 17: com.daml.ledger.api.v2.UpdateService.GetTransactionTreeByEventId:output_type -> com.daml.ledger.api.v2.GetTransactionTreeResponse
	5,  // 18: com.daml.ledger.api.v2.UpdateService.GetTransactionTreeById:output_type -> com.daml.ledger.api.v2.GetTransactionTreeResponse
	6,  // 19: com.daml.ledger.api.v2.UpdateService.GetTransactionByEventId:output_type -> com.daml.ledger.api.v2.GetTransactionResponse
	6,  // 20: com.daml.ledger.api.v2.UpdateService.GetTransactionById:output_type -> com.daml.ledger.api.v2.GetTransactionResponse
	15, // [15:21] is the sub-list for method output_type
	9,  // [9:15] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_com_daml_ledger_api_v2_update_service_proto_init() }
func file_com_daml_ledger_api_v2_update_service_proto_init() {
	if File_com_daml_ledger_api_v2_update_service_proto != nil {
		return
	}
	file_com_daml_ledger_api_v2_participant_offset_proto_init()
	file_com_daml_ledger_api_v2_reassignment_proto_init()
	file_com_daml_ledger_api_v2_transaction_proto_init()
	file_com_daml_ledger_api_v2_transaction_filter_proto_init()
	file_com_daml_ledger_api_v2_update_service_proto_msgTypes[1].OneofWrappers = []any{
		(*GetUpdatesResponse_Transaction)(nil),
		(*GetUpdatesResponse_Reassignment)(nil),
	}
	file_com_daml_ledger_api_v2_update_service_proto_msgTypes[2].OneofWrappers = []any{
		(*GetUpdateTreesResponse_TransactionTree)(nil),
		(*GetUpdateTreesResponse_Reassignment)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_com_daml_ledger_api_v2_update_service_proto_rawDesc), len(file_com_daml_ledger_api_v2_update_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_com_daml_ledger_api_v2_update_service_proto_goTypes,
		DependencyIndexes: file_com_daml_ledger_api_v2_update_service_proto_depIdxs,
		MessageInfos:      file_com_daml_ledger_api_v2_update_service_proto_msgTypes,
	}.Build()
	File_com_daml_ledger_api_v2_update_service_proto = out.File
	file_com_daml_ledger_api_v2_update_service_proto_goTypes = nil
	file_com_daml_ledger_api_v2_update_service_proto_depIdxs = nil
}
