// Copyright (c) 2024 Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: com/daml/ledger/api/v2/version_service.proto

package v2

import (
	v1 "github.com/chainsafe/canton-middleware/pkg/canton/lapi/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetLedgerApiVersionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLedgerApiVersionRequest) Reset() {
	*x = GetLedgerApiVersionRequest{}
	mi := &file_com_daml_ledger_api_v2_version_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLedgerApiVersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLedgerApiVersionRequest) ProtoMessage() {}

func (x *GetLedgerApiVersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_com_daml_ledger_api_v2_version_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLedgerApiVersionRequest.ProtoReflect.Descriptor instead.
func (*GetLedgerApiVersionRequest) Descriptor() ([]byte, []int) {
	return file_com_daml_ledger_api_v2_version_service_proto_rawDescGZIP(), []int{0}
}

var File_com_daml_ledger_api_v2_version_service_proto protoreflect.FileDescriptor

const file_com_daml_ledger_api_v2_version_service_proto_rawDesc = "" +
	"\n" +
	",com/daml/ledger/api/v2/version_service.proto\x12\x16com.daml.ledger.api.v2\x1a,com/daml/ledger/api/v1/version_service.proto\"\x1c\n" +
	"\x1aGetLedgerApiVersionRequest2\x90\x01\n" +
	"\x0eVersionService\x12~\n" +
	"\x13GetLedgerApiVersion\x122.com.daml.ledger.api.v2.GetLedgerApiVersionRequest\x1a3.com.daml.ledger.api.v1.GetLedgerApiVersionResponseB\x86\x01\n" +
	"\x16com.daml.ledger.api.v2B\x18VersionServiceOuterClassZ9github.com/chainsafe/canton-middleware/pkg/canton/lapi/v2\xaa\x02\x16Com.Daml.Ledger.Api.V2b\x06proto3"

var (
	file_com_daml_ledger_api_v2_version_service_proto_rawDescOnce sync.Once
	file_com_daml_ledger_api_v2_version_service_proto_rawDescData []byte
)

func file_com_daml_ledger_api_v2_version_service_proto_rawDescGZIP() []byte {
	file_com_daml_ledger_api_v2_version_service_proto_rawDescOnce.Do(func() {
		file_com_daml_ledger_api_v2_version_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_com_daml_ledger_api_v2_version_service_proto_rawDesc), len(file_com_daml_ledger_api_v2_version_service_proto_rawDesc)))
	})
	return file_com_daml_ledger_api_v2_version_service_proto_rawDescData
}

var file_com_daml_ledger_api_v2_version_service_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_com_daml_ledger_api_v2_version_service_proto_goTypes = []any{
	(*GetLedgerApiVersionRequest)(nil),     // 0: com.daml.ledger.api.v2.GetLedgerApiVersionRequest
	(*v1.GetLedgerApiVersionResponse)(nil), // 1: com.daml.ledger.api.v1.GetLedgerApiVersionResponse
}
var file_com_daml_ledger_api_v2_version_service_proto_depIdxs = []int32{
	0, // 0: com.daml.ledger.api.v2.VersionService.GetLedgerApiVersion:input_type -> com.daml.ledger.api.v2.GetLedgerApiVersionRequest
	1, // 1: com.daml.ledger.api.v2.VersionService.GetLedgerApiVersion:output_type -> com.daml.ledger.api.v1.GetLedgerApiVersionResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_com_daml_ledger_api_v2_version_service_proto_init() }
func file_com_daml_ledger_api_v2_version_service_proto_init() {
	if File_com_daml_ledger_api_v2_version_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_com_daml_ledger_api_v2_version_service_proto_rawDesc), len(file_com_daml_ledger_api_v2_version_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_com_daml_ledger_api_v2_version_service_proto_goTypes,
		DependencyIndexes: file_com_daml_ledger_api_v2_version_service_proto_depIdxs,
		MessageInfos:      file_com_daml_ledger_api_v2_version_service_proto_msgTypes,
	}.Build()
	File_com_daml_ledger_api_v2_version_service_proto = out.File
	file_com_daml_ledger_api_v2_version_service_proto_goTypes = nil
	file_com_daml_ledger_api_v2_version_service_proto_depIdxs = nil
}
