// Command generate-test-vectors produces deterministic crypto test vectors
// for cross-validation with the canton-snap TypeScript implementation.
//
// Output is written to stdout as JSON. Redirect to a file:
//
//	go run ./cmd/generate-test-vectors > vectors.json
package main

import (
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"os"

	"github.com/chainsafe/canton-middleware/pkg/keys"
)

type signatureVector struct {
	Hash         string `json:"hash"`
	DERSignature string `json:"der_signature"`
}

type keyVector struct {
	PrivateKey       string            `json:"private_key"`
	CompressedPubKey string            `json:"compressed_public_key"`
	SPKIDer          string            `json:"spki_der"`
	Fingerprint      string            `json:"fingerprint"`
	Signatures       []signatureVector `json:"signatures"`
}

type vectorFile struct {
	Description string      `json:"description"`
	Vectors     []keyVector `json:"vectors"`
}

// Test private keys — small, deterministic, easy to reproduce.
// These are NOT secure keys — they exist solely for cross-validation.
var testPrivateKeys = []string{
	"0000000000000000000000000000000000000000000000000000000000000001",
	"0000000000000000000000000000000000000000000000000000000000000002",
	"0000000000000000000000000000000000000000000000000000000000000003",
	"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
	"deadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeef",
}

// Test messages to hash and sign.
var testMessages = []string{
	"",
	"canton-snap cross-validation",
	"hello world",
}

func main() {
	output := vectorFile{
		Description: "Canton crypto test vectors for cross-validation with canton-snap TypeScript. " +
			"Generated by: go run ./cmd/generate-test-vectors",
	}

	for _, privHex := range testPrivateKeys {
		privBytes, err := hex.DecodeString(privHex)
		if err != nil {
			fmt.Fprintf(os.Stderr, "invalid private key hex %q: %v\n", privHex, err)
			os.Exit(1)
		}

		kp, err := keys.CantonKeyPairFromPrivateKey(privBytes)
		if err != nil {
			fmt.Fprintf(os.Stderr, "invalid private key %q: %v\n", privHex, err)
			os.Exit(1)
		}

		spki, err := kp.SPKIPublicKey()
		if err != nil {
			fmt.Fprintf(os.Stderr, "SPKIPublicKey failed for key %q: %v\n", privHex, err)
			os.Exit(1)
		}

		fp, err := kp.Fingerprint()
		if err != nil {
			fmt.Fprintf(os.Stderr, "Fingerprint failed for key %q: %v\n", privHex, err)
			os.Exit(1)
		}

		kv := keyVector{
			PrivateKey:       privHex,
			CompressedPubKey: hex.EncodeToString(kp.PublicKey),
			SPKIDer:          hex.EncodeToString(spki),
			Fingerprint:      fp,
		}

		for _, msg := range testMessages {
			hash := sha256.Sum256([]byte(msg))
			derSig, err := kp.SignHashDER(hash[:])
			if err != nil {
				fmt.Fprintf(os.Stderr, "SignHashDER failed for key %q, msg %q: %v\n", privHex, msg, err)
				os.Exit(1)
			}

			// Self-verify to catch bugs early
			if err := keys.VerifyDER(kp.PublicKey, hash[:], derSig); err != nil {
				fmt.Fprintf(os.Stderr, "Self-verification failed for key %q, msg %q: %v\n", privHex, msg, err)
				os.Exit(1)
			}

			kv.Signatures = append(kv.Signatures, signatureVector{
				Hash:         hex.EncodeToString(hash[:]),
				DERSignature: hex.EncodeToString(derSig),
			})
		}

		output.Vectors = append(output.Vectors, kv)
	}

	enc := json.NewEncoder(os.Stdout)
	enc.SetIndent("", "  ")
	if err := enc.Encode(output); err != nil {
		fmt.Fprintf(os.Stderr, "JSON encode failed: %v\n", err)
		os.Exit(1)
	}
}
