// Copyright (c) 2024 Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: com/daml/ledger/api/v1/active_contracts_service.proto

package lapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetActiveContractsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Must correspond to the ledger ID reported by the Ledger Identification Service.
	// Must be a valid LedgerString (as described in “value.proto“).
	// Optional
	LedgerId string `protobuf:"bytes,1,opt,name=ledger_id,json=ledgerId,proto3" json:"ledger_id,omitempty"`
	// Templates to include in the served snapshot, per party.
	// Required
	Filter *TransactionFilter `protobuf:"bytes,2,opt,name=filter,proto3" json:"filter,omitempty"`
	// If enabled, values served over the API will contain more information than strictly necessary to interpret the data.
	// In particular, setting the verbose flag to true triggers the ledger to include labels for record fields.
	// Optional
	Verbose bool `protobuf:"varint,3,opt,name=verbose,proto3" json:"verbose,omitempty"`
	// The offset at which the snapshot of the active contracts will be computed.
	// Must be no greater than the current ledger end offset.
	// Must be greater than or equal to the last pruning offset.
	// If not set the current ledger end offset will be used.
	// Optional
	ActiveAtOffset string `protobuf:"bytes,4,opt,name=active_at_offset,json=activeAtOffset,proto3" json:"active_at_offset,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetActiveContractsRequest) Reset() {
	*x = GetActiveContractsRequest{}
	mi := &file_com_daml_ledger_api_v1_active_contracts_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActiveContractsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActiveContractsRequest) ProtoMessage() {}

func (x *GetActiveContractsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_com_daml_ledger_api_v1_active_contracts_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActiveContractsRequest.ProtoReflect.Descriptor instead.
func (*GetActiveContractsRequest) Descriptor() ([]byte, []int) {
	return file_com_daml_ledger_api_v1_active_contracts_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetActiveContractsRequest) GetLedgerId() string {
	if x != nil {
		return x.LedgerId
	}
	return ""
}

func (x *GetActiveContractsRequest) GetFilter() *TransactionFilter {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *GetActiveContractsRequest) GetVerbose() bool {
	if x != nil {
		return x.Verbose
	}
	return false
}

func (x *GetActiveContractsRequest) GetActiveAtOffset() string {
	if x != nil {
		return x.ActiveAtOffset
	}
	return ""
}

type GetActiveContractsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Included only in the last message.
	// The client should start consuming the transactions endpoint with this offset.
	// The format of this field is described in “ledger_offset.proto“.
	Offset string `protobuf:"bytes,1,opt,name=offset,proto3" json:"offset,omitempty"`
	// The workflow that created the contracts.
	// Must be a valid LedgerString (as described in “value.proto“).
	WorkflowId string `protobuf:"bytes,2,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	// The list of contracts that were introduced by the workflow with “workflow_id“ at the offset.
	// Must be a valid LedgerString (as described in “value.proto“).
	ActiveContracts []*CreatedEvent `protobuf:"bytes,3,rep,name=active_contracts,json=activeContracts,proto3" json:"active_contracts,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetActiveContractsResponse) Reset() {
	*x = GetActiveContractsResponse{}
	mi := &file_com_daml_ledger_api_v1_active_contracts_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActiveContractsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActiveContractsResponse) ProtoMessage() {}

func (x *GetActiveContractsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_com_daml_ledger_api_v1_active_contracts_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActiveContractsResponse.ProtoReflect.Descriptor instead.
func (*GetActiveContractsResponse) Descriptor() ([]byte, []int) {
	return file_com_daml_ledger_api_v1_active_contracts_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetActiveContractsResponse) GetOffset() string {
	if x != nil {
		return x.Offset
	}
	return ""
}

func (x *GetActiveContractsResponse) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *GetActiveContractsResponse) GetActiveContracts() []*CreatedEvent {
	if x != nil {
		return x.ActiveContracts
	}
	return nil
}

var File_com_daml_ledger_api_v1_active_contracts_service_proto protoreflect.FileDescriptor

const file_com_daml_ledger_api_v1_active_contracts_service_proto_rawDesc = "" +
	"\n" +
	"5com/daml/ledger/api/v1/active_contracts_service.proto\x12\x16com.daml.ledger.api.v1\x1a\"com/daml/ledger/api/v1/event.proto\x1a/com/daml/ledger/api/v1/transaction_filter.proto\"\xbf\x01\n" +
	"\x19GetActiveContractsRequest\x12\x1b\n" +
	"\tledger_id\x18\x01 \x01(\tR\bledgerId\x12A\n" +
	"\x06filter\x18\x02 \x01(\v2).com.daml.ledger.api.v1.TransactionFilterR\x06filter\x12\x18\n" +
	"\averbose\x18\x03 \x01(\bR\averbose\x12(\n" +
	"\x10active_at_offset\x18\x04 \x01(\tR\x0eactiveAtOffset\"\xa6\x01\n" +
	"\x1aGetActiveContractsResponse\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\tR\x06offset\x12\x1f\n" +
	"\vworkflow_id\x18\x02 \x01(\tR\n" +
	"workflowId\x12O\n" +
	"\x10active_contracts\x18\x03 \x03(\v2$.com.daml.ledger.api.v1.CreatedEventR\x0factiveContracts2\x97\x01\n" +
	"\x16ActiveContractsService\x12}\n" +
	"\x12GetActiveContracts\x121.com.daml.ledger.api.v1.GetActiveContractsRequest\x1a2.com.daml.ledger.api.v1.GetActiveContractsResponse0\x01B\x8b\x01\n" +
	"\x16com.daml.ledger.api.v1B ActiveContractsServiceOuterClassZ6github.com/chainsafe/canton-middleware/pkg/canton/lapi\xaa\x02\x16Com.Daml.Ledger.Api.V1b\x06proto3"

var (
	file_com_daml_ledger_api_v1_active_contracts_service_proto_rawDescOnce sync.Once
	file_com_daml_ledger_api_v1_active_contracts_service_proto_rawDescData []byte
)

func file_com_daml_ledger_api_v1_active_contracts_service_proto_rawDescGZIP() []byte {
	file_com_daml_ledger_api_v1_active_contracts_service_proto_rawDescOnce.Do(func() {
		file_com_daml_ledger_api_v1_active_contracts_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_com_daml_ledger_api_v1_active_contracts_service_proto_rawDesc), len(file_com_daml_ledger_api_v1_active_contracts_service_proto_rawDesc)))
	})
	return file_com_daml_ledger_api_v1_active_contracts_service_proto_rawDescData
}

var file_com_daml_ledger_api_v1_active_contracts_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_com_daml_ledger_api_v1_active_contracts_service_proto_goTypes = []any{
	(*GetActiveContractsRequest)(nil),  // 0: com.daml.ledger.api.v1.GetActiveContractsRequest
	(*GetActiveContractsResponse)(nil), // 1: com.daml.ledger.api.v1.GetActiveContractsResponse
	(*TransactionFilter)(nil),          // 2: com.daml.ledger.api.v1.TransactionFilter
	(*CreatedEvent)(nil),               // 3: com.daml.ledger.api.v1.CreatedEvent
}
var file_com_daml_ledger_api_v1_active_contracts_service_proto_depIdxs = []int32{
	2, // 0: com.daml.ledger.api.v1.GetActiveContractsRequest.filter:type_name -> com.daml.ledger.api.v1.TransactionFilter
	3, // 1: com.daml.ledger.api.v1.GetActiveContractsResponse.active_contracts:type_name -> com.daml.ledger.api.v1.CreatedEvent
	0, // 2: com.daml.ledger.api.v1.ActiveContractsService.GetActiveContracts:input_type -> com.daml.ledger.api.v1.GetActiveContractsRequest
	1, // 3: com.daml.ledger.api.v1.ActiveContractsService.GetActiveContracts:output_type -> com.daml.ledger.api.v1.GetActiveContractsResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_com_daml_ledger_api_v1_active_contracts_service_proto_init() }
func file_com_daml_ledger_api_v1_active_contracts_service_proto_init() {
	if File_com_daml_ledger_api_v1_active_contracts_service_proto != nil {
		return
	}
	file_com_daml_ledger_api_v1_event_proto_init()
	file_com_daml_ledger_api_v1_transaction_filter_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_com_daml_ledger_api_v1_active_contracts_service_proto_rawDesc), len(file_com_daml_ledger_api_v1_active_contracts_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_com_daml_ledger_api_v1_active_contracts_service_proto_goTypes,
		DependencyIndexes: file_com_daml_ledger_api_v1_active_contracts_service_proto_depIdxs,
		MessageInfos:      file_com_daml_ledger_api_v1_active_contracts_service_proto_msgTypes,
	}.Build()
	File_com_daml_ledger_api_v1_active_contracts_service_proto = out.File
	file_com_daml_ledger_api_v1_active_contracts_service_proto_goTypes = nil
	file_com_daml_ledger_api_v1_active_contracts_service_proto_depIdxs = nil
}
