// Copyright (c) 2024 Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: com/daml/ledger/api/v2/command_completion_service.proto

package lapi

import (
	v1 "github.com/chainsafe/canton-middleware/pkg/canton/lapi/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CompletionStreamRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Only completions of commands submitted with the same application_id will be visible in the stream.
	// Must be a valid ApplicationIdString (as described in “value.proto“).
	// Required unless authentication is used with a user token or a custom token specifying an application-id.
	// In that case, the token's user-id, respectively application-id, will be used for the request's application_id.
	ApplicationId string `protobuf:"bytes,1,opt,name=application_id,json=applicationId,proto3" json:"application_id,omitempty"`
	// Non-empty list of parties whose data should be included.
	// Only completions of commands for which at least one of the “act_as“ parties is in the given set of parties
	// will be visible in the stream.
	// Must be a valid PartyIdString (as described in “value.proto“).
	// Required
	Parties []string `protobuf:"bytes,2,rep,name=parties,proto3" json:"parties,omitempty"`
	// This field indicates the minimum offset for completions. This can be used to resume an earlier completion stream.
	// Optional, if not set the ledger uses the current ledger end offset instead.
	BeginExclusive *ParticipantOffset `protobuf:"bytes,3,opt,name=begin_exclusive,json=beginExclusive,proto3" json:"begin_exclusive,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CompletionStreamRequest) Reset() {
	*x = CompletionStreamRequest{}
	mi := &file_com_daml_ledger_api_v2_command_completion_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompletionStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompletionStreamRequest) ProtoMessage() {}

func (x *CompletionStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_com_daml_ledger_api_v2_command_completion_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompletionStreamRequest.ProtoReflect.Descriptor instead.
func (*CompletionStreamRequest) Descriptor() ([]byte, []int) {
	return file_com_daml_ledger_api_v2_command_completion_service_proto_rawDescGZIP(), []int{0}
}

func (x *CompletionStreamRequest) GetApplicationId() string {
	if x != nil {
		return x.ApplicationId
	}
	return ""
}

func (x *CompletionStreamRequest) GetParties() []string {
	if x != nil {
		return x.Parties
	}
	return nil
}

func (x *CompletionStreamRequest) GetBeginExclusive() *ParticipantOffset {
	if x != nil {
		return x.BeginExclusive
	}
	return nil
}

type CompletionStreamResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// This checkpoint may be used to restart consumption.  The
	// checkpoint belongs to the completion in this response.
	// Required
	Checkpoint *v1.Checkpoint `protobuf:"bytes,1,opt,name=checkpoint,proto3" json:"checkpoint,omitempty"`
	// Required
	Completion *Completion `protobuf:"bytes,2,opt,name=completion,proto3" json:"completion,omitempty"`
	// The sequencing domain.
	// In case
	//
	//   - successful/failed transactions: identifies the sequencing domain of the transaction
	//   - for successful/failed unassign commands: identifies the source domain
	//   - for successful/failed assign commands: identifies the target domain
	//
	// Required
	DomainId      string `protobuf:"bytes,3,opt,name=domain_id,json=domainId,proto3" json:"domain_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompletionStreamResponse) Reset() {
	*x = CompletionStreamResponse{}
	mi := &file_com_daml_ledger_api_v2_command_completion_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompletionStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompletionStreamResponse) ProtoMessage() {}

func (x *CompletionStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_com_daml_ledger_api_v2_command_completion_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompletionStreamResponse.ProtoReflect.Descriptor instead.
func (*CompletionStreamResponse) Descriptor() ([]byte, []int) {
	return file_com_daml_ledger_api_v2_command_completion_service_proto_rawDescGZIP(), []int{1}
}

func (x *CompletionStreamResponse) GetCheckpoint() *v1.Checkpoint {
	if x != nil {
		return x.Checkpoint
	}
	return nil
}

func (x *CompletionStreamResponse) GetCompletion() *Completion {
	if x != nil {
		return x.Completion
	}
	return nil
}

func (x *CompletionStreamResponse) GetDomainId() string {
	if x != nil {
		return x.DomainId
	}
	return ""
}

var File_com_daml_ledger_api_v2_command_completion_service_proto protoreflect.FileDescriptor

const file_com_daml_ledger_api_v2_command_completion_service_proto_rawDesc = "" +
	"\n" +
	"7com/daml/ledger/api/v2/command_completion_service.proto\x12\x16com.daml.ledger.api.v2\x1a7com/daml/ledger/api/v1/command_completion_service.proto\x1a'com/daml/ledger/api/v2/completion.proto\x1a/com/daml/ledger/api/v2/participant_offset.proto\"\xae\x01\n" +
	"\x17CompletionStreamRequest\x12%\n" +
	"\x0eapplication_id\x18\x01 \x01(\tR\rapplicationId\x12\x18\n" +
	"\aparties\x18\x02 \x03(\tR\aparties\x12R\n" +
	"\x0fbegin_exclusive\x18\x03 \x01(\v2).com.daml.ledger.api.v2.ParticipantOffsetR\x0ebeginExclusive\"\xbf\x01\n" +
	"\x18CompletionStreamResponse\x12B\n" +
	"\n" +
	"checkpoint\x18\x01 \x01(\v2\".com.daml.ledger.api.v1.CheckpointR\n" +
	"checkpoint\x12B\n" +
	"\n" +
	"completion\x18\x02 \x01(\v2\".com.daml.ledger.api.v2.CompletionR\n" +
	"completion\x12\x1b\n" +
	"\tdomain_id\x18\x03 \x01(\tR\bdomainId2\x93\x01\n" +
	"\x18CommandCompletionService\x12w\n" +
	"\x10CompletionStream\x12/.com.daml.ledger.api.v2.CompletionStreamRequest\x1a0.com.daml.ledger.api.v2.CompletionStreamResponse0\x01B\x8d\x01\n" +
	"\x16com.daml.ledger.api.v2B\"CommandCompletionServiceOuterClassZ6github.com/chainsafe/canton-middleware/pkg/canton/lapi\xaa\x02\x16Com.Daml.Ledger.Api.V2b\x06proto3"

var (
	file_com_daml_ledger_api_v2_command_completion_service_proto_rawDescOnce sync.Once
	file_com_daml_ledger_api_v2_command_completion_service_proto_rawDescData []byte
)

func file_com_daml_ledger_api_v2_command_completion_service_proto_rawDescGZIP() []byte {
	file_com_daml_ledger_api_v2_command_completion_service_proto_rawDescOnce.Do(func() {
		file_com_daml_ledger_api_v2_command_completion_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_com_daml_ledger_api_v2_command_completion_service_proto_rawDesc), len(file_com_daml_ledger_api_v2_command_completion_service_proto_rawDesc)))
	})
	return file_com_daml_ledger_api_v2_command_completion_service_proto_rawDescData
}

var file_com_daml_ledger_api_v2_command_completion_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_com_daml_ledger_api_v2_command_completion_service_proto_goTypes = []any{
	(*CompletionStreamRequest)(nil),  // 0: com.daml.ledger.api.v2.CompletionStreamRequest
	(*CompletionStreamResponse)(nil), // 1: com.daml.ledger.api.v2.CompletionStreamResponse
	(*ParticipantOffset)(nil),        // 2: com.daml.ledger.api.v2.ParticipantOffset
	(*v1.Checkpoint)(nil),            // 3: com.daml.ledger.api.v1.Checkpoint
	(*Completion)(nil),               // 4: com.daml.ledger.api.v2.Completion
}
var file_com_daml_ledger_api_v2_command_completion_service_proto_depIdxs = []int32{
	2, // 0: com.daml.ledger.api.v2.CompletionStreamRequest.begin_exclusive:type_name -> com.daml.ledger.api.v2.ParticipantOffset
	3, // 1: com.daml.ledger.api.v2.CompletionStreamResponse.checkpoint:type_name -> com.daml.ledger.api.v1.Checkpoint
	4, // 2: com.daml.ledger.api.v2.CompletionStreamResponse.completion:type_name -> com.daml.ledger.api.v2.Completion
	0, // 3: com.daml.ledger.api.v2.CommandCompletionService.CompletionStream:input_type -> com.daml.ledger.api.v2.CompletionStreamRequest
	1, // 4: com.daml.ledger.api.v2.CommandCompletionService.CompletionStream:output_type -> com.daml.ledger.api.v2.CompletionStreamResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_com_daml_ledger_api_v2_command_completion_service_proto_init() }
func file_com_daml_ledger_api_v2_command_completion_service_proto_init() {
	if File_com_daml_ledger_api_v2_command_completion_service_proto != nil {
		return
	}
	file_com_daml_ledger_api_v2_completion_proto_init()
	file_com_daml_ledger_api_v2_participant_offset_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_com_daml_ledger_api_v2_command_completion_service_proto_rawDesc), len(file_com_daml_ledger_api_v2_command_completion_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_com_daml_ledger_api_v2_command_completion_service_proto_goTypes,
		DependencyIndexes: file_com_daml_ledger_api_v2_command_completion_service_proto_depIdxs,
		MessageInfos:      file_com_daml_ledger_api_v2_command_completion_service_proto_msgTypes,
	}.Build()
	File_com_daml_ledger_api_v2_command_completion_service_proto = out.File
	file_com_daml_ledger_api_v2_command_completion_service_proto_goTypes = nil
	file_com_daml_ledger_api_v2_command_completion_service_proto_depIdxs = nil
}
