// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	indexer "github.com/chainsafe/canton-middleware/pkg/indexer"
	mock "github.com/stretchr/testify/mock"
)

// IndexerReader is an autogenerated mock type for the IndexerReader type
type IndexerReader struct {
	mock.Mock
}

type IndexerReader_Expecter struct {
	mock *mock.Mock
}

func (_m *IndexerReader) EXPECT() *IndexerReader_Expecter {
	return &IndexerReader_Expecter{mock: &_m.Mock}
}

// GetTransfers provides a mock function with given fields: ctx, partyID, query, p
func (_m *IndexerReader) GetTransfers(ctx context.Context, partyID string, query indexer.TransferQuery, p indexer.Pagination) (*indexer.Page[indexer.Transfer], error) {
	ret := _m.Called(ctx, partyID, query, p)

	if len(ret) == 0 {
		panic("no return value specified for GetTransfers")
	}

	var r0 *indexer.Page[indexer.Transfer]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, indexer.TransferQuery, indexer.Pagination) (*indexer.Page[indexer.Transfer], error)); ok {
		return rf(ctx, partyID, query, p)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, indexer.TransferQuery, indexer.Pagination) *indexer.Page[indexer.Transfer]); ok {
		r0 = rf(ctx, partyID, query, p)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*indexer.Page[indexer.Transfer])
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, indexer.TransferQuery, indexer.Pagination) error); ok {
		r1 = rf(ctx, partyID, query, p)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IndexerReader_GetTransfers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTransfers'
type IndexerReader_GetTransfers_Call struct {
	*mock.Call
}

// GetTransfers is a helper method to define mock.On call
//   - ctx context.Context
//   - partyID string
//   - query indexer.TransferQuery
//   - p indexer.Pagination
func (_e *IndexerReader_Expecter) GetTransfers(ctx interface{}, partyID interface{}, query interface{}, p interface{}) *IndexerReader_GetTransfers_Call {
	return &IndexerReader_GetTransfers_Call{Call: _e.mock.On("GetTransfers", ctx, partyID, query, p)}
}

func (_c *IndexerReader_GetTransfers_Call) Run(run func(ctx context.Context, partyID string, query indexer.TransferQuery, p indexer.Pagination)) *IndexerReader_GetTransfers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(indexer.TransferQuery), args[3].(indexer.Pagination))
	})
	return _c
}

func (_c *IndexerReader_GetTransfers_Call) Return(_a0 *indexer.Page[indexer.Transfer], _a1 error) *IndexerReader_GetTransfers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *IndexerReader_GetTransfers_Call) RunAndReturn(run func(context.Context, string, indexer.TransferQuery, indexer.Pagination) (*indexer.Page[indexer.Transfer], error)) *IndexerReader_GetTransfers_Call {
	_c.Call.Return(run)
	return _c
}

// NewIndexerReader creates a new instance of IndexerReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIndexerReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *IndexerReader {
	mock := &IndexerReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
