// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	token "github.com/chainsafe/canton-middleware/pkg/cantonsdk/token"
	mock "github.com/stretchr/testify/mock"
)

// Token is an autogenerated mock type for the Token type
type Token struct {
	mock.Mock
}

type Token_Expecter struct {
	mock *mock.Mock
}

func (_m *Token) EXPECT() *Token_Expecter {
	return &Token_Expecter{mock: &_m.Mock}
}

// Burn provides a mock function with given fields: ctx, req
func (_m *Token) Burn(ctx context.Context, req *token.BurnRequest) error {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Burn")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *token.BurnRequest) error); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Token_Burn_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Burn'
type Token_Burn_Call struct {
	*mock.Call
}

// Burn is a helper method to define mock.On call
//   - ctx context.Context
//   - req *token.BurnRequest
func (_e *Token_Expecter) Burn(ctx interface{}, req interface{}) *Token_Burn_Call {
	return &Token_Burn_Call{Call: _e.mock.On("Burn", ctx, req)}
}

func (_c *Token_Burn_Call) Run(run func(ctx context.Context, req *token.BurnRequest)) *Token_Burn_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*token.BurnRequest))
	})
	return _c
}

func (_c *Token_Burn_Call) Return(_a0 error) *Token_Burn_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Token_Burn_Call) RunAndReturn(run func(context.Context, *token.BurnRequest) error) *Token_Burn_Call {
	_c.Call.Return(run)
	return _c
}

// ExecuteTransfer provides a mock function with given fields: ctx, req
func (_m *Token) ExecuteTransfer(ctx context.Context, req *token.ExecuteTransferRequest) error {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for ExecuteTransfer")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *token.ExecuteTransferRequest) error); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Token_ExecuteTransfer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExecuteTransfer'
type Token_ExecuteTransfer_Call struct {
	*mock.Call
}

// ExecuteTransfer is a helper method to define mock.On call
//   - ctx context.Context
//   - req *token.ExecuteTransferRequest
func (_e *Token_Expecter) ExecuteTransfer(ctx interface{}, req interface{}) *Token_ExecuteTransfer_Call {
	return &Token_ExecuteTransfer_Call{Call: _e.mock.On("ExecuteTransfer", ctx, req)}
}

func (_c *Token_ExecuteTransfer_Call) Run(run func(ctx context.Context, req *token.ExecuteTransferRequest)) *Token_ExecuteTransfer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*token.ExecuteTransferRequest))
	})
	return _c
}

func (_c *Token_ExecuteTransfer_Call) Return(_a0 error) *Token_ExecuteTransfer_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Token_ExecuteTransfer_Call) RunAndReturn(run func(context.Context, *token.ExecuteTransferRequest) error) *Token_ExecuteTransfer_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllHoldings provides a mock function with given fields: ctx
func (_m *Token) GetAllHoldings(ctx context.Context) ([]*token.Holding, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllHoldings")
	}

	var r0 []*token.Holding
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*token.Holding, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*token.Holding); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*token.Holding)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Token_GetAllHoldings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllHoldings'
type Token_GetAllHoldings_Call struct {
	*mock.Call
}

// GetAllHoldings is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Token_Expecter) GetAllHoldings(ctx interface{}) *Token_GetAllHoldings_Call {
	return &Token_GetAllHoldings_Call{Call: _e.mock.On("GetAllHoldings", ctx)}
}

func (_c *Token_GetAllHoldings_Call) Run(run func(ctx context.Context)) *Token_GetAllHoldings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *Token_GetAllHoldings_Call) Return(_a0 []*token.Holding, _a1 error) *Token_GetAllHoldings_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Token_GetAllHoldings_Call) RunAndReturn(run func(context.Context) ([]*token.Holding, error)) *Token_GetAllHoldings_Call {
	_c.Call.Return(run)
	return _c
}

// GetBalanceByFingerprint provides a mock function with given fields: ctx, fingerprint, tokenSymbol
func (_m *Token) GetBalanceByFingerprint(ctx context.Context, fingerprint string, tokenSymbol string) (string, error) {
	ret := _m.Called(ctx, fingerprint, tokenSymbol)

	if len(ret) == 0 {
		panic("no return value specified for GetBalanceByFingerprint")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (string, error)); ok {
		return rf(ctx, fingerprint, tokenSymbol)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = rf(ctx, fingerprint, tokenSymbol)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, fingerprint, tokenSymbol)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Token_GetBalanceByFingerprint_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBalanceByFingerprint'
type Token_GetBalanceByFingerprint_Call struct {
	*mock.Call
}

// GetBalanceByFingerprint is a helper method to define mock.On call
//   - ctx context.Context
//   - fingerprint string
//   - tokenSymbol string
func (_e *Token_Expecter) GetBalanceByFingerprint(ctx interface{}, fingerprint interface{}, tokenSymbol interface{}) *Token_GetBalanceByFingerprint_Call {
	return &Token_GetBalanceByFingerprint_Call{Call: _e.mock.On("GetBalanceByFingerprint", ctx, fingerprint, tokenSymbol)}
}

func (_c *Token_GetBalanceByFingerprint_Call) Run(run func(ctx context.Context, fingerprint string, tokenSymbol string)) *Token_GetBalanceByFingerprint_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *Token_GetBalanceByFingerprint_Call) Return(_a0 string, _a1 error) *Token_GetBalanceByFingerprint_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Token_GetBalanceByFingerprint_Call) RunAndReturn(run func(context.Context, string, string) (string, error)) *Token_GetBalanceByFingerprint_Call {
	_c.Call.Return(run)
	return _c
}

// GetHoldings provides a mock function with given fields: ctx, ownerParty, tokenSymbol
func (_m *Token) GetHoldings(ctx context.Context, ownerParty string, tokenSymbol string) ([]*token.Holding, error) {
	ret := _m.Called(ctx, ownerParty, tokenSymbol)

	if len(ret) == 0 {
		panic("no return value specified for GetHoldings")
	}

	var r0 []*token.Holding
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) ([]*token.Holding, error)); ok {
		return rf(ctx, ownerParty, tokenSymbol)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) []*token.Holding); ok {
		r0 = rf(ctx, ownerParty, tokenSymbol)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*token.Holding)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, ownerParty, tokenSymbol)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Token_GetHoldings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetHoldings'
type Token_GetHoldings_Call struct {
	*mock.Call
}

// GetHoldings is a helper method to define mock.On call
//   - ctx context.Context
//   - ownerParty string
//   - tokenSymbol string
func (_e *Token_Expecter) GetHoldings(ctx interface{}, ownerParty interface{}, tokenSymbol interface{}) *Token_GetHoldings_Call {
	return &Token_GetHoldings_Call{Call: _e.mock.On("GetHoldings", ctx, ownerParty, tokenSymbol)}
}

func (_c *Token_GetHoldings_Call) Run(run func(ctx context.Context, ownerParty string, tokenSymbol string)) *Token_GetHoldings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *Token_GetHoldings_Call) Return(_a0 []*token.Holding, _a1 error) *Token_GetHoldings_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Token_GetHoldings_Call) RunAndReturn(run func(context.Context, string, string) ([]*token.Holding, error)) *Token_GetHoldings_Call {
	_c.Call.Return(run)
	return _c
}

// GetTokenConfigCID provides a mock function with given fields: ctx, tokenSymbol
func (_m *Token) GetTokenConfigCID(ctx context.Context, tokenSymbol string) (string, error) {
	ret := _m.Called(ctx, tokenSymbol)

	if len(ret) == 0 {
		panic("no return value specified for GetTokenConfigCID")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, tokenSymbol)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, tokenSymbol)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, tokenSymbol)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Token_GetTokenConfigCID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTokenConfigCID'
type Token_GetTokenConfigCID_Call struct {
	*mock.Call
}

// GetTokenConfigCID is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenSymbol string
func (_e *Token_Expecter) GetTokenConfigCID(ctx interface{}, tokenSymbol interface{}) *Token_GetTokenConfigCID_Call {
	return &Token_GetTokenConfigCID_Call{Call: _e.mock.On("GetTokenConfigCID", ctx, tokenSymbol)}
}

func (_c *Token_GetTokenConfigCID_Call) Run(run func(ctx context.Context, tokenSymbol string)) *Token_GetTokenConfigCID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Token_GetTokenConfigCID_Call) Return(_a0 string, _a1 error) *Token_GetTokenConfigCID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Token_GetTokenConfigCID_Call) RunAndReturn(run func(context.Context, string) (string, error)) *Token_GetTokenConfigCID_Call {
	_c.Call.Return(run)
	return _c
}

// GetTokenTransferEvents provides a mock function with given fields: ctx
func (_m *Token) GetTokenTransferEvents(ctx context.Context) ([]*token.TokenTransferEvent, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetTokenTransferEvents")
	}

	var r0 []*token.TokenTransferEvent
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*token.TokenTransferEvent, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*token.TokenTransferEvent); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*token.TokenTransferEvent)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Token_GetTokenTransferEvents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTokenTransferEvents'
type Token_GetTokenTransferEvents_Call struct {
	*mock.Call
}

// GetTokenTransferEvents is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Token_Expecter) GetTokenTransferEvents(ctx interface{}) *Token_GetTokenTransferEvents_Call {
	return &Token_GetTokenTransferEvents_Call{Call: _e.mock.On("GetTokenTransferEvents", ctx)}
}

func (_c *Token_GetTokenTransferEvents_Call) Run(run func(ctx context.Context)) *Token_GetTokenTransferEvents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *Token_GetTokenTransferEvents_Call) Return(_a0 []*token.TokenTransferEvent, _a1 error) *Token_GetTokenTransferEvents_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Token_GetTokenTransferEvents_Call) RunAndReturn(run func(context.Context) ([]*token.TokenTransferEvent, error)) *Token_GetTokenTransferEvents_Call {
	_c.Call.Return(run)
	return _c
}

// GetTotalSupply provides a mock function with given fields: ctx, tokenSymbol
func (_m *Token) GetTotalSupply(ctx context.Context, tokenSymbol string) (string, error) {
	ret := _m.Called(ctx, tokenSymbol)

	if len(ret) == 0 {
		panic("no return value specified for GetTotalSupply")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, tokenSymbol)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, tokenSymbol)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, tokenSymbol)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Token_GetTotalSupply_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTotalSupply'
type Token_GetTotalSupply_Call struct {
	*mock.Call
}

// GetTotalSupply is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenSymbol string
func (_e *Token_Expecter) GetTotalSupply(ctx interface{}, tokenSymbol interface{}) *Token_GetTotalSupply_Call {
	return &Token_GetTotalSupply_Call{Call: _e.mock.On("GetTotalSupply", ctx, tokenSymbol)}
}

func (_c *Token_GetTotalSupply_Call) Run(run func(ctx context.Context, tokenSymbol string)) *Token_GetTotalSupply_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Token_GetTotalSupply_Call) Return(_a0 string, _a1 error) *Token_GetTotalSupply_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Token_GetTotalSupply_Call) RunAndReturn(run func(context.Context, string) (string, error)) *Token_GetTotalSupply_Call {
	_c.Call.Return(run)
	return _c
}

// GetTransferFactory provides a mock function with given fields: ctx
func (_m *Token) GetTransferFactory(ctx context.Context) (*token.TransferFactoryInfo, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetTransferFactory")
	}

	var r0 *token.TransferFactoryInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*token.TransferFactoryInfo, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *token.TransferFactoryInfo); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*token.TransferFactoryInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Token_GetTransferFactory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTransferFactory'
type Token_GetTransferFactory_Call struct {
	*mock.Call
}

// GetTransferFactory is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Token_Expecter) GetTransferFactory(ctx interface{}) *Token_GetTransferFactory_Call {
	return &Token_GetTransferFactory_Call{Call: _e.mock.On("GetTransferFactory", ctx)}
}

func (_c *Token_GetTransferFactory_Call) Run(run func(ctx context.Context)) *Token_GetTransferFactory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *Token_GetTransferFactory_Call) Return(_a0 *token.TransferFactoryInfo, _a1 error) *Token_GetTransferFactory_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Token_GetTransferFactory_Call) RunAndReturn(run func(context.Context) (*token.TransferFactoryInfo, error)) *Token_GetTransferFactory_Call {
	_c.Call.Return(run)
	return _c
}

// Mint provides a mock function with given fields: ctx, req
func (_m *Token) Mint(ctx context.Context, req *token.MintRequest) (string, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Mint")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *token.MintRequest) (string, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *token.MintRequest) string); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *token.MintRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Token_Mint_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Mint'
type Token_Mint_Call struct {
	*mock.Call
}

// Mint is a helper method to define mock.On call
//   - ctx context.Context
//   - req *token.MintRequest
func (_e *Token_Expecter) Mint(ctx interface{}, req interface{}) *Token_Mint_Call {
	return &Token_Mint_Call{Call: _e.mock.On("Mint", ctx, req)}
}

func (_c *Token_Mint_Call) Run(run func(ctx context.Context, req *token.MintRequest)) *Token_Mint_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*token.MintRequest))
	})
	return _c
}

func (_c *Token_Mint_Call) Return(_a0 string, _a1 error) *Token_Mint_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Token_Mint_Call) RunAndReturn(run func(context.Context, *token.MintRequest) (string, error)) *Token_Mint_Call {
	_c.Call.Return(run)
	return _c
}

// PrepareTransfer provides a mock function with given fields: ctx, req
func (_m *Token) PrepareTransfer(ctx context.Context, req *token.PrepareTransferRequest) (*token.PreparedTransfer, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for PrepareTransfer")
	}

	var r0 *token.PreparedTransfer
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *token.PrepareTransferRequest) (*token.PreparedTransfer, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *token.PrepareTransferRequest) *token.PreparedTransfer); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*token.PreparedTransfer)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *token.PrepareTransferRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Token_PrepareTransfer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PrepareTransfer'
type Token_PrepareTransfer_Call struct {
	*mock.Call
}

// PrepareTransfer is a helper method to define mock.On call
//   - ctx context.Context
//   - req *token.PrepareTransferRequest
func (_e *Token_Expecter) PrepareTransfer(ctx interface{}, req interface{}) *Token_PrepareTransfer_Call {
	return &Token_PrepareTransfer_Call{Call: _e.mock.On("PrepareTransfer", ctx, req)}
}

func (_c *Token_PrepareTransfer_Call) Run(run func(ctx context.Context, req *token.PrepareTransferRequest)) *Token_PrepareTransfer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*token.PrepareTransferRequest))
	})
	return _c
}

func (_c *Token_PrepareTransfer_Call) Return(_a0 *token.PreparedTransfer, _a1 error) *Token_PrepareTransfer_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Token_PrepareTransfer_Call) RunAndReturn(run func(context.Context, *token.PrepareTransferRequest) (*token.PreparedTransfer, error)) *Token_PrepareTransfer_Call {
	_c.Call.Return(run)
	return _c
}

// TransferByFingerprint provides a mock function with given fields: ctx, fromFingerprint, toFingerprint, amount, tokenSymbol
func (_m *Token) TransferByFingerprint(ctx context.Context, fromFingerprint string, toFingerprint string, amount string, tokenSymbol string) error {
	ret := _m.Called(ctx, fromFingerprint, toFingerprint, amount, tokenSymbol)

	if len(ret) == 0 {
		panic("no return value specified for TransferByFingerprint")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string) error); ok {
		r0 = rf(ctx, fromFingerprint, toFingerprint, amount, tokenSymbol)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Token_TransferByFingerprint_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TransferByFingerprint'
type Token_TransferByFingerprint_Call struct {
	*mock.Call
}

// TransferByFingerprint is a helper method to define mock.On call
//   - ctx context.Context
//   - fromFingerprint string
//   - toFingerprint string
//   - amount string
//   - tokenSymbol string
func (_e *Token_Expecter) TransferByFingerprint(ctx interface{}, fromFingerprint interface{}, toFingerprint interface{}, amount interface{}, tokenSymbol interface{}) *Token_TransferByFingerprint_Call {
	return &Token_TransferByFingerprint_Call{Call: _e.mock.On("TransferByFingerprint", ctx, fromFingerprint, toFingerprint, amount, tokenSymbol)}
}

func (_c *Token_TransferByFingerprint_Call) Run(run func(ctx context.Context, fromFingerprint string, toFingerprint string, amount string, tokenSymbol string)) *Token_TransferByFingerprint_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(string))
	})
	return _c
}

func (_c *Token_TransferByFingerprint_Call) Return(_a0 error) *Token_TransferByFingerprint_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Token_TransferByFingerprint_Call) RunAndReturn(run func(context.Context, string, string, string, string) error) *Token_TransferByFingerprint_Call {
	_c.Call.Return(run)
	return _c
}

// TransferByPartyID provides a mock function with given fields: ctx, fromParty, toParty, amount, tokenSymbol
func (_m *Token) TransferByPartyID(ctx context.Context, fromParty string, toParty string, amount string, tokenSymbol string) error {
	ret := _m.Called(ctx, fromParty, toParty, amount, tokenSymbol)

	if len(ret) == 0 {
		panic("no return value specified for TransferByPartyID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string) error); ok {
		r0 = rf(ctx, fromParty, toParty, amount, tokenSymbol)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Token_TransferByPartyID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TransferByPartyID'
type Token_TransferByPartyID_Call struct {
	*mock.Call
}

// TransferByPartyID is a helper method to define mock.On call
//   - ctx context.Context
//   - fromParty string
//   - toParty string
//   - amount string
//   - tokenSymbol string
func (_e *Token_Expecter) TransferByPartyID(ctx interface{}, fromParty interface{}, toParty interface{}, amount interface{}, tokenSymbol interface{}) *Token_TransferByPartyID_Call {
	return &Token_TransferByPartyID_Call{Call: _e.mock.On("TransferByPartyID", ctx, fromParty, toParty, amount, tokenSymbol)}
}

func (_c *Token_TransferByPartyID_Call) Run(run func(ctx context.Context, fromParty string, toParty string, amount string, tokenSymbol string)) *Token_TransferByPartyID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(string))
	})
	return _c
}

func (_c *Token_TransferByPartyID_Call) Return(_a0 error) *Token_TransferByPartyID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Token_TransferByPartyID_Call) RunAndReturn(run func(context.Context, string, string, string, string) error) *Token_TransferByPartyID_Call {
	_c.Call.Return(run)
	return _c
}

// NewToken creates a new instance of Token. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewToken(t interface {
	mock.TestingT
	Cleanup(func())
}) *Token {
	mock := &Token{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
