// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	token "github.com/chainsafe/canton-middleware/pkg/cantonsdk/token"
	mock "github.com/stretchr/testify/mock"
)

// TransferCache is an autogenerated mock type for the TransferCache type
type TransferCache struct {
	mock.Mock
}

type TransferCache_Expecter struct {
	mock *mock.Mock
}

func (_m *TransferCache) EXPECT() *TransferCache_Expecter {
	return &TransferCache_Expecter{mock: &_m.Mock}
}

// GetAndDelete provides a mock function with given fields: transferID
func (_m *TransferCache) GetAndDelete(transferID string) (*token.PreparedTransfer, error) {
	ret := _m.Called(transferID)

	if len(ret) == 0 {
		panic("no return value specified for GetAndDelete")
	}

	var r0 *token.PreparedTransfer
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*token.PreparedTransfer, error)); ok {
		return rf(transferID)
	}
	if rf, ok := ret.Get(0).(func(string) *token.PreparedTransfer); ok {
		r0 = rf(transferID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*token.PreparedTransfer)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(transferID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TransferCache_GetAndDelete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAndDelete'
type TransferCache_GetAndDelete_Call struct {
	*mock.Call
}

// GetAndDelete is a helper method to define mock.On call
//   - transferID string
func (_e *TransferCache_Expecter) GetAndDelete(transferID interface{}) *TransferCache_GetAndDelete_Call {
	return &TransferCache_GetAndDelete_Call{Call: _e.mock.On("GetAndDelete", transferID)}
}

func (_c *TransferCache_GetAndDelete_Call) Run(run func(transferID string)) *TransferCache_GetAndDelete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *TransferCache_GetAndDelete_Call) Return(_a0 *token.PreparedTransfer, _a1 error) *TransferCache_GetAndDelete_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TransferCache_GetAndDelete_Call) RunAndReturn(run func(string) (*token.PreparedTransfer, error)) *TransferCache_GetAndDelete_Call {
	_c.Call.Return(run)
	return _c
}

// Put provides a mock function with given fields: _a0
func (_m *TransferCache) Put(_a0 *token.PreparedTransfer) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Put")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*token.PreparedTransfer) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TransferCache_Put_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Put'
type TransferCache_Put_Call struct {
	*mock.Call
}

// Put is a helper method to define mock.On call
//   - _a0 *token.PreparedTransfer
func (_e *TransferCache_Expecter) Put(_a0 interface{}) *TransferCache_Put_Call {
	return &TransferCache_Put_Call{Call: _e.mock.On("Put", _a0)}
}

func (_c *TransferCache_Put_Call) Run(run func(_a0 *token.PreparedTransfer)) *TransferCache_Put_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*token.PreparedTransfer))
	})
	return _c
}

func (_c *TransferCache_Put_Call) Return(_a0 error) *TransferCache_Put_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TransferCache_Put_Call) RunAndReturn(run func(*token.PreparedTransfer) error) *TransferCache_Put_Call {
	_c.Call.Return(run)
	return _c
}

// NewTransferCache creates a new instance of TransferCache. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTransferCache(t interface {
	mock.TestingT
	Cleanup(func())
}) *TransferCache {
	mock := &TransferCache{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
