// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	indexer "github.com/chainsafe/canton-middleware/pkg/indexer"
	mock "github.com/stretchr/testify/mock"
)

// IndexerReader is an autogenerated mock type for the IndexerReader type
type IndexerReader struct {
	mock.Mock
}

type IndexerReader_Expecter struct {
	mock *mock.Mock
}

func (_m *IndexerReader) EXPECT() *IndexerReader_Expecter {
	return &IndexerReader_Expecter{mock: &_m.Mock}
}

// GetOffersForParty provides a mock function with given fields: ctx, partyID, query, p
func (_m *IndexerReader) GetOffersForParty(ctx context.Context, partyID string, query indexer.OfferQuery, p indexer.Pagination) (*indexer.Page[indexer.PendingOffer], error) {
	ret := _m.Called(ctx, partyID, query, p)

	if len(ret) == 0 {
		panic("no return value specified for GetOffersForParty")
	}

	var r0 *indexer.Page[indexer.PendingOffer]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, indexer.OfferQuery, indexer.Pagination) (*indexer.Page[indexer.PendingOffer], error)); ok {
		return rf(ctx, partyID, query, p)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, indexer.OfferQuery, indexer.Pagination) *indexer.Page[indexer.PendingOffer]); ok {
		r0 = rf(ctx, partyID, query, p)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*indexer.Page[indexer.PendingOffer])
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, indexer.OfferQuery, indexer.Pagination) error); ok {
		r1 = rf(ctx, partyID, query, p)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IndexerReader_GetOffersForParty_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOffersForParty'
type IndexerReader_GetOffersForParty_Call struct {
	*mock.Call
}

// GetOffersForParty is a helper method to define mock.On call
//   - ctx context.Context
//   - partyID string
//   - query indexer.OfferQuery
//   - p indexer.Pagination
func (_e *IndexerReader_Expecter) GetOffersForParty(ctx interface{}, partyID interface{}, query interface{}, p interface{}) *IndexerReader_GetOffersForParty_Call {
	return &IndexerReader_GetOffersForParty_Call{Call: _e.mock.On("GetOffersForParty", ctx, partyID, query, p)}
}

func (_c *IndexerReader_GetOffersForParty_Call) Run(run func(ctx context.Context, partyID string, query indexer.OfferQuery, p indexer.Pagination)) *IndexerReader_GetOffersForParty_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(indexer.OfferQuery), args[3].(indexer.Pagination))
	})
	return _c
}

func (_c *IndexerReader_GetOffersForParty_Call) Return(_a0 *indexer.Page[indexer.PendingOffer], _a1 error) *IndexerReader_GetOffersForParty_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *IndexerReader_GetOffersForParty_Call) RunAndReturn(run func(context.Context, string, indexer.OfferQuery, indexer.Pagination) (*indexer.Page[indexer.PendingOffer], error)) *IndexerReader_GetOffersForParty_Call {
	_c.Call.Return(run)
	return _c
}

// NewIndexerReader creates a new instance of IndexerReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIndexerReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *IndexerReader {
	mock := &IndexerReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
