// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// PartyRegistry is an autogenerated mock type for the PartyRegistry type
type PartyRegistry struct {
	mock.Mock
}

type PartyRegistry_Expecter struct {
	mock *mock.Mock
}

func (_m *PartyRegistry) EXPECT() *PartyRegistry_Expecter {
	return &PartyRegistry_Expecter{mock: &_m.Mock}
}

// PartyExists provides a mock function with given fields: ctx, partyID
func (_m *PartyRegistry) PartyExists(ctx context.Context, partyID string) (bool, error) {
	ret := _m.Called(ctx, partyID)

	if len(ret) == 0 {
		panic("no return value specified for PartyExists")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, partyID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, partyID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, partyID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PartyRegistry_PartyExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PartyExists'
type PartyRegistry_PartyExists_Call struct {
	*mock.Call
}

// PartyExists is a helper method to define mock.On call
//   - ctx context.Context
//   - partyID string
func (_e *PartyRegistry_Expecter) PartyExists(ctx interface{}, partyID interface{}) *PartyRegistry_PartyExists_Call {
	return &PartyRegistry_PartyExists_Call{Call: _e.mock.On("PartyExists", ctx, partyID)}
}

func (_c *PartyRegistry_PartyExists_Call) Run(run func(ctx context.Context, partyID string)) *PartyRegistry_PartyExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *PartyRegistry_PartyExists_Call) Return(_a0 bool, _a1 error) *PartyRegistry_PartyExists_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PartyRegistry_PartyExists_Call) RunAndReturn(run func(context.Context, string) (bool, error)) *PartyRegistry_PartyExists_Call {
	_c.Call.Return(run)
	return _c
}

// NewPartyRegistry creates a new instance of PartyRegistry. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPartyRegistry(t interface {
	mock.TestingT
	Cleanup(func())
}) *PartyRegistry {
	mock := &PartyRegistry{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
