// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	indexer "github.com/chainsafe/canton-middleware/pkg/indexer"
	mock "github.com/stretchr/testify/mock"
)

// PendingOfferLister is an autogenerated mock type for the PendingOfferLister type
type PendingOfferLister struct {
	mock.Mock
}

type PendingOfferLister_Expecter struct {
	mock *mock.Mock
}

func (_m *PendingOfferLister) EXPECT() *PendingOfferLister_Expecter {
	return &PendingOfferLister_Expecter{mock: &_m.Mock}
}

// GetPendingOffersForParty provides a mock function with given fields: ctx, partyID, p
func (_m *PendingOfferLister) GetPendingOffersForParty(ctx context.Context, partyID string, p indexer.Pagination) (*indexer.Page[indexer.PendingOffer], error) {
	ret := _m.Called(ctx, partyID, p)

	if len(ret) == 0 {
		panic("no return value specified for GetPendingOffersForParty")
	}

	var r0 *indexer.Page[indexer.PendingOffer]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, indexer.Pagination) (*indexer.Page[indexer.PendingOffer], error)); ok {
		return rf(ctx, partyID, p)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, indexer.Pagination) *indexer.Page[indexer.PendingOffer]); ok {
		r0 = rf(ctx, partyID, p)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*indexer.Page[indexer.PendingOffer])
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, indexer.Pagination) error); ok {
		r1 = rf(ctx, partyID, p)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PendingOfferLister_GetPendingOffersForParty_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPendingOffersForParty'
type PendingOfferLister_GetPendingOffersForParty_Call struct {
	*mock.Call
}

// GetPendingOffersForParty is a helper method to define mock.On call
//   - ctx context.Context
//   - partyID string
//   - p indexer.Pagination
func (_e *PendingOfferLister_Expecter) GetPendingOffersForParty(ctx interface{}, partyID interface{}, p interface{}) *PendingOfferLister_GetPendingOffersForParty_Call {
	return &PendingOfferLister_GetPendingOffersForParty_Call{Call: _e.mock.On("GetPendingOffersForParty", ctx, partyID, p)}
}

func (_c *PendingOfferLister_GetPendingOffersForParty_Call) Run(run func(ctx context.Context, partyID string, p indexer.Pagination)) *PendingOfferLister_GetPendingOffersForParty_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(indexer.Pagination))
	})
	return _c
}

func (_c *PendingOfferLister_GetPendingOffersForParty_Call) Return(_a0 *indexer.Page[indexer.PendingOffer], _a1 error) *PendingOfferLister_GetPendingOffersForParty_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PendingOfferLister_GetPendingOffersForParty_Call) RunAndReturn(run func(context.Context, string, indexer.Pagination) (*indexer.Page[indexer.PendingOffer], error)) *PendingOfferLister_GetPendingOffersForParty_Call {
	_c.Call.Return(run)
	return _c
}

// NewPendingOfferLister creates a new instance of PendingOfferLister. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPendingOfferLister(t interface {
	mock.TestingT
	Cleanup(func())
}) *PendingOfferLister {
	mock := &PendingOfferLister{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
