// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	ethrpc "github.com/chainsafe/canton-middleware/pkg/ethrpc"
	mock "github.com/stretchr/testify/mock"
)

// EvmLogStore is an autogenerated mock type for the EvmLogStore type
type EvmLogStore struct {
	mock.Mock
}

type EvmLogStore_Expecter struct {
	mock *mock.Mock
}

func (_m *EvmLogStore) EXPECT() *EvmLogStore_Expecter {
	return &EvmLogStore_Expecter{mock: &_m.Mock}
}

// NewBlock provides a mock function with given fields: ctx, chainID
func (_m *EvmLogStore) NewBlock(ctx context.Context, chainID uint64) (ethrpc.PendingBlock, error) {
	ret := _m.Called(ctx, chainID)

	if len(ret) == 0 {
		panic("no return value specified for NewBlock")
	}

	var r0 ethrpc.PendingBlock
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64) (ethrpc.PendingBlock, error)); ok {
		return rf(ctx, chainID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64) ethrpc.PendingBlock); ok {
		r0 = rf(ctx, chainID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ethrpc.PendingBlock)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = rf(ctx, chainID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// EvmLogStore_NewBlock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewBlock'
type EvmLogStore_NewBlock_Call struct {
	*mock.Call
}

func (_e *EvmLogStore_Expecter) NewBlock(ctx interface{}, chainID interface{}) *EvmLogStore_NewBlock_Call {
	return &EvmLogStore_NewBlock_Call{Call: _e.mock.On("NewBlock", ctx, chainID)}
}

func (_c *EvmLogStore_NewBlock_Call) Run(run func(ctx context.Context, chainID uint64)) *EvmLogStore_NewBlock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64))
	})
	return _c
}

func (_c *EvmLogStore_NewBlock_Call) Return(_a0 ethrpc.PendingBlock, _a1 error) *EvmLogStore_NewBlock_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *EvmLogStore_NewBlock_Call) RunAndReturn(run func(context.Context, uint64) (ethrpc.PendingBlock, error)) *EvmLogStore_NewBlock_Call {
	_c.Call.Return(run)
	return _c
}

// GetEvmTransactionCount provides a mock function with given fields: ctx, fromAddress
func (_m *EvmLogStore) GetEvmTransactionCount(ctx context.Context, fromAddress string) (uint64, error) {
	ret := _m.Called(ctx, fromAddress)

	if len(ret) == 0 {
		panic("no return value specified for GetEvmTransactionCount")
	}

	var r0 uint64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (uint64, error)); ok {
		return rf(ctx, fromAddress)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) uint64); ok {
		r0 = rf(ctx, fromAddress)
	} else {
		r0 = ret.Get(0).(uint64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, fromAddress)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// EvmLogStore_GetEvmTransactionCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEvmTransactionCount'
type EvmLogStore_GetEvmTransactionCount_Call struct {
	*mock.Call
}

func (_e *EvmLogStore_Expecter) GetEvmTransactionCount(ctx interface{}, fromAddress interface{}) *EvmLogStore_GetEvmTransactionCount_Call {
	return &EvmLogStore_GetEvmTransactionCount_Call{Call: _e.mock.On("GetEvmTransactionCount", ctx, fromAddress)}
}

func (_c *EvmLogStore_GetEvmTransactionCount_Call) Run(run func(ctx context.Context, fromAddress string)) *EvmLogStore_GetEvmTransactionCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *EvmLogStore_GetEvmTransactionCount_Call) Return(_a0 uint64, _a1 error) *EvmLogStore_GetEvmTransactionCount_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *EvmLogStore_GetEvmTransactionCount_Call) RunAndReturn(run func(context.Context, string) (uint64, error)) *EvmLogStore_GetEvmTransactionCount_Call {
	_c.Call.Return(run)
	return _c
}

// NewEvmLogStore creates a new instance of EvmLogStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewEvmLogStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *EvmLogStore {
	mock := &EvmLogStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
