// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	indexer "github.com/chainsafe/canton-middleware/pkg/indexer"

	mock "github.com/stretchr/testify/mock"
)

// Store is an autogenerated mock type for the Store type
type Store struct {
	mock.Mock
}

type Store_Expecter struct {
	mock *mock.Mock
}

func (_m *Store) EXPECT() *Store_Expecter {
	return &Store_Expecter{mock: &_m.Mock}
}

// ApplyBalanceDelta provides a mock function with given fields: ctx, partyID, instrumentAdmin, instrumentID, delta
func (_m *Store) ApplyBalanceDelta(ctx context.Context, partyID string, instrumentAdmin string, instrumentID string, delta string) error {
	ret := _m.Called(ctx, partyID, instrumentAdmin, instrumentID, delta)

	if len(ret) == 0 {
		panic("no return value specified for ApplyBalanceDelta")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string) error); ok {
		r0 = rf(ctx, partyID, instrumentAdmin, instrumentID, delta)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Store_ApplyBalanceDelta_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ApplyBalanceDelta'
type Store_ApplyBalanceDelta_Call struct {
	*mock.Call
}

// ApplyBalanceDelta is a helper method to define mock.On call
//   - ctx context.Context
//   - partyID string
//   - instrumentAdmin string
//   - instrumentID string
//   - delta string
func (_e *Store_Expecter) ApplyBalanceDelta(ctx interface{}, partyID interface{}, instrumentAdmin interface{}, instrumentID interface{}, delta interface{}) *Store_ApplyBalanceDelta_Call {
	return &Store_ApplyBalanceDelta_Call{Call: _e.mock.On("ApplyBalanceDelta", ctx, partyID, instrumentAdmin, instrumentID, delta)}
}

func (_c *Store_ApplyBalanceDelta_Call) Run(run func(ctx context.Context, partyID string, instrumentAdmin string, instrumentID string, delta string)) *Store_ApplyBalanceDelta_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(string))
	})
	return _c
}

func (_c *Store_ApplyBalanceDelta_Call) Return(_a0 error) *Store_ApplyBalanceDelta_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Store_ApplyBalanceDelta_Call) RunAndReturn(run func(context.Context, string, string, string, string) error) *Store_ApplyBalanceDelta_Call {
	_c.Call.Return(run)
	return _c
}

// ApplySupplyDelta provides a mock function with given fields: ctx, instrumentAdmin, instrumentID, delta
func (_m *Store) ApplySupplyDelta(ctx context.Context, instrumentAdmin string, instrumentID string, delta string) error {
	ret := _m.Called(ctx, instrumentAdmin, instrumentID, delta)

	if len(ret) == 0 {
		panic("no return value specified for ApplySupplyDelta")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = rf(ctx, instrumentAdmin, instrumentID, delta)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Store_ApplySupplyDelta_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ApplySupplyDelta'
type Store_ApplySupplyDelta_Call struct {
	*mock.Call
}

// ApplySupplyDelta is a helper method to define mock.On call
//   - ctx context.Context
//   - instrumentAdmin string
//   - instrumentID string
//   - delta string
func (_e *Store_Expecter) ApplySupplyDelta(ctx interface{}, instrumentAdmin interface{}, instrumentID interface{}, delta interface{}) *Store_ApplySupplyDelta_Call {
	return &Store_ApplySupplyDelta_Call{Call: _e.mock.On("ApplySupplyDelta", ctx, instrumentAdmin, instrumentID, delta)}
}

func (_c *Store_ApplySupplyDelta_Call) Run(run func(ctx context.Context, instrumentAdmin string, instrumentID string, delta string)) *Store_ApplySupplyDelta_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *Store_ApplySupplyDelta_Call) Return(_a0 error) *Store_ApplySupplyDelta_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Store_ApplySupplyDelta_Call) RunAndReturn(run func(context.Context, string, string, string) error) *Store_ApplySupplyDelta_Call {
	_c.Call.Return(run)
	return _c
}

// LatestOffset provides a mock function with given fields: ctx
func (_m *Store) LatestOffset(ctx context.Context) (int64, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for LatestOffset")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (int64, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) int64); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store_LatestOffset_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LatestOffset'
type Store_LatestOffset_Call struct {
	*mock.Call
}

// LatestOffset is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Store_Expecter) LatestOffset(ctx interface{}) *Store_LatestOffset_Call {
	return &Store_LatestOffset_Call{Call: _e.mock.On("LatestOffset", ctx)}
}

func (_c *Store_LatestOffset_Call) Run(run func(ctx context.Context)) *Store_LatestOffset_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *Store_LatestOffset_Call) Return(_a0 int64, _a1 error) *Store_LatestOffset_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Store_LatestOffset_Call) RunAndReturn(run func(context.Context) (int64, error)) *Store_LatestOffset_Call {
	_c.Call.Return(run)
	return _c
}

// RunInTx provides a mock function with given fields: ctx, fn
func (_m *Store) RunInTx(ctx context.Context, fn func(context.Context, indexer.Store) error) error {
	ret := _m.Called(ctx, fn)

	if len(ret) == 0 {
		panic("no return value specified for RunInTx")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, func(context.Context, indexer.Store) error) error); ok {
		r0 = rf(ctx, fn)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Store_RunInTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RunInTx'
type Store_RunInTx_Call struct {
	*mock.Call
}

// RunInTx is a helper method to define mock.On call
//   - ctx context.Context
//   - fn func(context.Context , indexer.Store) error
func (_e *Store_Expecter) RunInTx(ctx interface{}, fn interface{}) *Store_RunInTx_Call {
	return &Store_RunInTx_Call{Call: _e.mock.On("RunInTx", ctx, fn)}
}

func (_c *Store_RunInTx_Call) Run(run func(ctx context.Context, fn func(context.Context, indexer.Store) error)) *Store_RunInTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(func(context.Context, indexer.Store) error))
	})
	return _c
}

func (_c *Store_RunInTx_Call) Return(_a0 error) *Store_RunInTx_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Store_RunInTx_Call) RunAndReturn(run func(context.Context, func(context.Context, indexer.Store) error) error) *Store_RunInTx_Call {
	_c.Call.Return(run)
	return _c
}

// SaveBatch provides a mock function with given fields: ctx, offset, events
func (_m *Store) SaveBatch(ctx context.Context, offset int64, events []*indexer.ParsedEvent) error {
	ret := _m.Called(ctx, offset, events)

	if len(ret) == 0 {
		panic("no return value specified for SaveBatch")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, []*indexer.ParsedEvent) error); ok {
		r0 = rf(ctx, offset, events)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Store_SaveBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveBatch'
type Store_SaveBatch_Call struct {
	*mock.Call
}

// SaveBatch is a helper method to define mock.On call
//   - ctx context.Context
//   - offset int64
//   - events []*indexer.ParsedEvent
func (_e *Store_Expecter) SaveBatch(ctx interface{}, offset interface{}, events interface{}) *Store_SaveBatch_Call {
	return &Store_SaveBatch_Call{Call: _e.mock.On("SaveBatch", ctx, offset, events)}
}

func (_c *Store_SaveBatch_Call) Run(run func(ctx context.Context, offset int64, events []*indexer.ParsedEvent)) *Store_SaveBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].([]*indexer.ParsedEvent))
	})
	return _c
}

func (_c *Store_SaveBatch_Call) Return(_a0 error) *Store_SaveBatch_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Store_SaveBatch_Call) RunAndReturn(run func(context.Context, int64, []*indexer.ParsedEvent) error) *Store_SaveBatch_Call {
	_c.Call.Return(run)
	return _c
}

// UpsertToken provides a mock function with given fields: ctx, token
func (_m *Store) UpsertToken(ctx context.Context, token *indexer.Token) error {
	ret := _m.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for UpsertToken")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *indexer.Token) error); ok {
		r0 = rf(ctx, token)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Store_UpsertToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertToken'
type Store_UpsertToken_Call struct {
	*mock.Call
}

// UpsertToken is a helper method to define mock.On call
//   - ctx context.Context
//   - token *indexer.Token
func (_e *Store_Expecter) UpsertToken(ctx interface{}, token interface{}) *Store_UpsertToken_Call {
	return &Store_UpsertToken_Call{Call: _e.mock.On("UpsertToken", ctx, token)}
}

func (_c *Store_UpsertToken_Call) Run(run func(ctx context.Context, token *indexer.Token)) *Store_UpsertToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*indexer.Token))
	})
	return _c
}

func (_c *Store_UpsertToken_Call) Return(_a0 error) *Store_UpsertToken_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Store_UpsertToken_Call) RunAndReturn(run func(context.Context, *indexer.Token) error) *Store_UpsertToken_Call {
	_c.Call.Return(run)
	return _c
}

// NewStore creates a new instance of Store. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *Store {
	mock := &Store{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
