// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	streaming "github.com/chainsafe/canton-middleware/pkg/cantonsdk/streaming"
)

// EventFetcher is an autogenerated mock type for the EventFetcher type
type EventFetcher struct {
	mock.Mock
}

type EventFetcher_Expecter struct {
	mock *mock.Mock
}

func (_m *EventFetcher) EXPECT() *EventFetcher_Expecter {
	return &EventFetcher_Expecter{mock: &_m.Mock}
}

// Events provides a mock function with no fields
func (_m *EventFetcher) Events() <-chan *streaming.Batch[interface{}] {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Events")
	}

	var r0 <-chan *streaming.Batch[interface{}]
	if rf, ok := ret.Get(0).(func() <-chan *streaming.Batch[interface{}]); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan *streaming.Batch[interface{}])
		}
	}

	return r0
}

// EventFetcher_Events_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Events'
type EventFetcher_Events_Call struct {
	*mock.Call
}

// Events is a helper method to define mock.On call
func (_e *EventFetcher_Expecter) Events() *EventFetcher_Events_Call {
	return &EventFetcher_Events_Call{Call: _e.mock.On("Events")}
}

func (_c *EventFetcher_Events_Call) Run(run func()) *EventFetcher_Events_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *EventFetcher_Events_Call) Return(_a0 <-chan *streaming.Batch[interface{}]) *EventFetcher_Events_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *EventFetcher_Events_Call) RunAndReturn(run func() <-chan *streaming.Batch[interface{}]) *EventFetcher_Events_Call {
	_c.Call.Return(run)
	return _c
}

// Start provides a mock function with given fields: ctx, offset
func (_m *EventFetcher) Start(ctx context.Context, offset int64) {
	_m.Called(ctx, offset)
}

// EventFetcher_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type EventFetcher_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - ctx context.Context
//   - offset int64
func (_e *EventFetcher_Expecter) Start(ctx interface{}, offset interface{}) *EventFetcher_Start_Call {
	return &EventFetcher_Start_Call{Call: _e.mock.On("Start", ctx, offset)}
}

func (_c *EventFetcher_Start_Call) Run(run func(ctx context.Context, offset int64)) *EventFetcher_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *EventFetcher_Start_Call) Return() *EventFetcher_Start_Call {
	_c.Call.Return()
	return _c
}

func (_c *EventFetcher_Start_Call) RunAndReturn(run func(context.Context, int64)) *EventFetcher_Start_Call {
	_c.Run(run)
	return _c
}

// NewEventFetcher creates a new instance of EventFetcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEventFetcher(t interface {
	mock.TestingT
	Cleanup(func())
}) *EventFetcher {
	mock := &EventFetcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
